{"abstract":[{"text":"Display custom advertisements within the reader.","type":"text"}],"seeAlsoSections":[{"anchor":"Features","title":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"generated":true}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"By default the PSReaderUI SDK does not display any advertisements.","type":"text"},{"text":" ","type":"text"},{"text":"Advertisement support is opt-in through the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate","type":"reference"},{"text":" protocol.","type":"text"},{"text":" ","type":"text"},{"text":"Implement this delegate to provide view controllers that the SDK embeds as","type":"text"},{"text":" ","type":"text"},{"text":"banner ads within the reader.","type":"text"}]},{"level":2,"type":"heading","anchor":"Protocol-Methods","text":"Protocol Methods"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate"},{"type":"text","text":" protocol defines three methods, each returning an"},{"type":"text","text":" "},{"type":"text","text":"optional "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertViewController"},{"type":"text","text":":"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate\/advertViewControllerForBottomBanner(inPublished:edition:)"},{"text":" ","type":"text"},{"text":"— bottom banner in ","type":"text"},{"inlineContent":[{"text":"feed edition","type":"text"}],"type":"strong"},{"text":" readers.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate\/advertViewControllerForBottomBanner(inReplicaEdition:)"},{"type":"text","text":" "},{"type":"text","text":"— bottom banner in "},{"inlineContent":[{"type":"text","text":"replica edition"}],"type":"strong"},{"type":"text","text":" readers."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate\/advertViewControllerForTopBanner(inReplicaEdition:)"},{"type":"text","text":" "},{"type":"text","text":"— top banner in "},{"inlineContent":[{"type":"text","text":"replica edition"}],"type":"strong"},{"type":"text","text":" readers."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" from any method to omit the ad placement for that context."}]},{"style":"note","type":"aside","content":[{"inlineContent":[{"text":"Feed editions support bottom banners only. Replica editions support","type":"text"},{"text":" ","type":"text"},{"text":"both top and bottom banners.","type":"text"}],"type":"paragraph"}],"name":"Note"},{"level":2,"type":"heading","anchor":"Creating-an-AdvertViewController","text":"Creating an AdvertViewController"},{"type":"paragraph","inlineContent":[{"text":"Your ad view controller must conform to ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertViewController","isActive":true,"type":"reference"},{"text":". The SDK","type":"text"},{"text":" ","type":"text"},{"text":"embeds it as a ","type":"text"},{"inlineContent":[{"type":"text","text":"child view controller"}],"type":"strong"},{"text":" within the reader interface — it is","type":"text"},{"text":" ","type":"text"},{"text":"added via ","type":"text"},{"code":"addChild","type":"codeVoice"},{"text":" and its view is placed inside the reader’s view hierarchy.","type":"text"},{"text":" ","type":"text"},{"text":"This means your ad banner participates in the standard UIKit containment","type":"text"},{"text":" ","type":"text"},{"text":"lifecycle (","type":"text"},{"code":"willMove(toParent:)","type":"codeVoice"},{"text":", ","type":"text"},{"code":"didMove(toParent:)","type":"codeVoice"},{"text":", etc.).","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["import PSReaderUI","","class MyAdBanner: UIViewController, PSReaderUI.AdvertViewController {","    override func viewDidLoad() {","        super.viewDidLoad()","        \/\/ Load and display your ad content","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"The banner’s height is determined by your view’s Auto Layout constraints. Set","type":"text"},{"text":" ","type":"text"},{"text":"an intrinsic content size or explicit height constraint on your ad view to","type":"text"},{"text":" ","type":"text"},{"text":"control how tall the banner appears in the reader.","type":"text"}]},{"anchor":"Assigning-the-Delegate","level":2,"text":"Assigning the Delegate","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Set the delegate on your ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","type":"reference"},{"text":":","type":"text"}]},{"code":["struct MyAdvertDelegate: PSReaderUI.AdvertDelegate {","    func advertViewControllerForBottomBanner(","        inPublished published: PSEPublished,","        edition: PSEEdition","    ) -> AdvertViewController? {","        return MyAdBanner()","    }","","    func advertViewControllerForBottomBanner(","        inReplicaEdition edition: PSEdition","    ) -> AdvertViewController? {","        return MyAdBanner()","    }","","    func advertViewControllerForTopBanner(","        inReplicaEdition edition: PSEdition","    ) -> AdvertViewController? {","        return nil \/\/ No top banner","    }","}","","globalConfig.advertDelegate = MyAdvertDelegate()"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate is inherited by all reader configurations created from the"},{"type":"text","text":" "},{"type":"text","text":"global configuration."}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/advertisements"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/advertisements"]}],"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","interfaceLanguage":"swift"},"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"PSReaderUI"}],"title":"Advertisements"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"title":"GlobalConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlobalConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GlobalConfiguration","kind":"identifier"}],"url":"\/documentation\/psreaderui\/globalconfiguration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","abstract":[{"type":"text","text":"A configuration object that provides global settings and delegates for"},{"type":"text","text":" "},{"type":"text","text":"customizing the SDK’s behavior and appearance."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AdvertDelegate/advertViewControllerForBottomBanner(inReplicaEdition:)":{"abstract":[{"type":"text","text":"Provides a view controller for displaying a bottom advert banner within replica (PDF) editions."}],"required":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate\/advertViewControllerForBottomBanner(inReplicaEdition:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertViewControllerForBottomBanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inReplicaEdition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEdition","text":"PSEdition"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10PSReaderUI20AdvertViewControllerP","text":"AdvertViewController"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/psreaderui\/advertdelegate\/advertviewcontrollerforbottombanner(inreplicaedition:)","type":"topic","title":"advertViewControllerForBottomBanner(inReplicaEdition:)","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"role":"article","url":"\/documentation\/psreaderui\/paywall-integration","type":"topic","abstract":[{"type":"text","text":"Restrict access to premium content with custom paywall screens."}],"title":"Paywall Integration","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AdvertDelegate/advertViewControllerForBottomBanner(inPublished:edition:)":{"type":"topic","url":"\/documentation\/psreaderui\/advertdelegate\/advertviewcontrollerforbottombanner(inpublished:edition:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertViewControllerForBottomBanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inPublished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEPublished","text":"PSEPublished"},{"kind":"text","text":", "},{"kind":"externalParam","text":"edition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEEdition","text":"PSEEdition"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10PSReaderUI20AdvertViewControllerP","text":"AdvertViewController"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate\/advertViewControllerForBottomBanner(inPublished:edition:)","title":"advertViewControllerForBottomBanner(inPublished:edition:)","required":true,"kind":"symbol","abstract":[{"type":"text","text":"Provides a view controller for displaying a bottom advert banner within"},{"type":"text","text":" "},{"type":"text","text":"published (mixed HTML \/ PDF) editions."}],"role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AdvertDelegate/advertViewControllerForTopBanner(inReplicaEdition:)":{"abstract":[{"text":"Provides a view controller for displaying a top advert banner within replica (PDF) editions.","type":"text"}],"required":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate\/advertViewControllerForTopBanner(inReplicaEdition:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"advertViewControllerForTopBanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inReplicaEdition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEdition","text":"PSEdition"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10PSReaderUI20AdvertViewControllerP","text":"AdvertViewController"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/psreaderui\/advertdelegate\/advertviewcontrollerfortopbanner(inreplicaedition:)","type":"topic","title":"advertViewControllerForTopBanner(inReplicaEdition:)","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AdvertDelegate":{"abstract":[{"type":"text","text":"A delegate protocol to enable custom advertising placements within the SDK."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvertDelegate"}],"title":"AdvertDelegate","kind":"symbol","url":"\/documentation\/psreaderui\/advertdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvertDelegate"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"type":"topic","abstract":[{"text":"A UI framework for building digital newspaper and magazine reader experiences on iOS.","type":"text"}],"url":"\/documentation\/psreaderui","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","title":"PSReaderUI","role":"collection","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"abstract":[{"type":"text","text":"Track user interactions and content engagement across the PSReaderUI SDK."}],"role":"article","kind":"article","url":"\/documentation\/psreaderui\/analytics","title":"Analytics","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"url":"\/documentation\/psreaderui\/sharing","kind":"article","title":"Sharing","abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"role":"article","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"role":"article","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","abstract":[{"text":"Add audio playback of article content using the SDK’s text-to-speech system.","type":"text"}],"type":"topic","title":"Text-to-Speech","url":"\/documentation\/psreaderui\/text-to-speech"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"type":"topic","role":"article","title":"Media Playback","url":"\/documentation\/psreaderui\/media-playback","kind":"article","abstract":[{"type":"text","text":"Enable video and media playback within the reader."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AdvertViewController":{"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdvertViewController","kind":"identifier"}],"abstract":[{"text":"A protocol representing a view controller used for displaying advertisements","type":"text"},{"text":" ","type":"text"},{"text":"within the PSReaderUI SDK.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertViewController","url":"\/documentation\/psreaderui\/advertviewcontroller","title":"AdvertViewController","role":"symbol","navigatorTitle":[{"text":"AdvertViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"title":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"generated":true,"anchor":"Features"}],"op":"replace","path":"\/seeAlsoSections"}]}]}