{"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"Analytics","role":"article","roleHeading":"Article","modules":[{"name":"PSReaderUI"}]},"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","anchor":"Overview","level":2,"type":"heading"},{"inlineContent":[{"text":"All analytics events are reported through the ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel","isActive":true,"type":"reference"},{"text":" singleton. To","type":"text"},{"text":" ","type":"text"},{"text":"begin receiving events, create a class that conforms to ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventSubscriber","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"and subscribe it to the shared channel:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["import PSReaderUI","","class AnalyticsHandler: PSReaderUI.EventSubscriber {","    func analytics(event: PSReaderUI.EventChannel.AnalyticsEvent) {","        switch event {","        \/\/ handle events","        }","    }","}","","let subscriber = AnalyticsHandler()","PSReaderUI.EventChannel.shared.subscribe(subscriber)"]},{"name":"Important","style":"important","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel","isActive":true},{"text":" holds a ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"weak"}]},{"text":" reference to each","type":"text"},{"text":" ","type":"text"},{"text":"subscriber. Maintain a strong reference to your subscriber (for example, as a","type":"text"},{"text":" ","type":"text"},{"text":"property on your app delegate or coordinator) to prevent it from being","type":"text"},{"text":" ","type":"text"},{"text":"deallocated. You do not need to explicitly unsubscribe.","type":"text"}],"type":"paragraph"}],"type":"aside"},{"inlineContent":[{"text":"Events are always delivered on the ","type":"text"},{"inlineContent":[{"text":"main thread","type":"text"}],"type":"strong"},{"text":".","type":"text"}],"type":"paragraph"},{"text":"Replica vs Feed Events","anchor":"Replica-vs-Feed-Events","level":2,"type":"heading"},{"inlineContent":[{"text":"Which events the SDK fires depends on the backend system your publication uses.","type":"text"},{"text":" ","type":"text"},{"text":"Replica editions produce ","type":"text"},{"type":"codeVoice","code":"replica*"},{"text":" events while feed editions produce","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"feedEdition*"},{"text":" events. Some events (such as carousel views and bookmark","type":"text"},{"text":" ","type":"text"},{"text":"operations) apply to both systems.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Consult the PageSuite portal or your account manager to determine which system"},{"type":"text","text":" "},{"type":"text","text":"applies to your publications. See "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","isActive":true},{"type":"text","text":" for"},{"type":"text","text":" "},{"type":"text","text":"background."}],"type":"paragraph"},{"text":"Event Categories","anchor":"Event-Categories","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/AnalyticsEvent","isActive":true},{"type":"text","text":" enumeration defines every event the SDK"},{"type":"text","text":" "},{"type":"text","text":"reports. Below is a summary of the main categories. See the"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/AnalyticsEvent","isActive":true},{"type":"text","text":" symbol page for the complete list."}],"type":"paragraph"},{"text":"Carousel Events","anchor":"Carousel-Events","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"Fired when a carousel section becomes visible, providing the section index,"},{"type":"text","text":" "},{"type":"text","text":"name, and content type through "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/CarouselEventContext"},{"type":"text","text":"."}],"type":"paragraph"},{"text":"Edition Lifecycle","anchor":"Edition-Lifecycle","level":3,"type":"heading"},{"inlineContent":[{"text":"Events for edition launches, downloads, and deletions. For example,","type":"text"},{"text":" ","type":"text"},{"code":"replicaLaunch","type":"codeVoice"},{"text":" fires when a user opens a replica edition, and","type":"text"},{"text":" ","type":"text"},{"code":"feedEditionDownloaded","type":"codeVoice"},{"text":" fires when a feed edition finishes downloading.","type":"text"}],"type":"paragraph"},{"text":"Page View and Navigation","anchor":"Page-View-and-Navigation","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"Page view events fire as the user navigates through an edition. Replica"},{"type":"text","text":" "},{"type":"text","text":"editions report "},{"type":"codeVoice","code":"replicaPageView"},{"type":"text","text":" with page numbers; feed editions report"},{"type":"text","text":" "},{"type":"codeVoice","code":"feedEditionArticleView"},{"type":"text","text":", "},{"type":"codeVoice","code":"feedEditionSectionView"},{"type":"text","text":", or"},{"type":"text","text":" "},{"type":"codeVoice","code":"feedEditionOtherPageView"},{"type":"text","text":" depending on the page type."}],"type":"paragraph"},{"inlineContent":[{"text":"The content browser also emits events when the user opens it or taps","type":"text"},{"text":" ","type":"text"},{"text":"navigation controls within it.","type":"text"}],"type":"paragraph"},{"text":"Bookmark Events","anchor":"Bookmark-Events","level":3,"type":"heading"},{"inlineContent":[{"text":"Bookmark and unbookmark events fire for both pages and articles. Each event","type":"text"},{"text":" ","type":"text"},{"text":"includes the bookmark object with edition and page metadata.","type":"text"}],"type":"paragraph"},{"text":"Share and Print Events","anchor":"Share-and-Print-Events","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"Share and print actions are tracked separately for replica pages, replica"},{"type":"text","text":" "},{"type":"text","text":"articles, and feed edition pages. These fire when the user initiates the"},{"type":"text","text":" "},{"type":"text","text":"action from the navigation bar."}],"type":"paragraph"},{"text":"Article-Specific Events","anchor":"Article-Specific-Events","level":3,"type":"heading"},{"inlineContent":[{"text":"In replica editions, additional events track article taps, article link taps,","type":"text"},{"text":" ","type":"text"},{"text":"and text size changes. Each carries a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/ReplicaArticleEventContext","type":"reference"},{"text":" ","type":"text"},{"text":"with the edition and article details.","type":"text"}],"type":"paragraph"},{"text":"Context Objects","anchor":"Context-Objects","level":2,"type":"heading"},{"inlineContent":[{"text":"Each event carries an associated context object that provides the relevant","type":"text"},{"text":" ","type":"text"},{"text":"metadata. The four context types are:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/CarouselEventContext","isActive":true,"type":"reference"},{"text":" — section index, name, and content","type":"text"},{"text":" ","type":"text"},{"text":"type. Use ","type":"text"},{"code":"sectionName","type":"codeVoice"},{"text":" to identify which tab the user is viewing and","type":"text"},{"text":" ","type":"text"},{"code":"contentType","type":"codeVoice"},{"text":" to distinguish between archive, bookmarks, and downloads.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/ReplicaEventContext"},{"type":"text","text":" — edition, page number, and spread page"},{"type":"text","text":" "},{"type":"text","text":"numbers for double-page mode. The "},{"type":"codeVoice","code":"edition"},{"type":"text","text":" property gives you access to"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"PSEdition"},{"type":"text","text":" model, and "},{"type":"codeVoice","code":"pageNumber"},{"type":"text","text":" identifies the current page."}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/ReplicaArticleEventContext","isActive":true,"type":"reference"},{"text":" — edition and article. The","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"article"},{"text":" property contains the article headline, ID, and share link.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/FeedEditionEventContext","isActive":true},{"type":"text","text":" — published object, edition, and"},{"type":"text","text":" "},{"type":"text","text":"current page spread. The "},{"type":"codeVoice","code":"published"},{"type":"text","text":" property provides the "},{"type":"codeVoice","code":"PSEPublished"},{"type":"text","text":" "},{"type":"text","text":"model with edition metadata, and "},{"type":"codeVoice","code":"edition"},{"type":"text","text":" contains page-level details."}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"See the symbol pages for each context type for the full list of properties."}],"type":"paragraph"},{"name":"Tip","style":"tip","content":[{"inlineContent":[{"type":"text","text":"Map SDK event names to your analytics provider’s conventions in one"},{"type":"text","text":" "},{"type":"text","text":"central place. A "},{"type":"codeVoice","code":"switch"},{"type":"text","text":" over "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/AnalyticsEvent","isActive":true},{"type":"text","text":" with a"},{"type":"text","text":" "},{"type":"codeVoice","code":"default"},{"type":"text","text":" case ensures you gracefully handle new events added in future SDK"},{"type":"text","text":" "},{"type":"text","text":"versions without a compile error."}],"type":"paragraph"}],"type":"aside"},{"text":"Example","anchor":"Example","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A practical example mapping common events to an analytics provider:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["class MyAnalyticsSubscriber: PSReaderUI.EventSubscriber {","    func analytics(event: PSReaderUI.EventChannel.AnalyticsEvent) {","        switch event {","        case .carouselView(let context):","            trackScreen(\"carousel_\\(context.sectionName)\")","","        case .replicaLaunch(let context):","            trackEvent(\"edition_open\", properties: [","                \"page\": context.pageNumber ?? 0","            ])","","        case .feedEditionLaunch(let published):","            trackEvent(\"edition_open\", properties: [","                \"edition\": published.guid","            ])","","        case .replicaPageView(let context):","            trackEvent(\"page_view\", properties: [","                \"page\": context.pageNumber ?? 0","            ])","","        case .feedEditionArticleView(let context):","            trackEvent(\"article_view\", properties: [","                \"edition\": context.edition?.guid ?? \"\"","            ])","","        case .replicaPageBookmark, .feedEditionPageBookmark,","             .feedEditionArticleBookmark, .replicaArticleBookmark:","            trackEvent(\"bookmark_added\")","","        case .replicaPageShare, .feedEditionShare:","            trackEvent(\"share\")","","        default:","            break","        }","    }","","    private func trackEvent(_ name: String, properties: [String: Any] = [:]) {","        \/\/ Forward to your analytics provider","    }","","    private func trackScreen(_ name: String) {","        \/\/ Forward to your analytics provider","    }","}"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/analytics"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/analytics"]}],"seeAlsoSections":[{"title":"Features","anchor":"Features","generated":true,"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"]}],"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","interfaceLanguage":"swift"},"abstract":[{"text":"Track user interactions and content engagement across the PSReaderUI SDK.","type":"text"}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"url":"\/documentation\/psreaderui\/advertisements","type":"topic","abstract":[{"text":"Display custom advertisements within the reader.","type":"text"}],"kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","role":"article","title":"Advertisements"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventChannel":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel","role":"symbol","url":"\/documentation\/psreaderui\/eventchannel","type":"topic","abstract":[{"type":"text","text":"Singleton class responsible for analytics reporting."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventChannel","kind":"identifier"}],"navigatorTitle":[{"text":"EventChannel","kind":"identifier"}],"kind":"symbol","title":"EventChannel"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventChannel/AnalyticsEvent":{"type":"topic","title":"EventChannel.AnalyticsEvent","url":"\/documentation\/psreaderui\/eventchannel\/analyticsevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnalyticsEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AnalyticsEvent","kind":"identifier"}],"abstract":[{"type":"text","text":"An analytics event and any relevant context associated with the event."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/AnalyticsEvent"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventSubscriber":{"navigatorTitle":[{"text":"EventSubscriber","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that listens to analytics events broadcast from an "},{"type":"codeVoice","code":"EventChannel"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventSubscriber","kind":"symbol","url":"\/documentation\/psreaderui\/eventsubscriber","title":"EventSubscriber","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventSubscriber","kind":"identifier"}],"role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"kind":"article","title":"Media Playback","url":"\/documentation\/psreaderui\/media-playback","type":"topic","role":"article","abstract":[{"text":"Enable video and media playback within the reader.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventChannel/ReplicaEventContext":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/ReplicaEventContext","title":"EventChannel.ReplicaEventContext","navigatorTitle":[{"text":"ReplicaEventContext","kind":"identifier"}],"abstract":[{"text":"Context object for replica events.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReplicaEventContext","kind":"identifier"}],"url":"\/documentation\/psreaderui\/eventchannel\/replicaeventcontext","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"title":"Paywall Integration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","abstract":[{"text":"Restrict access to premium content with custom paywall screens.","type":"text"}],"url":"\/documentation\/psreaderui\/paywall-integration","type":"topic","kind":"article","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventChannel/ReplicaArticleEventContext":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReplicaArticleEventContext","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ReplicaArticleEventContext","kind":"identifier"}],"url":"\/documentation\/psreaderui\/eventchannel\/replicaarticleeventcontext","abstract":[{"text":"Context object for replica article events.","type":"text"}],"title":"EventChannel.ReplicaArticleEventContext","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/ReplicaArticleEventContext"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Replica-and-Feed-Editions":{"title":"Replica and Feed Editions","type":"topic","role":"article","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","abstract":[{"type":"text","text":"Understand the two backend systems that power PSReaderUI content."}],"url":"\/documentation\/psreaderui\/replica-and-feed-editions"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventChannel/FeedEditionEventContext":{"title":"EventChannel.FeedEditionEventContext","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/FeedEditionEventContext","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedEditionEventContext"}],"url":"\/documentation\/psreaderui\/eventchannel\/feededitioneventcontext","abstract":[{"type":"text","text":"Context object for feed edition events."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeedEditionEventContext"}],"kind":"symbol","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","url":"\/documentation\/psreaderui\/text-to-speech","kind":"article","type":"topic","abstract":[{"type":"text","text":"Add audio playback of article content using the SDK’s text-to-speech system."}],"title":"Text-to-Speech","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"type":"topic","kind":"article","url":"\/documentation\/psreaderui\/sharing","title":"Sharing","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventChannel/CarouselEventContext":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"CarouselEventContext","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/CarouselEventContext","title":"EventChannel.CarouselEventContext","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CarouselEventContext","kind":"identifier"}],"abstract":[{"type":"text","text":"Context object for carousel events."}],"url":"\/documentation\/psreaderui\/eventchannel\/carouseleventcontext"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"url":"\/documentation\/psreaderui","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"],"generated":true,"title":"Features","anchor":"Features"}],"op":"replace","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}