{"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Customization","generated":true,"title":"Customization","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"]}],"sections":[],"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","isActive":true},{"type":"text","text":" is the primary entry point for the PSReaderUI SDK."},{"type":"text","text":" "},{"type":"text","text":"It presents a tabbed interface with horizontal section ribbons at the top and"},{"type":"text","text":" "},{"type":"text","text":"content grids below. Each section can display edition archives, bookmarks,"},{"type":"text","text":" "},{"type":"text","text":"downloads, or kiosk grids."}]},{"inlineContent":[{"text":"Sections are defined as an array of ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController\/SectionItem","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"values passed to the initializer. The SDK supports three kinds of section","type":"text"},{"text":" ","type":"text"},{"text":"items: dynamic archives, single sections, and subsection groups.","type":"text"}],"type":"paragraph"},{"anchor":"Dynamic-Archives-Recommended","type":"heading","level":2,"text":"Dynamic Archives (Recommended)"},{"type":"paragraph","inlineContent":[{"text":"The simplest way to populate the carousel is with a ","type":"text"},{"inlineContent":[{"text":"shortcode","type":"text"}],"type":"strong"},{"text":" and","type":"text"},{"text":" ","type":"text"},{"code":".dynamicArchive","type":"codeVoice"},{"text":". The SDK fetches publication configuration from the","type":"text"},{"text":" ","type":"text"},{"text":"PageSuite backend and automatically creates the appropriate content sections:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let carouselVC = PSReaderUI.CarouselViewController(","    globalConfig: globalConfig,","    sections: [","        .dynamicArchive(\"Editions\", shortcode: \"SHORTCODE\"),","        .subsections(\"My Content\", [","            .init(name: \"Bookmarks\", type: .bookmarks(type: .all)),","            .init(name: \"Downloads\", type: .downloads(type: .all))","        ])","    ]",")"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController\/refreshDynamicArchives(completion:)","isActive":true},{"type":"text","text":" at any"},{"type":"text","text":" "},{"type":"text","text":"time to re-fetch the remote configuration and update the carousel content."}]},{"type":"heading","text":"Manual Sections","level":2,"anchor":"Manual-Sections"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For full control, define sections explicitly using "},{"type":"codeVoice","code":".section"},{"type":"text","text":" or"},{"type":"text","text":" "},{"type":"codeVoice","code":".subsections"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["let sections: [PSReaderUI.CarouselViewController.SectionItem] = [","    .section(.init(name: \"Latest\", type: .feedArchive(guid: \"APP_GUID\"))),","    .subsections(\"More\", [","        .init(name: \"Archive\", type: .replicaArchive(guid: \"PUB_GUID\")),","        .init(name: \"Bookmarks\", type: .bookmarks(type: .all)),","        .init(name: \"Downloads\", type: .downloads(type: .all))","    ])","]"]},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":".section","type":"codeVoice"},{"text":" creates a top-level tab with a single content view. A","type":"text"},{"text":" ","type":"text"},{"code":".subsections","type":"codeVoice"},{"text":" creates a top-level tab with a secondary ribbon that lets","type":"text"},{"text":" ","type":"text"},{"text":"users switch between multiple content views.","type":"text"}]},{"text":"Content Types","anchor":"Content-Types","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController\/ContentType","type":"reference","isActive":true},{"type":"text","text":" enum defines all available content"},{"type":"text","text":" "},{"type":"text","text":"sources:"}]},{"header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Content Type","type":"text"}]}],[{"inlineContent":[{"text":"Description","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".feedArchive(guid:)","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Feed edition archive identified by an application GUID."}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".replicaArchive(guid:, supplements:)"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Replica edition archive identified by a publication GUID. Pass an optional ","type":"text"},{"code":"supplements","type":"codeVoice"},{"text":" array of publication GUIDs to include supplemental editions alongside the main archive.","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".feedPublicationKiosk(publications:)"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Grid of multiple feed publications (kiosk layout). Each cell represents a different publication and tapping one opens its archive.","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".replicaPublicationKiosk(publications:)","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Grid of multiple replica publications (kiosk layout). Same multi-publication grid for replica editions."}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".bookmarks(type:)","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"User’s bookmarked pages and articles. Filter by type."}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".downloads(type:)"}],"type":"paragraph"}],[{"inlineContent":[{"text":"User’s downloaded editions. Filter by type.","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".search(config:)"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Full-text search across feed edition articles and pages. Requires a ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration","type":"reference","isActive":true},{"text":". See ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]]],"type":"table"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","isActive":true},{"type":"text","text":" to determine whether your publications use"},{"type":"text","text":" "},{"type":"text","text":"feed or replica content types."}]},{"text":"Per-Section Configuration Overrides","anchor":"Per-Section-Configuration-Overrides","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Each content type accepts an optional configuration parameter. Use this to","type":"text"},{"text":" ","type":"text"},{"text":"override the global defaults for a specific section — for example, to use a","type":"text"},{"text":" ","type":"text"},{"text":"different date formatter or thumbnail aspect ratio:","type":"text"}]},{"syntax":"swift","code":["var specialArchiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","specialArchiveConfig.aspectRatio = 0.75","specialArchiveConfig.thumbnailContentMode = .flexibleHeight(estimatedAspectRatio: 0.75)","",".section(.init(","    name: \"Special Edition\",","    type: .feedArchive(guid: \"GUID\", config: specialArchiveConfig)","))"],"type":"codeListing"},{"text":"Dismiss Button and Safe Area","anchor":"Dismiss-Button-and-Safe-Area","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When presenting the carousel modally, add a dismiss button:"}]},{"syntax":"swift","code":["var carouselConfig = PSReaderUI.CarouselConfiguration(globalConfig: globalConfig)","carouselConfig.dismissButton = .dismissButton(position: .leading())"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Control which safe area edges the carousel ignores. This is useful when"},{"type":"text","text":" "},{"type":"text","text":"embedding the carousel in a container that already provides its own safe"},{"type":"text","text":" "},{"type":"text","text":"area handling:"}]},{"syntax":"swift","code":["carouselConfig.ignoreSafeArea = .bottom"],"type":"codeListing"},{"text":"Complete Example","anchor":"Complete-Example","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"A carousel combining a dynamic archive, a manual section with a per-section","type":"text"},{"text":" ","type":"text"},{"text":"configuration override, and a subsection group:","type":"text"}]},{"syntax":"swift","code":["let globalConfig = PSReaderUI.GlobalConfiguration(","    apiKey: apiKey,","    accountGUID: accountGUID",")","","\/\/ Per-section override for the premium archive","var premiumConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","premiumConfig.aspectRatio = 0.75","","let carouselVC = PSReaderUI.CarouselViewController(","    globalConfig: globalConfig,","    sections: [","        \/\/ Dynamic archive populated from a shortcode","        .dynamicArchive(\"Latest\", shortcode: \"SHORTCODE\"),","","        \/\/ Manual section with a per-section configuration","        .section(.init(","            name: \"Premium\",","            type: .replicaArchive(","                guid: \"PUB_GUID\",","                supplements: [\"SUPPLEMENT_PUB_GUID\"],","                config: premiumConfig","            )","        )),","","        \/\/ Subsection group for user content","        .subsections(\"My Content\", [","            .init(name: \"Bookmarks\", type: .bookmarks(type: .all)),","            .init(name: \"Downloads\", type: .downloads(type: .all))","        ])","    ]",")"],"type":"codeListing"},{"text":"SwiftUI Integration","anchor":"SwiftUI-Integration","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Wrap ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","isActive":true,"type":"reference"},{"text":" in a ","type":"text"},{"code":"UIViewControllerRepresentable","type":"codeVoice"},{"text":" for use","type":"text"},{"text":" ","type":"text"},{"text":"in SwiftUI:","type":"text"}]},{"syntax":"swift","code":["import SwiftUI","import PSReaderUI","","struct ReaderView: UIViewControllerRepresentable {","    func makeUIViewController(context: Context) -> PSReaderUI.CarouselViewController {","        let globalConfig = PSReaderUI.GlobalConfiguration(","            apiKey: \"API_KEY\",","            accountGUID: \"ACCOUNT_GUID\"","        )","        return PSReaderUI.CarouselViewController(","            globalConfig: globalConfig,","            sections: [","                .dynamicArchive(\"Editions\", shortcode: \"SHORTCODE\")","            ]","        )","    }","","    func updateUIViewController(_ uiViewController: PSReaderUI.CarouselViewController, context: Context) {}","}"],"type":"codeListing"}],"kind":"content"}],"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"PSReaderUI"}],"roleHeading":"Article","title":"Carousel Setup","role":"article"},"abstract":[{"text":"Configure the carousel’s sections, content sources, and layout.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/carousel-setup"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/carousel-setup"]}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","abstract":[{"type":"text","text":"The primary view controller provided by the SDK for presenting digital publication"},{"type":"text","text":" "},{"type":"text","text":"content through an intuitive carousel interface."}],"url":"\/documentation\/psreaderui\/carouselviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CarouselViewController","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"CarouselViewController","kind":"identifier"}],"title":"CarouselViewController","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","url":"\/documentation\/psreaderui","role":"collection","type":"topic","abstract":[{"text":"A UI framework for building digital newspaper and magazine reader experiences on iOS.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Standalone-View-Controllers":{"type":"topic","url":"\/documentation\/psreaderui\/standalone-view-controllers","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","title":"Standalone View Controllers","abstract":[{"type":"text","text":"Use archive, bookmarks, downloads, and search views outside of the carousel."}],"kind":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchConfiguration"}],"url":"\/documentation\/psreaderui\/searchconfiguration","abstract":[{"type":"text","text":"Configuration for the SDK’s built-in search interface."}],"role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration","navigatorTitle":[{"kind":"identifier","text":"SearchConfiguration"}],"kind":"symbol","title":"SearchConfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Theming-and-Customization":{"type":"topic","url":"\/documentation\/psreaderui\/theming-and-customization","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","abstract":[{"type":"text","text":"Adjust fonts, colors, icons, and layouts to match your app’s brand."}],"title":"Theming and Customization","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController/refreshDynamicArchives(completion:)":{"url":"\/documentation\/psreaderui\/carouselviewcontroller\/refreshdynamicarchives(completion:)","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController\/refreshDynamicArchives(completion:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshDynamicArchives"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Refreshes the publication lists in dynamic archives. Updates subsections if needed."}],"title":"refreshDynamicArchives(completion:)","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Search":{"abstract":[{"type":"text","text":"Search across feed edition content for articles and pages."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search","kind":"article","title":"Search","url":"\/documentation\/psreaderui\/search","role":"article","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Replica-and-Feed-Editions":{"title":"Replica and Feed Editions","url":"\/documentation\/psreaderui\/replica-and-feed-editions","kind":"article","abstract":[{"text":"Understand the two backend systems that power PSReaderUI content.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController/ContentType":{"url":"\/documentation\/psreaderui\/carouselviewcontroller\/contenttype","abstract":[{"text":"Describes the content type of a section or subsection page.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentType"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController\/ContentType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContentType"}],"title":"CarouselViewController.ContentType"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController/SectionItem":{"abstract":[{"text":"Defines the top level of paging sections in the carousel.","type":"text"}],"type":"topic","kind":"symbol","title":"CarouselViewController.SectionItem","role":"symbol","navigatorTitle":[{"text":"SectionItem","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SectionItem","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController\/SectionItem","url":"\/documentation\/psreaderui\/carouselviewcontroller\/sectionitem"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Localization":{"url":"\/documentation\/psreaderui\/localization","type":"topic","title":"Localization","abstract":[{"type":"text","text":"Localize all user-facing strings in the PSReaderUI SDK."}],"kind":"article","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"],"title":"Customization","anchor":"Customization"}],"path":"\/seeAlsoSections","op":"replace"}]}]}