{"metadata":{"modules":[{"name":"PSReaderUI"}],"roleHeading":"Article","role":"article","title":"Change Log"},"kind":"article","primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Versioning Scheme","anchor":"Versioning-Scheme","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"Starting in 2026, the SDK uses a calendar-based versioning scheme to"},{"type":"text","text":" "},{"type":"text","text":"align with the rest of the PageSuite product line. Versions follow the format"},{"type":"text","text":" "},{"inlineContent":[{"type":"text","text":"year.month.patch"}],"type":"strong"},{"type":"text","text":" — for example, "},{"type":"codeVoice","code":"26.1.0"},{"type":"text","text":" is the first January 2026"},{"type":"text","text":" "},{"type":"text","text":"release. This scheme does "},{"inlineContent":[{"text":"not","type":"text"}],"type":"strong"},{"type":"text","text":" follow semantic versioning. While we strive"},{"type":"text","text":" "},{"type":"text","text":"to maintain API stability, breaking changes may occur in any release without a"},{"type":"text","text":" "},{"type":"text","text":"major version bump. We recommend pinning to a specific version and reviewing"},{"type":"text","text":" "},{"type":"text","text":"this change log before upgrading."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"},{"level":2,"text":"v26.4.1","anchor":"v2641","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Added optional ","type":"text"},{"type":"codeVoice","code":"publicationName"},{"text":" parameter to","type":"text"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController\/ContentType\/feedArchive(guid:publicationName:config:)","isActive":true},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Adjusted dynamic archive publication naming logic for improved publication","type":"text"},{"text":" ","type":"text"},{"text":"names in downloads and other UI contexts. ","type":"text"},{"inlineContent":[{"text":"Behavior change:","type":"text"}],"type":"strong"},{"text":" Publication","type":"text"},{"text":" ","type":"text"},{"text":"names may differ from previous versions. Contact support if a name needs","type":"text"},{"text":" ","type":"text"},{"text":"adjusting.","type":"text"}],"type":"paragraph"}]}]},{"level":2,"text":"v26.4.0","anchor":"v2640","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingCacheStrategy","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/clearCache()","isActive":true},{"type":"text","text":" to"},{"type":"text","text":" "},{"type":"text","text":"control comment count freshness. See: "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting#Cache-Strategy","isActive":true},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"text":"Added ","type":"text"},{"type":"codeVoice","code":"pillIdealWidth"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pillHorizontalMargin"},{"text":" parameters to","type":"text"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingButton","isActive":true},{"text":". Reduces layout shift when comment counts update.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Added ","type":"text"},{"code":"preferredWidth","type":"codeVoice"},{"text":" parameter to ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentTooltipViewController","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"See: ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting#Tooltips","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration\/latestPaperThumbnailContentMode","isActive":true,"type":"reference"},{"text":". Fixes","type":"text"},{"text":" ","type":"text"},{"text":"broadsheet thumbnails overflowing the archive container when using","type":"text"},{"text":" ","type":"text"},{"code":"flexibleHeight","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Updated default comment button text from “Join the conversation” to"},{"type":"text","text":" "},{"type":"text","text":"“View comments”."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed search cell loading skeletons. Replaced static background color","type":"text"},{"text":" ","type":"text"},{"text":"placeholders.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Fixed page thumbnail not shrinking in search cells.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed inconsistent date format handling in search results.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Improved search cell loading skeletons.","type":"text"}]}]}]},{"level":2,"text":"v26.3.0","anchor":"v2630","type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Added search functionality. See: ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added commenting support. See: "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","isActive":true},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added hide-on-swipe behavior for navigation bars in the feed edition reader."},{"type":"text","text":" "},{"type":"strong","inlineContent":[{"text":"Behavior change:","type":"text"}]},{"type":"text","text":" Navigation bars now hide on swipe by default. To disable,"},{"type":"text","text":" "},{"type":"text","text":"see "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderNavigationBarConfiguration\/hidesBarsOnSwipe","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added support for publication nameplates configurable via the PageSuite portal."}]}]},{"content":[{"inlineContent":[{"text":"Fixed incorrect overlay size for default TTS overlay in replica reader.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Adjusted back navigation flow for articles in PDF-based feed editions."},{"type":"text","text":" "},{"type":"text","text":"Articles now navigate back to their parent PDF page instead of dismissing"},{"type":"text","text":" "},{"type":"text","text":"the reader."}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"This release introduces new localized string keys for search and"},{"type":"text","text":" "},{"type":"text","text":"commenting."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"},{"level":2,"text":"v26.2.0","anchor":"v2620","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added new sort menu to my content views."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added new delete all option to my content views.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added support for in flow article ads.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Improved support for fixed banner ads.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Improved placeholder image support in bookmark views."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Fixed issue where "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","isActive":true,"type":"reference"},{"type":"text","text":" did not read sub-headlines."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Fixed ","type":"text"},{"code":"NSCoding","type":"codeVoice"},{"text":" not an object warnings.","type":"text"}],"type":"paragraph"}]}]},{"level":2,"text":"v26.1.0","type":"heading","anchor":"v2610"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Introduced modern replacement for the legacy replica reader."},{"type":"text","text":" "},{"type":"text","text":"See: "},{"type":"codeVoice","code":"v26.1.0 Migration Guide"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added support for custom "},{"type":"codeVoice","code":"baseURL"},{"type":"text","text":"s in article webviews. Resolves issues"},{"type":"text","text":" "},{"type":"text","text":"with embeds and relative link failures."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Updated content browser UI for PDF pages and added page numbers."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added alternative UI for editions without section information. Replaces"},{"type":"text","text":" "},{"type":"text","text":"section ribbons with forward \/ back buttons."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Improved animation when navigating to an article from PDF pages."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Changed default "},{"type":"codeVoice","code":"archiveLimit"},{"type":"text","text":" (replica: 30, feed edition: unbounded)."},{"type":"text","text":" "},{"type":"text","text":"See: "},{"type":"codeVoice","code":"v26.1.0 Migration Guide"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Deleting all data now returns the user to the archive screen.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed incorrect share link generated when sharing bookmarked articles."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed issue with ","type":"text"},{"type":"codeVoice","code":"DefaultTextToSpeechProvider"},{"text":" not stripping HTML from","type":"text"},{"text":" ","type":"text"},{"text":"headlines.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed overflowing text in alerts with custom localized text.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed download button animation not correctly indicating queued state."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed grid layout issues on My Content screens on tablet. Resolves","type":"text"},{"text":" ","type":"text"},{"text":"excessively large space between columns.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Fixed potential crash when clearing edition data.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"heading","level":2,"text":"v5.5.0","anchor":"v550"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Introduced Liquid Glass UI for iOS 26+. See: ","type":"text"},{"code":"v5.5.0 Migration Guide","type":"codeVoice"},{"text":" for opt out.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Display cached content on archive screens when offline instead of immediately"},{"type":"text","text":" "},{"type":"text","text":"showing the offline screen."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added ","type":"text"},{"code":"ImageContentMode.flexibleHeight","type":"codeVoice"},{"text":" for archive screens.","type":"text"},{"text":" ","type":"text"},{"text":"See: ","type":"text"},{"code":"ImageContentMode","type":"codeVoice"},{"text":", ","type":"text"},{"code":"v5.5.0 Migration Guide","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added "},{"type":"codeVoice","code":"locale"},{"type":"text","text":" parameter to "},{"type":"codeVoice","code":"DefaultEditionDateFormatter"},{"type":"text","text":" initializer and"},{"type":"text","text":" "},{"type":"text","text":"defaulted it to "},{"type":"codeVoice","code":".current"},{"type":"text","text":" to respect the user’s locale, aligning behavior"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"codeVoice","code":"DateFormatter"},{"type":"text","text":". Previously the initializer used "},{"type":"codeVoice","code":"en_US_POSIX"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Automatically call global ","type":"text"},{"code":"PSReader.Initialize","type":"codeVoice"},{"text":" function when needed to","type":"text"},{"text":" ","type":"text"},{"text":"avoid failures if the host app forgets to initialize the SDK.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Downgraded recommended PDFNet version to ","type":"text"},{"code":"11.5.85515","type":"codeVoice"},{"text":" to avoid rendering regressions.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Replica Reader: Center align PDFs in fit-to-height modes when the PDF is"},{"type":"text","text":" "},{"type":"text","text":"smaller than the view."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Replica Reader: Fixed possible rendering glitch that could occur when opening","type":"text"},{"text":" ","type":"text"},{"text":"an edition on the non-first page.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Replica Reader: Fixed dark mode background for double page spreads.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Replica Reader: Added analytics events for the next\/previous buttons in both","type":"text"},{"text":" ","type":"text"},{"text":"the page browser and the article browser.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Replica Reader: Fixed possible double reporting of popover article page views.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Replica Reader: Added a configuration option to control status bar visibility."},{"type":"text","text":" "},{"type":"text","text":"See: "},{"type":"codeVoice","code":"LegacyReaderConfiguration.prefersStatusBarHidden"},{"type":"text","text":"."}]}]}]},{"type":"heading","level":2,"text":"v5.4.0","anchor":"v540"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Added kiosk layout support for feed archives.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added replica supplements support."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added placeholder image support for page browser. See: "},{"type":"codeVoice","code":"AssetDelegate"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Removed forced uppercase formatting in page browser sections."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed possible crash on bad HTML inputs."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Fixed crash when deleting a replica article bookmark if multiple bookmarks"},{"type":"text","text":" "},{"type":"text","text":"originated from the same PDF page."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed possible incorrect theme on download preference prompt."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed possible missing thumbnail on bookmarks.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Updated archive view default UI; tweaked colors and added border thumbnails.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Enhanced settings menu with new UI and options: WiFi-Only download, print,","type":"text"},{"text":" ","type":"text"},{"text":"auto delete downloads, clear edition data, and show page browser on first load.","type":"text"}]}]}]},{"type":"heading","level":2,"text":"v5.3.0","anchor":"v530"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Added text-to-speech support. See: "},{"type":"codeVoice","code":"AudioDelegate"},{"type":"text","text":", "},{"type":"codeVoice","code":"DefaultTextToSpeechProvider"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Consolidated print into share actions. The dedicated PDF print icon has been removed.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Added ability to print articles and section fronts.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Updated settings UI.","type":"text"}]}]}]},{"type":"heading","level":2,"text":"v5.2.0","anchor":"v520"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Improved handling of iPad multi tasking \/ split screen.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Fixed issue where pages \/ articles would occasionally fail to load when"},{"type":"text","text":" "},{"type":"text","text":"streaming an edition."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Added error handling for bad PDF inputs. Fixes potential crash from uncaught"},{"type":"text","text":" "},{"type":"codeVoice","code":"PDFNetException"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Added edition sort toggle to downloads screen."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Support for custom edition names.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Added standalone archive view for use outside of a carousel container."},{"type":"text","text":" "},{"type":"text","text":"See: "},{"type":"codeVoice","code":"ArchiveViewController"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"PDF pages and articles now segmented in PDF driven editions.","type":"text"},{"text":" ","type":"text"},{"text":"See: ","type":"text"},{"code":"v5.2.0 Migration Guide","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Navigation bar: Removed right-side back arrow. Left icon now adapts to"},{"type":"text","text":" "},{"type":"text","text":"context, dismisses either the article or the reader."},{"type":"text","text":" "},{"type":"text","text":"See: "},{"type":"codeVoice","code":"ImageResourceName"},{"type":"text","text":", "},{"type":"codeVoice","code":"AssetDelegate"},{"type":"text","text":", "},{"type":"codeVoice","code":"v5.2.0 Migration Guide"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Replica Reader: Changed reader background to black in dark mode."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Replica Reader: Fixed issue where print navigation bar item could not be enabled.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Replica Reader: Changed default "},{"type":"codeVoice","code":"readerBack"},{"type":"text","text":" and "},{"type":"codeVoice","code":"articlePopOverBack"},{"type":"text","text":" assets."}],"type":"paragraph"}]}]},{"anchor":"v511","type":"heading","level":2,"text":"v5.1.1"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Fixed issue where SDK did not respond window open calls from templates."}],"type":"paragraph"}]}]},{"anchor":"v510","type":"heading","level":2,"text":"v5.1.0"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Dropped ZipFoundation depdendency.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Replaced unowned references with weak references for better stability.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added Swift package."}]}]}]},{"anchor":"v500","type":"heading","level":2,"text":"v5.0.0"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Option to read editions without downloading."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Improved archive cache handling and offline use."}]}]},{"content":[{"inlineContent":[{"text":"Paywall support. See: ","type":"text"},{"type":"codeVoice","code":"PaywallDelegate"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"More fine grained date formatting. See: ","type":"text"},{"code":"EditionDateFormatter","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Reworked API for customizing assets. See: ","type":"text"},{"type":"codeVoice","code":"AssetDelegate"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Added date picker support for replica archives.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Removed bitcode from bundled "},{"code":"ZipFoundation.xcframework","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Fixed typo in "},{"type":"codeVoice","code":"DownloadsConfiguration"},{"type":"text","text":" type name."}],"type":"paragraph"}]}]},{"anchor":"v432","type":"heading","level":2,"text":"v4.3.2"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fix issue with replica reader contents ribbon."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Fix issue where image galleries \/ share sheet would not open after dismissing"},{"type":"text","text":" "},{"type":"text","text":"feed edition settings menu."}],"type":"paragraph"}]}]},{"anchor":"v431","type":"heading","level":2,"text":"v4.3.1"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added supported screen orientations API."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added support for author names in article templates."}]}]}]},{"anchor":"v430","type":"heading","level":2,"text":"v4.3.0"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Fix padding issue at the bottom of carousel view."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fix contents ribbon not tracking currently open page.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Fix issue where reader can sometimes scroll past end of edition."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Fix rendering issues on rotation on some templates."}],"type":"paragraph"}]}]},{"anchor":"v421","type":"heading","level":2,"text":"v4.2.1"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed crash when swiping in legacy replica reader while offline.","type":"text"}]}]}]},{"anchor":"v420","type":"heading","level":2,"text":"v4.2.0"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Added support for replica publication kiosks."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Feed edition reader settings menu dark mode issues.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Feed edition reader rotation fixes.","type":"text"}],"type":"paragraph"}]}]},{"anchor":"v410","type":"heading","level":2,"text":"v4.1.0"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Added reader settings menu."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added support for double page mode."}]}]},{"content":[{"inlineContent":[{"text":"Added fit-to-width \/ fit-to-height options.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Remember last read page."}],"type":"paragraph"}]}]},{"anchor":"v400","type":"heading","level":2,"text":"v4.0.0"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Fixed issue with annotated links on adverts."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Fixed issue where archive screen would disable pull-to-refresh."}],"type":"paragraph"}]}]},{"anchor":"v400-preview5","type":"heading","level":2,"text":"v4.0.0-preview5"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Fixed "},{"code":"editionDateString","type":"codeVoice"},{"type":"text","text":" timezone and format inconsistencies."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added edition launch analytics event when luanching from downloads.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added support for legal Kill scenarios."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed overrideUserInterfaceStyle regression.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed issue when swiping in carousel,"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Support for bespoke ads."}]}]}]},{"anchor":"v400-preview4","type":"heading","level":2,"text":"v4.0.0-preview4"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Added support for page links.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed occasional layout issues on rotate."}]}]}]},{"anchor":"v400-preview3","type":"heading","level":2,"text":"v4.0.0-preview3"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Added timezone support.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added support for dynamic archives."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Added improved OOB sharing support.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"SDK globally respects "},{"type":"codeVoice","code":"overrideUserInterfaceStyle"},{"type":"text","text":"."}],"type":"paragraph"}]}]},{"anchor":"v400-preview2","type":"heading","level":2,"text":"v4.0.0-preview2"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completed dark mode."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Added further UI configuration options."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Fixed back navigation logic to match web."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Aligned PDF page names in content browser with web."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Increased section ribbon items hit boxes.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Fixed crash on empty edition.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Fixed article tap + zoom gestures interfering on PDF pages.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Removed vertical padding around PDFs."}],"type":"paragraph"}]}]},{"anchor":"v400-preview1","type":"heading","level":2,"text":"v4.0.0-preview1"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Renamed "},{"type":"codeVoice","code":"feedEditionPageView"},{"type":"text","text":" to "},{"type":"codeVoice","code":"feedEditionOtherPageView"},{"type":"text","text":" and ensured it"},{"type":"text","text":" "},{"type":"text","text":"does not fire when either a "},{"type":"codeVoice","code":"feedEditionArticleView"},{"type":"text","text":" or"},{"type":"text","text":" "},{"type":"codeVoice","code":"feedEditionSectionView"},{"type":"text","text":" has already been fired for a give page view."}]}]},{"content":[{"inlineContent":[{"text":"Added ","type":"text"},{"code":"imageResourceForName","type":"codeVoice"},{"text":" property to ","type":"text"},{"code":"GlobalConfiguration","type":"codeVoice"},{"text":" object as a new","type":"text"},{"text":" ","type":"text"},{"text":"customization point for replacing icons in the SDK.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fixed inconsistent layouts when using "},{"code":"fitToHeight","type":"codeVoice"},{"type":"text","text":" thumbnails."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Aligned UI elements with rendered "},{"type":"codeVoice","code":"fitToHeight"},{"type":"text","text":" thumbnail edges."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Fixed crash when jumping to an article."}],"type":"paragraph"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/change-log"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/change-log"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"abstract":[{"text":"Track new features, improvements, bug fixes, and other updates in each","type":"text"},{"text":" ","type":"text"},{"text":"PSReaderUI SDK release.","type":"text"}],"seeAlsoSections":[{"generated":true,"anchor":"Release-Notes","title":"Release Notes","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Migration-Guides"]}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingDelegate/clearCache()":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/clearCache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"text":"Removes all cached comment counts.","type":"text"}],"role":"symbol","title":"clearCache()","required":true,"url":"\/documentation\/psreaderui\/commentingdelegate\/clearcache()","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingCacheStrategy":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommentingCacheStrategy"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommentingCacheStrategy"}],"abstract":[{"text":"Controls how ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"resolves comment counts against the local cache.","type":"text"}],"title":"CommentingCacheStrategy","type":"topic","url":"\/documentation\/psreaderui\/commentingcachestrategy","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingCacheStrategy","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Migration-Guides":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Migration-Guides","kind":"article","abstract":[{"type":"text","text":"Guidance to help you smoothly transition your app to newer versions of the SDK."},{"type":"text","text":" "},{"type":"text","text":"This page highlights breaking changes, necessary updates, and recommended"},{"type":"text","text":" "},{"type":"text","text":"practices when migrating between versions."}],"type":"topic","url":"\/documentation\/psreaderui\/migration-guides","role":"article","title":"Migration Guides"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Commenting#Tooltips":{"kind":"section","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting#Tooltips","abstract":[],"type":"topic","title":"Tooltips","url":"\/documentation\/psreaderui\/commenting#Tooltips"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","url":"\/documentation\/psreaderui","role":"collection","type":"topic","abstract":[{"text":"A UI framework for building digital newspaper and magazine reader experiences on iOS.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController/ContentType/feedArchive(guid:publicationName:config:)":{"abstract":[{"text":"An archive screen for feed editions (that is mixed PDF and HTML responsive editions).","type":"text"}],"title":"CarouselViewController.ContentType.feedArchive(guid:publicationName:config:)","type":"topic","role":"symbol","url":"\/documentation\/psreaderui\/carouselviewcontroller\/contenttype\/feedarchive(guid:publicationname:config:)","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"feedArchive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"guid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publicationName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10PSReaderUI20ArchiveConfigurationV","text":"ArchiveConfiguration"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController\/ContentType\/feedArchive(guid:publicationName:config:)"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentTooltipViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultCommentTooltipViewController"}],"role":"symbol","kind":"symbol","url":"\/documentation\/psreaderui\/defaultcommenttooltipviewcontroller","abstract":[{"type":"text","text":"A popover tooltip view controller with a text label and close button."}],"title":"DefaultCommentTooltipViewController","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentTooltipViewController","navigatorTitle":[{"kind":"identifier","text":"DefaultCommentTooltipViewController"}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingButton":{"role":"symbol","abstract":[{"text":"A pill-shaped comment button with a border and centered text label.","type":"text"}],"navigatorTitle":[{"text":"DefaultCommentingButton","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingButton","title":"DefaultCommentingButton","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultCommentingButton","kind":"identifier"}],"url":"\/documentation\/psreaderui\/defaultcommentingbutton"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultTextToSpeechProvider":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultTextToSpeechProvider","kind":"identifier"}],"url":"\/documentation\/psreaderui\/defaulttexttospeechprovider","role":"symbol","title":"DefaultTextToSpeechProvider","abstract":[{"text":"A complete text-to-speech implementation providing ready-to-use audio functionality.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","kind":"symbol","navigatorTitle":[{"text":"DefaultTextToSpeechProvider","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingDelegate/fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)":{"role":"symbol","required":true,"type":"topic","title":"fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)","kind":"symbol","abstract":[{"text":"Fetches the comment count for a single article using the given cache strategy.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchCommentCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forArticle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PSEArticle","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEArticle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inEdition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PSEEditionSource","preciseIdentifier":"s:8PSReader16PSEEditionSourceP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheStrategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommentingCacheStrategy","preciseIdentifier":"s:10PSReaderUI23CommentingCacheStrategyO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)","url":"\/documentation\/psreaderui\/commentingdelegate\/fetchcommentcount(forarticle:inedition:cachestrategy:completion:)"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveConfiguration/latestPaperThumbnailContentMode":{"title":"latestPaperThumbnailContentMode","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration\/latestPaperThumbnailContentMode","abstract":[{"type":"text","text":"Optional content mode override for the latest edition hero cell."}],"url":"\/documentation\/psreaderui\/archiveconfiguration\/latestpaperthumbnailcontentmode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latestPaperThumbnailContentMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10PSReaderUI16ImageContentModeO","text":"ImageContentMode","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderNavigationBarConfiguration/hidesBarsOnSwipe":{"url":"\/documentation\/psreaderui\/readernavigationbarconfiguration\/hidesbarsonswipe","kind":"symbol","type":"topic","role":"symbol","title":"hidesBarsOnSwipe","abstract":[{"type":"text","text":"Hides the navigation bar and other views (such as comment buttons) when the user"},{"type":"text","text":" "},{"type":"text","text":"scrolls down through content, and shows them again when scrolling back up."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderNavigationBarConfiguration\/hidesBarsOnSwipe","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidesBarsOnSwipe","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Commenting#Cache-Strategy":{"url":"\/documentation\/psreaderui\/commenting#Cache-Strategy","abstract":[],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting#Cache-Strategy","title":"Cache Strategy","kind":"section"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Commenting":{"type":"topic","kind":"article","abstract":[{"text":"Add comment counts, comment buttons, and commenting integration to the reader.","type":"text"}],"role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","title":"Commenting","url":"\/documentation\/psreaderui\/commenting"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Search":{"abstract":[{"type":"text","text":"Search across feed edition content for articles and pages."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search","kind":"article","title":"Search","url":"\/documentation\/psreaderui\/search","role":"article","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"title":"Release Notes","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Migration-Guides"],"generated":true,"anchor":"Release-Notes"}],"op":"replace","path":"\/seeAlsoSections"}]}]}