{"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"inlineContent":[{"text":"The PSReaderUI SDK provides a pluggable commenting architecture built around two","type":"text"},{"text":" ","type":"text"},{"text":"protocols:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService"}],"type":"strong"},{"text":" — a backend-agnostic data layer that fetches comment","type":"text"},{"text":" ","type":"text"},{"text":"counts and determines which articles support commenting.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate"}],"type":"strong"},{"text":" — extends ","type":"text"},{"code":"CommentingService","type":"codeVoice"},{"text":" with UI","type":"text"},{"text":" ","type":"text"},{"text":"responsibilities: providing a comment button, handling taps, and presenting","type":"text"},{"text":" ","type":"text"},{"text":"onboarding tooltips.","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"text":"The SDK ships ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider","isActive":true,"type":"reference"},{"text":", an open class that wraps any","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService","isActive":true,"type":"reference"},{"text":" and provides default UI components out of the box —","type":"text"},{"text":" ","type":"text"},{"text":"a pill-shaped comment button, comment-count caching, trending indicators in the","type":"text"},{"text":" ","type":"text"},{"text":"content browser, and one-time onboarding tooltips.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The commenting backend is pluggable. The SDK currently bundles"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CoralCommentingService"},{"type":"text","text":" for "},{"type":"reference","isActive":true,"identifier":"https:\/\/coralproject.net\/"},{"type":"text","text":" "},{"type":"text","text":"integration. You can connect any commenting backend by implementing"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService"},{"type":"text","text":"."}],"type":"paragraph"},{"level":2,"anchor":"Quick-Start","type":"heading","text":"Quick Start"},{"inlineContent":[{"type":"text","text":"Create a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService"},{"type":"text","text":" for your commenting backend, wrap it in a"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider"},{"type":"text","text":", and assign it to your "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The example below uses "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CoralCommentingService"},{"type":"text","text":", but all"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService","isActive":true},{"type":"text","text":" implementations work the same way:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["\/\/ 1. Create a commenting service for your backend","let service = CoralCommentingService(domain: \"talk.yourpublication.com\")","","\/\/ 2. Wrap it in a provider that handles UI, caching, and tooltips","let provider = DefaultCommentingProvider(","    globalConfig: globalConfig,","    service: service,","    onCommentButtonTapped: { article, page, source, viewController in","        \/\/ Present your commenting UI — see \"The Callback\" below","    }",")","","\/\/ 3. Assign to your global configuration","globalConfig.commentingDelegate = provider"]},{"inlineContent":[{"type":"text","text":"That’s it. The SDK will show a comment button at the bottom of eligible articles,"},{"type":"text","text":" "},{"type":"text","text":"display comment counts in the content browser, and prefetch counts at edition"},{"type":"text","text":" "},{"type":"text","text":"load time."}],"type":"paragraph"},{"level":2,"anchor":"The-Callback","type":"heading","text":"The Callback"},{"inlineContent":[{"text":"When a user taps the comment button — either the native button in the article","type":"text"},{"text":" ","type":"text"},{"text":"footer or a template-based button in the article byline — the SDK invokes the","type":"text"},{"text":" ","type":"text"},{"code":"onCommentButtonTapped","type":"codeVoice"},{"text":" closure with four parameters:","type":"text"}],"type":"paragraph"},{"header":"row","type":"table","rows":[[[{"inlineContent":[{"text":"Parameter","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Type","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Description"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"article","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"codeVoice","code":"PSEArticle"}],"type":"paragraph"}],[{"inlineContent":[{"text":"The article the user wants to comment on.","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"page","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"codeVoice","code":"PSEPage"}],"type":"paragraph"}],[{"inlineContent":[{"text":"The page containing the article.","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"source","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"code":"PSEEditionSource","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"The edition the article belongs to."}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":"viewController"}],"type":"paragraph"}],[{"inlineContent":[{"code":"UIViewController","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"text":"The presenting view controller — use it to present your commenting UI.","type":"text"}],"type":"paragraph"}]]]},{"inlineContent":[{"type":"text","text":"This is where you present your commenting interface. For Coral Talk, the article"},{"type":"text","text":" "},{"type":"text","text":"carries metadata that you can use to identify the comment stream:"}],"type":"paragraph"},{"type":"codeListing","code":["onCommentButtonTapped: { article, page, source, viewController in","    \/\/ Access Coral-specific metadata","    guard let coral = article.metadata?.coralCommenting else { return }","","    \/\/ coral.assetId     — the Coral asset ID for this article","    \/\/ coral.publicUrl   — the public URL associated with the comment stream","    \/\/ coral.enabled     — whether commenting is enabled","","    let commentVC = MyCoralViewController(assetId: coral.assetId)","    viewController.present(commentVC, animated: true)","}"],"syntax":"swift"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Store the "},{"type":"codeVoice","code":"page.pageguid"},{"type":"text","text":" and edition GUID alongside your comment data"},{"type":"text","text":" "},{"type":"text","text":"if you need to deep link back to the article later (e.g., from a comment"},{"type":"text","text":" "},{"type":"text","text":"history screen). See the next section."}]}],"style":"tip","name":"Tip"},{"type":"heading","anchor":"Deep-Linking-Back-to-Articles","level":2,"text":"Deep Linking Back to Articles"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A client may need to navigate back to a specific article from outside the"},{"type":"text","text":" "},{"type":"text","text":"reader — for example, from a comment history view or a push notification about"},{"type":"text","text":" "},{"type":"text","text":"a reply. Use "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","isActive":true},{"type":"text","text":" with the shortcode initializer and"},{"type":"text","text":" "},{"type":"text","text":"pass the page GUID as the opening page:"}]},{"type":"codeListing","code":["let reader = FeedReaderViewController(","    globalConfig: globalConfig,","    shortcode: \"SHORTCODE\",","    editionGUID: savedEditionGUID,","    openingPage: .page(guid: savedPageGUID)",")","","present(reader, animated: true)"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"To make this work, persist the page GUID (","type":"text"},{"type":"codeVoice","code":"page.pageguid"},{"text":"), edition GUID, and","type":"text"},{"text":" ","type":"text"},{"text":"shortcode when the user opens a comment stream. These three values are","type":"text"},{"text":" ","type":"text"},{"text":"sufficient to reconstruct the deep link later.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking"},{"type":"text","text":" for the full guide on opening editions and pages"},{"type":"text","text":" "},{"type":"text","text":"programmatically."}]},{"type":"heading","anchor":"Custom-Commenting-Service","level":2,"text":"Custom Commenting Service"},{"type":"paragraph","inlineContent":[{"text":"To connect a non-Coral backend, implement ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService","isActive":true,"type":"reference"},{"text":". The protocol","type":"text"},{"text":" ","type":"text"},{"text":"has three required methods and one optional batch method:","type":"text"}]},{"type":"codeListing","code":["class MyCommentingService: CommentingService {","","    func isCommentingEnabled(","        article: PSEArticle,","        inEdition source: PSEEditionSource","    ) -> Bool {","        \/\/ Return true for articles that support commenting","        return article.articleguid != nil","    }","","    func articleIdentifier(for article: PSEArticle) -> String? {","        \/\/ Return a stable ID used as the cache key and batch lookup key","        return article.articleguid","    }","","    func fetchCommentCount(","        forArticle article: PSEArticle,","        inEdition source: PSEEditionSource,","        completion: @escaping (Result<Int, Error>) -> Void","    ) {","        \/\/ Fetch the count from your backend","        MyAPI.fetchCount(for: article) { count in","            completion(.success(count))","        }","    }","","    \/\/ Optional — override for efficient batch fetching.","    \/\/ The default calls fetchCommentCount individually per article.","    func prefetchCommentCounts(","        forArticles articles: [PSEArticle],","        inEdition source: PSEEditionSource,","        completion: ((Result<[String: Int], Error>) -> Void)?","    ) {","        let ids = articles.compactMap { articleIdentifier(for: $0) }","        MyAPI.fetchCounts(for: ids) { results in","            completion?(.success(results))","        }","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Pass your service into "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider","type":"reference","isActive":true},{"type":"text","text":" to get all the default UI"},{"type":"text","text":" "},{"type":"text","text":"behavior — button, caching, tooltips, trending — without reimplementing any of"},{"type":"text","text":" "},{"type":"text","text":"it:"}]},{"type":"codeListing","code":["let provider = DefaultCommentingProvider(","    globalConfig: globalConfig,","    service: MyCommentingService(),","    onCommentButtonTapped: { article, page, source, viewController in","        \/\/ Present your commenting UI","    }",")","","globalConfig.commentingDelegate = provider"],"syntax":"swift"},{"type":"heading","anchor":"Customizing-the-Button","level":2,"text":"Customizing the Button"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider"},{"type":"text","text":" returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingButton"},{"type":"text","text":" — a"},{"type":"text","text":" "},{"type":"text","text":"pill-shaped button with a 1 px border and centered text label. To customize"},{"type":"text","text":" "},{"type":"text","text":"its appearance, subclass "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider"},{"type":"text","text":" and override"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/commentButton(forArticle:inEdition:onTap:)"},{"type":"text","text":":"}]},{"type":"codeListing","code":["class MyCommentingProvider: DefaultCommentingProvider {","    override func commentButton(","        forArticle article: PSEArticle,","        inEdition source: PSEEditionSource,","        onTap: @escaping () -> Void","    ) -> (any CommentingButtonView)? {","        let button = DefaultCommentingButton(","            text: \"Leave a comment\",","            foregroundColor: .systemBlue,","            font: .systemFont(ofSize: 16, weight: .semibold),","            pillTopPadding: 20,","            pillBottomPadding: 20,","            labelVerticalPadding: 14,","            labelHorizontalPadding: 40","        )","        button.onTap = onTap","        return button","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"For a completely custom button, implement ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingButtonView","isActive":true,"type":"reference"},{"text":" on your own","type":"text"},{"text":" ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass. Store the ","type":"text"},{"code":"onTap","type":"codeVoice"},{"text":" closure and call it when the user taps","type":"text"},{"text":" ","type":"text"},{"text":"the button. Implement ","type":"text"},{"code":"updateText(_:)","type":"codeVoice"},{"text":" so the SDK can update the label when","type":"text"},{"text":" ","type":"text"},{"text":"comment counts are fetched.","type":"text"}]},{"type":"heading","anchor":"Cache-Strategy","level":2,"text":"Cache Strategy"},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider","isActive":true,"type":"reference"},{"text":" maintains an in-memory comment-count cache.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingCacheStrategy","isActive":true,"type":"reference"},{"text":" enum controls how","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"resolves counts:","type":"text"}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Strategy","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"Behavior"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".preferCache"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Return the cached count immediately if available; fetch from the network only on a cache miss."}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".preferNetwork"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Always fetch from the network and update the cache. Falls back to a cached value if the network request fails."}],"type":"paragraph"}]]],"header":"row"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK uses "},{"code":".preferCache","type":"codeVoice"},{"type":"text","text":" in the content browser (where thumbnails benefit"},{"type":"text","text":" "},{"type":"text","text":"from instant counts) and "},{"code":".preferNetwork","type":"codeVoice"},{"type":"text","text":" in the article view (where fresh"},{"type":"text","text":" "},{"type":"text","text":"counts matter most). The cache is cleared and repopulated via"},{"type":"text","text":" "},{"code":"CommentingDelegate\/prefetchCommentCounts(forArticles:inEdition:completion:)","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"each time an edition loads."}]},{"type":"paragraph","inlineContent":[{"text":"If you implement ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate","type":"reference"},{"text":" directly, you are responsible for","type":"text"},{"text":" ","type":"text"},{"text":"handling cache strategy semantics in your","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)","type":"reference"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/clearCache()","type":"reference"},{"text":" implementations.","type":"text"}]},{"type":"heading","anchor":"Trending-Threshold","level":2,"text":"Trending Threshold"},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/trendingThreshold","isActive":true},{"type":"text","text":" controls when a trending icon"},{"type":"text","text":" "},{"type":"text","text":"appears next to the comment count in the content browser. When an article’s"},{"type":"text","text":" "},{"type":"text","text":"comment count meets or exceeds this value, the SDK displays a trending"},{"type":"text","text":" "},{"type":"text","text":"indicator alongside the count."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default threshold is "},{"type":"codeVoice","code":"100"},{"type":"text","text":". Pass a custom value to the initializer:"}]},{"type":"codeListing","code":["let provider = DefaultCommentingProvider(","    globalConfig: globalConfig,","    service: service,","    trendingThreshold: 50,","    onCommentButtonTapped: { article, page, source, viewController in","        \/\/ ...","    }",")"],"syntax":"swift"},{"type":"heading","anchor":"Tooltips","level":2,"text":"Tooltips"},{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider"},{"type":"text","text":" presents one-time onboarding tooltips to introduce"},{"type":"text","text":" "},{"type":"text","text":"the commenting feature:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Article tooltip"}],"type":"strong"},{"text":" — a popover anchored above the comment button in the","type":"text"},{"text":" ","type":"text"},{"text":"article view.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Content browser tooltip","type":"text"}],"type":"strong"},{"text":" — a popover anchored below the first visible","type":"text"},{"text":" ","type":"text"},{"text":"commenting-enabled cell in the content browser.","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each tooltip is shown once per app install. The provider tracks presentation"},{"type":"text","text":" "},{"type":"text","text":"state in "},{"type":"codeVoice","code":"UserDefaults"},{"type":"text","text":" and returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" on subsequent calls."}]},{"type":"paragraph","inlineContent":[{"text":"To customize tooltip text, use the ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager","isActive":true,"type":"reference"},{"text":" system (see below).","type":"text"},{"text":" ","type":"text"},{"text":"To customize tooltip appearance or behavior, subclass ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"and override ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/articleCommentTooltipViewController(inEdition:)","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"or ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/contentBrowserCommentTooltipViewController(inEdition:)","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"heading","anchor":"Localization","level":2,"text":"Localization"},{"type":"paragraph","inlineContent":[{"type":"text","text":"All commenting strings are resolved through the "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager","isActive":true},{"type":"text","text":" system."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Override these using a String Catalog or by subclassing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"},{"type":"text","text":" for the full localization guide."}]},{"type":"heading","anchor":"Custom-Icons","level":2,"text":"Custom Icons"},{"type":"paragraph","inlineContent":[{"text":"The content browser uses two images from the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate"},{"text":" system for","type":"text"},{"text":" ","type":"text"},{"text":"commenting indicators:","type":"text"}]},{"type":"table","rows":[[[{"inlineContent":[{"type":"text","text":"Resource Name"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Usage","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".comment","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Comment count icon in content browser cells"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".trending","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Trending indicator shown when the count exceeds the threshold"}],"type":"paragraph"}]]],"header":"row"},{"type":"paragraph","inlineContent":[{"text":"Override these through a custom ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate","isActive":true,"type":"reference"},{"text":" to match your app’s icon","type":"text"},{"text":" ","type":"text"},{"text":"style. See ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","isActive":true,"type":"reference"},{"text":" for details on asset customization.","type":"text"}]},{"type":"heading","anchor":"Custom-CommentingDelegate","level":2,"text":"Custom CommentingDelegate"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For full control over every aspect of the commenting experience, implement"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate"},{"type":"text","text":" directly. This is an advanced pattern — you take on"},{"type":"text","text":" "},{"type":"text","text":"responsibility for the data layer, button creation, tap handling, and tooltips:"}]},{"type":"codeListing","code":["class MyCommentingDelegate: CommentingDelegate {","","    var trendingThreshold: Int { 50 }","","    \/\/ MARK: - CommentingService","","    func isCommentingEnabled(","        article: PSEArticle,","        inEdition source: PSEEditionSource","    ) -> Bool {","        return article.articleguid != nil","    }","","    func articleIdentifier(for article: PSEArticle) -> String? {","        return article.articleguid","    }","","    func fetchCommentCount(","        forArticle article: PSEArticle,","        inEdition source: PSEEditionSource,","        completion: @escaping (Result<Int, Error>) -> Void","    ) {","        \/\/ Fetch from your backend","    }","","    func prefetchCommentCounts(","        forArticles articles: [PSEArticle],","        inEdition source: PSEEditionSource,","        completion: ((Result<[String: Int], Error>) -> Void)?","    ) {","        \/\/ Batch fetch from your backend","    }","","    \/\/ MARK: - CommentingDelegate","","    func fetchCommentCount(","        forArticle article: PSEArticle,","        inEdition source: PSEEditionSource,","        cacheStrategy: CommentingCacheStrategy,","        completion: @escaping (Result<Int, Error>) -> Void","    ) {","        \/\/ Handle .preferCache \/ .preferNetwork as needed for your backend","        fetchCommentCount(forArticle: article, inEdition: source, completion: completion)","    }","","    func clearCache() {","        \/\/ Clear any cached comment counts","    }","","    func commentButton(","        forArticle article: PSEArticle,","        inEdition source: PSEEditionSource,","        onTap: @escaping () -> Void","    ) -> (any CommentingButtonView)? {","        \/\/ Return your custom button, or nil to suppress","        let button = MyCustomButton()","        button.onTap = onTap","        return button","    }","","    func commentButtonTapped(","        forArticle article: PSEArticle,","        onPage page: PSEPage,","        inEdition source: PSEEditionSource,","        from viewController: UIViewController","    ) {","        \/\/ Present your commenting UI","    }","}","","globalConfig.commentingDelegate = MyCommentingDelegate()"],"syntax":"swift"},{"type":"aside","content":[{"inlineContent":[{"text":"In most cases, subclassing ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider","type":"reference"},{"text":" and overriding","type":"text"},{"text":" ","type":"text"},{"text":"a single method is simpler than implementing ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate","type":"reference"},{"text":" from","type":"text"},{"text":" ","type":"text"},{"text":"scratch. Only use the full protocol when you need to replace the caching,","type":"text"},{"text":" ","type":"text"},{"text":"tooltip, or button logic entirely.","type":"text"}],"type":"paragraph"}],"style":"tip","name":"Tip"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","metadata":{"modules":[{"name":"PSReaderUI"}],"roleHeading":"Article","title":"Commenting","role":"article"},"abstract":[{"text":"Add comment counts, comment buttons, and commenting integration to the reader.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"],"generated":true,"title":"Features","anchor":"Features"}],"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/psreaderui\/commenting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/psreaderui\/commenting"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Localization":{"url":"\/documentation\/psreaderui\/localization","type":"topic","title":"Localization","abstract":[{"type":"text","text":"Localize all user-facing strings in the PSReaderUI SDK."}],"kind":"article","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AssetDelegate":{"role":"symbol","kind":"symbol","title":"AssetDelegate","type":"topic","abstract":[{"text":"A delegate protocol for providing custom images and logos used within the SDK.","type":"text"}],"url":"\/documentation\/psreaderui\/assetdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AssetDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AssetDelegate"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LocalizationManager":{"navigatorTitle":[{"kind":"identifier","text":"LocalizationManager"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationManager"}],"title":"LocalizationManager","url":"\/documentation\/psreaderui\/localizationmanager","abstract":[{"text":"Provides localized strings.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingProvider/accentColor":{"role":"symbol","type":"topic","url":"\/documentation\/psreaderui\/defaultcommentingprovider\/accentcolor","abstract":[{"type":"text","text":"The accent color used for interactive commenting UI elements."}],"title":"accentColor","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/accentColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accentColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingButton":{"role":"symbol","abstract":[{"text":"A pill-shaped comment button with a border and centered text label.","type":"text"}],"navigatorTitle":[{"text":"DefaultCommentingButton","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingButton","title":"DefaultCommentingButton","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultCommentingButton","kind":"identifier"}],"url":"\/documentation\/psreaderui\/defaultcommentingbutton"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingService":{"role":"symbol","abstract":[{"text":"Data provider protocol for fetching comment counts from a backend.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommentingService","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/psreaderui\/commentingservice","navigatorTitle":[{"text":"CommentingService","kind":"identifier"}],"title":"CommentingService"},"https://coralproject.net/":{"identifier":"https:\/\/coralproject.net\/","titleInlineContent":[{"type":"text","text":"Coral Talk"}],"type":"link","title":"Coral Talk","url":"https:\/\/coralproject.net\/"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingProvider/contentBrowserCommentTooltipViewController(inEdition:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentBrowserCommentTooltipViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inEdition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PSEEditionSource","preciseIdentifier":"s:8PSReader16PSEEditionSourceP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","title":"contentBrowserCommentTooltipViewController(inEdition:)","abstract":[{"text":"Returns a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentTooltipViewController","isActive":true},{"text":" for the content browser.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/contentBrowserCommentTooltipViewController(inEdition:)","role":"symbol","url":"\/documentation\/psreaderui\/defaultcommentingprovider\/contentbrowsercommenttooltipviewcontroller(inedition:)"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"kind":"article","url":"\/documentation\/psreaderui\/paywall-integration","role":"article","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","title":"Paywall Integration","abstract":[{"type":"text","text":"Restrict access to premium content with custom paywall screens."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"type":"topic","title":"Analytics","kind":"article","role":"article","abstract":[{"type":"text","text":"Track user interactions and content engagement across the PSReaderUI SDK."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","url":"\/documentation\/psreaderui\/analytics"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingButtonView":{"kind":"symbol","navigatorTitle":[{"text":"CommentingButtonView","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommentingButtonView","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingButtonView","url":"\/documentation\/psreaderui\/commentingbuttonview","type":"topic","abstract":[{"text":"A custom view that acts as a comment button within the reader.","type":"text"}],"role":"symbol","title":"CommentingButtonView"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingProvider/fontFamily":{"url":"\/documentation\/psreaderui\/defaultcommentingprovider\/fontfamily","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/fontFamily","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fontFamily"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The font family used for commenting UI labels."}],"title":"fontFamily"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"title":"Media Playback","kind":"article","url":"\/documentation\/psreaderui\/media-playback","role":"article","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","abstract":[{"type":"text","text":"Enable video and media playback within the reader."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"role":"article","url":"\/documentation\/psreaderui\/sharing","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","kind":"article","type":"topic","title":"Sharing","abstract":[{"text":"Configure how users share edition content from the reader.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"type":"topic","title":"Text-to-Speech","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","abstract":[{"text":"Add audio playback of article content using the SDK’s text-to-speech system.","type":"text"}],"url":"\/documentation\/psreaderui\/text-to-speech","kind":"article","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingProvider/articleCommentTooltipViewController(inEdition:)":{"url":"\/documentation\/psreaderui\/defaultcommentingprovider\/articlecommenttooltipviewcontroller(inedition:)","title":"articleCommentTooltipViewController(inEdition:)","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/articleCommentTooltipViewController(inEdition:)","kind":"symbol","role":"symbol","abstract":[{"text":"Returns a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentTooltipViewController"},{"type":"text","text":" for the article view."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleCommentTooltipViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inEdition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PSEEditionSource","preciseIdentifier":"s:8PSReader16PSEEditionSourceP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingDelegate/fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)":{"role":"symbol","required":true,"type":"topic","title":"fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)","kind":"symbol","abstract":[{"text":"Fetches the comment count for a single article using the given cache strategy.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchCommentCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forArticle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PSEArticle","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEArticle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inEdition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PSEEditionSource","preciseIdentifier":"s:8PSReader16PSEEditionSourceP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheStrategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommentingCacheStrategy","preciseIdentifier":"s:10PSReaderUI23CommentingCacheStrategyO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)","url":"\/documentation\/psreaderui\/commentingdelegate\/fetchcommentcount(forarticle:inedition:cachestrategy:completion:)"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"type":"topic","title":"Advertisements","abstract":[{"type":"text","text":"Display custom advertisements within the reader."}],"url":"\/documentation\/psreaderui\/advertisements","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","kind":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","url":"\/documentation\/psreaderui","role":"collection","type":"topic","abstract":[{"text":"A UI framework for building digital newspaper and magazine reader experiences on iOS.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Deep-Linking":{"title":"Deep Linking","role":"article","kind":"article","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","abstract":[{"type":"text","text":"Open a specific feed edition directly, bypassing the archive screen."}],"url":"\/documentation\/psreaderui\/deep-linking"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Search":{"abstract":[{"type":"text","text":"Search across feed edition content for articles and pages."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search","kind":"article","title":"Search","url":"\/documentation\/psreaderui\/search","role":"article","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingCacheStrategy":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommentingCacheStrategy"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommentingCacheStrategy"}],"abstract":[{"text":"Controls how ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/fetchCommentCount(forArticle:inEdition:cacheStrategy:completion:)","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"resolves comment counts against the local cache.","type":"text"}],"title":"CommentingCacheStrategy","type":"topic","url":"\/documentation\/psreaderui\/commentingcachestrategy","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingCacheStrategy","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingProvider/commentButton(forArticle:inEdition:onTap:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"commentButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forArticle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PSEArticle","kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEArticle"},{"text":", ","kind":"text"},{"text":"inEdition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PSEEditionSource","kind":"typeIdentifier","preciseIdentifier":"s:8PSReader16PSEEditionSourceP"},{"text":", ","kind":"text"},{"text":"onTap","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommentingButtonView","kind":"typeIdentifier","preciseIdentifier":"s:10PSReaderUI20CommentingButtonViewP"},{"text":")?","kind":"text"}],"title":"commentButton(forArticle:inEdition:onTap:)","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/commentButton(forArticle:inEdition:onTap:)","role":"symbol","abstract":[{"text":"Returns a ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingButton","type":"reference","isActive":true},{"text":" styled with ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/accentColor","type":"reference","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/fontFamily","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/psreaderui\/defaultcommentingprovider\/commentbutton(forarticle:inedition:ontap:)"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"GlobalConfiguration"}],"url":"\/documentation\/psreaderui\/globalconfiguration","role":"symbol","title":"GlobalConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlobalConfiguration"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","kind":"symbol","abstract":[{"type":"text","text":"A configuration object that provides global settings and delegates for"},{"type":"text","text":" "},{"type":"text","text":"customizing the SDK’s behavior and appearance."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingDelegate/clearCache()":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate\/clearCache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"text":"Removes all cached comment counts.","type":"text"}],"role":"symbol","title":"clearCache()","required":true,"url":"\/documentation\/psreaderui\/commentingdelegate\/clearcache()","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingProvider":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DefaultCommentingProvider","kind":"identifier"}],"url":"\/documentation\/psreaderui\/defaultcommentingprovider","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultCommentingProvider","kind":"identifier"}],"abstract":[{"text":"A ready-made ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate","type":"reference","isActive":true},{"text":" that wraps any ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService","type":"reference","isActive":true},{"text":".","type":"text"}],"title":"DefaultCommentingProvider"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentTooltipViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultCommentTooltipViewController"}],"role":"symbol","kind":"symbol","url":"\/documentation\/psreaderui\/defaultcommenttooltipviewcontroller","abstract":[{"type":"text","text":"A popover tooltip view controller with a text label and close button."}],"title":"DefaultCommentTooltipViewController","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentTooltipViewController","navigatorTitle":[{"kind":"identifier","text":"DefaultCommentTooltipViewController"}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Theming-and-Customization":{"type":"topic","url":"\/documentation\/psreaderui\/theming-and-customization","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","abstract":[{"type":"text","text":"Adjust fonts, colors, icons, and layouts to match your app’s brand."}],"title":"Theming and Customization","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultCommentingProvider/trendingThreshold":{"title":"trendingThreshold","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trendingThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The comment count at which the trending icon appears in the content browser."}],"type":"topic","url":"\/documentation\/psreaderui\/defaultcommentingprovider\/trendingthreshold","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultCommentingProvider\/trendingThreshold"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CommentingDelegate":{"url":"\/documentation\/psreaderui\/commentingdelegate","role":"symbol","title":"CommentingDelegate","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommentingDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommentingDelegate"}],"abstract":[{"text":"Extends ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService","isActive":true,"type":"reference"},{"text":" with UI responsibilities for the commenting system.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CoralCommentingService":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoralCommentingService","kind":"identifier"}],"navigatorTitle":[{"text":"CoralCommentingService","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CoralCommentingService","title":"CoralCommentingService","url":"\/documentation\/psreaderui\/coralcommentingservice","role":"symbol","abstract":[{"text":"A ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CommentingService","type":"reference"},{"text":" implementation for","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"https:\/\/coralproject.net\/","type":"reference"},{"text":".","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/FeedReaderViewController":{"role":"symbol","navigatorTitle":[{"text":"FeedReaderViewController","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeedReaderViewController","kind":"identifier"}],"url":"\/documentation\/psreaderui\/feedreaderviewcontroller","abstract":[{"type":"text","text":"A standalone view controller for displaying feed edition content."}],"kind":"symbol","title":"FeedReaderViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Features","title":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"]}]}]}]}