{"seeAlsoSections":[{"generated":true,"title":"Features","anchor":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"]}],"metadata":{"modules":[{"name":"PSReaderUI"}],"role":"article","title":"Deep Linking","roleHeading":"Article"},"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"variants":[{"paths":["\/documentation\/psreaderui\/deep-linking"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/psreaderui\/deep-linking"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Open a specific feed edition directly, bypassing the archive screen."}],"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","interfaceLanguage":"swift"},"sections":[],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When your app receives a push notification, handles a URL scheme, or responds"},{"type":"text","text":" "},{"type":"text","text":"to a universal link, you often want to jump straight to a specific edition"},{"type":"text","text":" "},{"type":"text","text":"rather than showing the archive grid first. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController"},{"type":"text","text":" "},{"type":"text","text":"provides a standalone reader that loads a single edition and presents its own"},{"type":"text","text":" "},{"type":"text","text":"dismiss button, making it ideal for these entry points."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController"},{"type":"text","text":" supports feed editions only. Replica"},{"type":"text","text":" "},{"type":"text","text":"editions are not supported. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions"},{"type":"text","text":" to determine"},{"type":"text","text":" "},{"type":"text","text":"which system your publication uses."}]}],"name":"Note","style":"note","type":"aside"},{"type":"paragraph","inlineContent":[{"text":"For general SDK setup and credentials, see ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started","type":"reference"},{"text":". For other","type":"text"},{"text":" ","type":"text"},{"text":"standalone view controllers like ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController","type":"reference"},{"text":", see","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","type":"reference"},{"text":".","type":"text"}]},{"anchor":"Opening-an-Edition","level":2,"type":"heading","text":"Opening an Edition"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Create a "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","isActive":true},{"type":"text","text":" using the initializer that matches the"},{"type":"text","text":" "},{"type":"text","text":"information you have available."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Latest edition by publication GUID:","type":"text"}]}]},{"type":"codeListing","syntax":"swift","code":["let reader = FeedReaderViewController(","    globalConfig: globalConfig,","    latestEditionForPublication: \"PUB_GUID\"",")"]},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Specific edition by GUID:"}]}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let reader = FeedReaderViewController(","    globalConfig: globalConfig,","    publicationGUID: \"PUB_GUID\",","    editionGUID: \"EDITION_GUID\"",")"]},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Specific edition using a shortcode:"}],"type":"strong"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let reader = FeedReaderViewController(","    globalConfig: globalConfig,","    shortcode: \"SHORTCODE\",","    editionGUID: \"EDITION_GUID\"",")"]},{"style":"tip","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Prefer the shortcode-based initializer when your archive uses","type":"text"},{"text":" ","type":"text"},{"code":".dynamicArchive","type":"codeVoice"},{"text":". The shortcode lets the SDK resolve the application","type":"text"},{"text":" ","type":"text"},{"text":"configuration automatically, so you don’t need to manage publication GUIDs","type":"text"},{"text":" ","type":"text"},{"text":"yourself.","type":"text"}]}],"name":"Tip"},{"inlineContent":[{"type":"text","text":"Pass an optional "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration","isActive":true,"type":"reference"},{"type":"text","text":" to any initializer to customize the"},{"type":"text","text":" "},{"type":"text","text":"reader’s appearance."}],"type":"paragraph"},{"type":"heading","level":2,"text":"Opening to a Specific Page","anchor":"Opening-to-a-Specific-Page"},{"inlineContent":[{"type":"text","text":"Every initializer accepts an optional "},{"type":"codeVoice","code":"openingPage"},{"type":"text","text":" parameter that scrolls the"},{"type":"text","text":" "},{"type":"text","text":"reader to a particular page on launch:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["\/\/ Open to the first page in a section","let reader = FeedReaderViewController(","    globalConfig: globalConfig,","    shortcode: \"SHORTCODE\",","    editionGUID: \"EDITION_GUID\",","    openingPage: .section(guid: \"SECTION_GUID\")",")","","\/\/ Open to an exact page","let reader = FeedReaderViewController(","    globalConfig: globalConfig,","    shortcode: \"SHORTCODE\",","    editionGUID: \"EDITION_GUID\",","    openingPage: .page(guid: \"PAGE_GUID\")",")"]},{"type":"heading","level":2,"text":"Presenting the Reader","anchor":"Presenting-the-Reader"},{"inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","type":"reference","isActive":true},{"type":"text","text":" is designed for modal presentation. It includes"},{"type":"text","text":" "},{"type":"text","text":"its own dismiss button, so you don’t need to wrap it in a navigation controller"},{"type":"text","text":" "},{"type":"text","text":"or add your own close button:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["self.present(reader, animated: true)"]},{"type":"heading","level":2,"text":"Opening Search Results","anchor":"Opening-Search-Results"},{"inlineContent":[{"type":"text","text":"When using "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchService","isActive":true},{"type":"text","text":" to build a custom search UI, you can open a"},{"type":"text","text":" "},{"type":"text","text":"search result by mapping "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult","isActive":true},{"type":"text","text":" fields to"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","isActive":true},{"type":"text","text":" parameters:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["guard let editionGUID = result.editionId,","      let publicationGUID = result.applicationId else {","    return","}","","let reader = FeedReaderViewController(","    globalConfig: globalConfig,","    publicationGUID: publicationGUID,","    editionGUID: editionGUID,","    openingPage: result.pageId.map { .page(guid: $0) }",")","","present(reader, animated: true)"]},{"style":"note","type":"aside","content":[{"inlineContent":[{"text":"The built-in ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchViewController","isActive":true,"type":"reference"},{"text":" and the carousel’s search tab","type":"text"},{"text":" ","type":"text"},{"text":"handle this automatically. You only need this when using ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchService","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"directly.","type":"text"}],"type":"paragraph"}],"name":"Note"},{"inlineContent":[{"type":"text","text":"See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"},{"type":"text","text":" for the full search integration guide."}],"type":"paragraph"}]}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Replica-and-Feed-Editions":{"abstract":[{"text":"Understand the two backend systems that power PSReaderUI content.","type":"text"}],"type":"topic","title":"Replica and Feed Editions","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","kind":"article","url":"\/documentation\/psreaderui\/replica-and-feed-editions"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"kind":"symbol","url":"\/documentation\/psreaderui","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"type":"topic","role":"collection"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Standalone-View-Controllers":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","kind":"article","url":"\/documentation\/psreaderui\/standalone-view-controllers","abstract":[{"text":"Use archive, bookmarks, downloads, and search views outside of the carousel.","type":"text"}],"role":"article","title":"Standalone View Controllers","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/FeedReaderViewController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedReaderViewController"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","type":"topic","url":"\/documentation\/psreaderui\/feedreaderviewcontroller","navigatorTitle":[{"kind":"identifier","text":"FeedReaderViewController"}],"abstract":[{"type":"text","text":"A standalone view controller for displaying feed edition content."}],"title":"FeedReaderViewController","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","kind":"article","role":"article","url":"\/documentation\/psreaderui\/text-to-speech","type":"topic","abstract":[{"text":"Add audio playback of article content using the SDK’s text-to-speech system.","type":"text"}],"title":"Text-to-Speech"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveViewController":{"kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController","title":"ArchiveViewController","url":"\/documentation\/psreaderui\/archiveviewcontroller","type":"topic","abstract":[{"text":"A standalone view controller for displaying publication archives.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArchiveViewController"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration","title":"ReaderConfiguration","abstract":[{"type":"text","text":"Configuration object for customizing the PSReaderUI Reader."}],"role":"symbol","navigatorTitle":[{"text":"ReaderConfiguration","kind":"identifier"}],"url":"\/documentation\/psreaderui\/readerconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"abstract":[{"text":"Display custom advertisements within the reader.","type":"text"}],"url":"\/documentation\/psreaderui\/advertisements","role":"article","title":"Advertisements","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","kind":"article","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchResult":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchResult"}],"type":"topic","title":"SearchResult","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult","kind":"symbol","abstract":[{"type":"text","text":"A single search result returned by the PageSuite search API."}],"navigatorTitle":[{"kind":"identifier","text":"SearchResult"}],"url":"\/documentation\/psreaderui\/searchresult"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"abstract":[{"text":"Restrict access to premium content with custom paywall screens.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","role":"article","kind":"article","url":"\/documentation\/psreaderui\/paywall-integration","type":"topic","title":"Paywall Integration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Getting-Started":{"type":"topic","url":"\/documentation\/psreaderui\/getting-started","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started","title":"Getting Started","role":"article","abstract":[{"text":"The PSReaderUI SDK provides a flexible, modern UI for integrating the PageSuite","type":"text"},{"text":" ","type":"text"},{"text":"PSReader SDK into your application.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"url":"\/documentation\/psreaderui\/sharing","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","role":"article","abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"type":"topic","title":"Sharing"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchViewController":{"abstract":[{"type":"text","text":"A standalone view controller for searching feed edition content."}],"title":"SearchViewController","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchViewController","url":"\/documentation\/psreaderui\/searchviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchViewController"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SearchViewController"}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchService":{"type":"topic","navigatorTitle":[{"text":"SearchService","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchService","kind":"symbol","url":"\/documentation\/psreaderui\/searchservice","role":"symbol","abstract":[{"text":"A service for searching PageSuite feed edition content.","type":"text"}],"title":"SearchService","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchService","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Search":{"url":"\/documentation\/psreaderui\/search","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search","role":"article","title":"Search","abstract":[{"type":"text","text":"Search across feed edition content for articles and pages."}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Commenting":{"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","abstract":[{"text":"Add comment counts, comment buttons, and commenting integration to the reader.","type":"text"}],"role":"article","kind":"article","title":"Commenting","url":"\/documentation\/psreaderui\/commenting"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"role":"article","title":"Analytics","type":"topic","abstract":[{"text":"Track user interactions and content engagement across the PSReaderUI SDK.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","kind":"article","url":"\/documentation\/psreaderui\/analytics"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"role":"article","url":"\/documentation\/psreaderui\/media-playback","abstract":[{"type":"text","text":"Enable video and media playback within the reader."}],"kind":"article","title":"Media Playback","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"title":"Features","anchor":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"],"generated":true}],"path":"\/seeAlsoSections"}]}]}