{"sections":[],"abstract":[{"text":"A complete Xcode project demonstrating PSReaderUI SDK integration.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"type":"reference","identifier":"https:\/\/pagesuite-builds.s3.eu-west-1.amazonaws.com\/PSReaderUISDK\/sdkDemos\/psreader-ui-ios.zip","isActive":true}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/demo-project"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/demo-project"]}],"metadata":{"title":"Demo Project","roleHeading":"Article","modules":[{"name":"PSReaderUI"}],"role":"article"},"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController"],"generated":true,"title":"Essentials","anchor":"Essentials"}],"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Demo-Project","interfaceLanguage":"swift"},"kind":"article","references":{"https://pagesuite-builds.s3.eu-west-1.amazonaws.com/PSReaderUISDK/sdkDemos/psreader-ui-ios.zip":{"title":"Download Demo Project","titleInlineContent":[{"type":"text","text":"Download Demo Project"}],"identifier":"https:\/\/pagesuite-builds.s3.eu-west-1.amazonaws.com\/PSReaderUISDK\/sdkDemos\/psreader-ui-ios.zip","url":"https:\/\/pagesuite-builds.s3.eu-west-1.amazonaws.com\/PSReaderUISDK\/sdkDemos\/psreader-ui-ios.zip","type":"link"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Getting-Started":{"type":"topic","url":"\/documentation\/psreaderui\/getting-started","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started","title":"Getting Started","role":"article","abstract":[{"text":"The PSReaderUI SDK provides a flexible, modern UI for integrating the PageSuite","type":"text"},{"text":" ","type":"text"},{"text":"PSReader SDK into your application.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"kind":"symbol","url":"\/documentation\/psreaderui","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"type":"topic","role":"collection"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController":{"url":"\/documentation\/psreaderui\/carouselviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarouselViewController"}],"kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarouselViewController"}],"abstract":[{"type":"text","text":"The primary view controller provided by the SDK for presenting digital publication"},{"type":"text","text":" "},{"type":"text","text":"content through an intuitive carousel interface."}],"title":"CarouselViewController"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlobalConfiguration","kind":"identifier"}],"title":"GlobalConfiguration","navigatorTitle":[{"text":"GlobalConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"A configuration object that provides global settings and delegates for","type":"text"},{"text":" ","type":"text"},{"text":"customizing the SDK’s behavior and appearance.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","kind":"symbol","url":"\/documentation\/psreaderui\/globalconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"anchor":"Essentials","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started"],"title":"Essentials","generated":true}],"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}