{"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"primaryContentSections":[{"content":[{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"This guide walks you through installation, credentials, SDK initialization, and"},{"type":"text","text":" "},{"type":"text","text":"launching your first reader experience. By the end you will have a working"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","isActive":true},{"type":"text","text":" displaying your publication editions."}],"type":"paragraph"},{"anchor":"Installation","level":2,"text":"Installation","type":"heading"},{"inlineContent":[{"text":"We support three installation methods for integrating the SDK into your iOS app:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Manual installation"}]}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"CocoaPods"}],"type":"strong"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Swift Package Manager (SPM)","type":"text"}],"type":"strong"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Access to our CocoaPods Specs repository and Swift Package repository is "},{"type":"strong","inlineContent":[{"text":"private","type":"text"}]},{"type":"text","text":" and granted via SSH."},{"type":"text","text":" "},{"type":"text","text":"To request access, please generate an SSH key pair and send the public key to our team. We’ll provision access to the appropriate repositories."}],"type":"paragraph"},{"type":"thematicBreak"},{"anchor":"1-Manual-Installation","level":3,"text":"1. Manual Installation","type":"heading"},{"inlineContent":[{"type":"text","text":"Manually install the provided "},{"type":"codeVoice","code":"PSReaderUI.xcframework"},{"type":"text","text":" and its dependencies by dragging and dropping them into your Xcode project."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PSReaderUI.xcframework"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"PSReader.xcframework","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PDFNet.xcframework"}]}]},{"content":[{"inlineContent":[{"text":"Tools.xcframework","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Ensure the frameworks are set to "},{"type":"strong","inlineContent":[{"type":"text","text":"Embed and Sign"}]},{"type":"text","text":" in your Xcode project settings."}],"type":"paragraph"},{"type":"thematicBreak"},{"anchor":"2-CocoaPods","level":3,"text":"2. CocoaPods","type":"heading"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Specs repository:"}],"type":"strong"}],"type":"paragraph"},{"syntax":null,"code":["git@bitbucket.org:pagesuite\/psreader-specs.git"],"type":"codeListing"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Note"}]},{"text":": The Apryse SDK integration is slightly non-standard. We recommend pinning it to version ","type":"text"},{"type":"codeVoice","code":"11.6.0.85755"},{"text":", as this is the version we have tested internally.","type":"text"}]}],"style":"note","type":"aside"},{"inlineContent":[{"type":"text","text":"Example "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":":"}],"type":"paragraph"},{"syntax":"ruby","code":["source 'git@bitbucket.org:pagesuite\/psreader-specs.git'","","target 'YourAppTarget' do","  use_frameworks!","","  pod 'PDFTron', podspec: 'https:\/\/www.pdftron.com\/downloads\/ios\/cocoapods\/xcframeworks\/pdftron\/11.3.0.85075.podspec'","  pod 'PDFTronTools', podspec: 'https:\/\/www.pdftron.com\/downloads\/ios\/cocoapods\/xcframeworks\/pdftron-tools\/11.3.0.85075.podspec'","  pod 'PSReaderUI2'","end"],"type":"codeListing"},{"type":"thematicBreak"},{"anchor":"3-Swift-Package-Manager","level":3,"text":"3. Swift Package Manager","type":"heading"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Package URL:"}]}],"type":"paragraph"},{"syntax":null,"code":["git@bitbucket.org:pagesuite\/psreader-swift-package.git"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"To integrate:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"In Xcode, go to ","type":"text"},{"inlineContent":[{"type":"text","text":"File > Add Packages…"}],"type":"strong"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enter the repository URL above."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Authenticate via SSH (make sure you have been granted access)."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Select the desired version\/range and add the package to your target."}],"type":"paragraph"}]}],"type":"orderedList"},{"anchor":"Versioning","level":2,"text":"Versioning","type":"heading"},{"inlineContent":[{"type":"text","text":"Starting in 2026, the SDK uses a calendar-based versioning scheme to align"},{"type":"text","text":" "},{"type":"text","text":"with the rest of the PageSuite product line. Versions follow the format"},{"type":"text","text":" "},{"inlineContent":[{"text":"year.month.patch","type":"text"}],"type":"strong"},{"type":"text","text":" — for example, "},{"code":"26.1.0","type":"codeVoice"},{"type":"text","text":" is the first January 2026"},{"type":"text","text":" "},{"type":"text","text":"release."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This scheme does "},{"inlineContent":[{"text":"not","type":"text"}],"type":"strong"},{"type":"text","text":" follow semantic versioning. While we strive to"},{"type":"text","text":" "},{"type":"text","text":"maintain API stability, breaking changes may occur in any release without a"},{"type":"text","text":" "},{"type":"text","text":"major version bump. We recommend pinning to a specific version and reviewing"},{"type":"text","text":" "},{"type":"text","text":"the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log"},{"type":"text","text":" before upgrading."}],"type":"paragraph"},{"anchor":"Credentials","level":2,"text":"Credentials","type":"heading"},{"inlineContent":[{"text":"To use the PSReaderUI SDK you need the following credentials. Contact your","type":"text"},{"type":"text","text":" "},{"type":"text","text":"PageSuite account manager or check the PageSuite portal to obtain them."}],"type":"paragraph"},{"rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Credential"}]}],[{"type":"paragraph","inlineContent":[{"text":"Description","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"API Key","type":"text"}],"type":"strong"}]}],[{"type":"paragraph","inlineContent":[{"text":"Authenticates your app with the PageSuite backend.","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Account GUID"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Identifies your account."}]}]],[[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Shortcode","type":"text"}],"type":"strong"},{"type":"text","text":" (recommended)"}]}],[{"type":"paragraph","inlineContent":[{"text":"A short identifier that maps to your publication configuration. Use with ","type":"text"},{"code":".dynamicArchive","type":"codeVoice"},{"text":" to load content automatically.","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Application GUID"}],"type":"strong"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Identifies a specific feed edition publication."}]}]],[[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Publication GUID"}],"type":"strong"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Identifies a specific replica publication."}]}]]],"header":"row","type":"table"},{"name":"Tip","content":[{"inlineContent":[{"type":"text","text":""},{"type":"strong","inlineContent":[{"type":"text","text":"Shortcode is the recommended approach."}]},{"type":"text","text":" It lets the SDK fetch your"},{"type":"text","text":" "},{"type":"text","text":"publication configuration dynamically, so you don’t need to manage GUIDs"},{"type":"text","text":" "},{"type":"text","text":"yourself."}],"type":"paragraph"}],"style":"tip","type":"aside"},{"anchor":"Initialize-the-SDK","level":2,"text":"Initialize the SDK","type":"heading"},{"inlineContent":[{"type":"text","text":"The PSReader SDK must be globally initialized before it can be used. Call this"},{"type":"text","text":" "},{"type":"text","text":"method early in your app lifecycle to optimize reader launch speed. You only"},{"type":"text","text":" "},{"type":"text","text":"need to call this method once."}],"type":"paragraph"},{"inlineContent":[{"text":"The completion handler is only used to return a status flag. It is not required","type":"text"},{"text":" ","type":"text"},{"text":"and it is not necessary to wait for the completion handler before continuing.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This method will only fail if the API key is invalid.","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["import PSReaderUI","","PSReader.initialize(apiKey: apiKey, completion: { success in","    \/\/ Note: The completion handler may be called on any thread.","})"],"type":"codeListing"},{"anchor":"Quick-Start","level":2,"text":"Quick Start","type":"heading"},{"inlineContent":[{"text":"Create a ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","isActive":true,"type":"reference"},{"text":" with your credentials and basic theming:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["import PSReaderUI","","let globalConfig = PSReaderUI.GlobalConfiguration(","    apiKey: apiKey,","    accountGUID: accountGUID,","    primaryFont: .systemFont(ofSize: 12),","    secondaryFont: .systemFont(ofSize: 12),","    brandColor: UIColor(dynamicProvider: {","        $0.userInterfaceStyle == .dark ? .white : .black","    })",")"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"The primary font is used for titles, headlines, and publication names. The"},{"type":"text","text":" "},{"type":"text","text":"secondary font covers the remaining UI. The brand color is used as an accent"},{"type":"text","text":" "},{"type":"text","text":"throughout the SDK."}],"type":"paragraph"},{"inlineContent":[{"text":"Then create a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController"},{"text":" using a ","type":"text"},{"type":"strong","inlineContent":[{"text":"shortcode","type":"text"}]},{"text":" and","type":"text"},{"text":" ","type":"text"},{"code":".dynamicArchive","type":"codeVoice"},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["let carouselVC = PSReaderUI.CarouselViewController(","    globalConfig: globalConfig,","    sections: [","        .dynamicArchive(\"Editions\", shortcode: \"SHORTCODE\"),","        .subsections(\"My Content\", [","            .init(name: \"Bookmarks\", type: .bookmarks(type: .all)),","            .init(name: \"Downloads\", type: .downloads(type: .all))","        ])","    ]",")"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"You can now push, present, or embed the "},{"code":"CarouselViewController","type":"codeVoice"},{"type":"text","text":" as needed."},{"type":"text","text":" "},{"type":"text","text":"See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup"},{"type":"text","text":" for more detail on sections, content types, and layout"},{"type":"text","text":" "},{"type":"text","text":"options."}],"type":"paragraph"},{"anchor":"Manual-Configuration","level":3,"text":"Manual Configuration","type":"heading"},{"inlineContent":[{"type":"text","text":"If you need to use explicit GUIDs instead of a shortcode, replace"},{"type":"text","text":" "},{"type":"codeVoice","code":".dynamicArchive"},{"type":"text","text":" with a "},{"type":"codeVoice","code":".section"},{"type":"text","text":" or "},{"type":"codeVoice","code":".subsections"},{"type":"text","text":" entry using the"},{"type":"text","text":" "},{"type":"text","text":"appropriate content type:"}],"type":"paragraph"},{"syntax":"swift","code":["\/\/ Feed edition archive with an application GUID",".section(.init(name: \"Editions\", type: .feedArchive(guid: \"APP_GUID\")))","","\/\/ Replica archive with a publication GUID",".section(.init(name: \"Editions\", type: .replicaArchive(guid: \"PUB_GUID\")))"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","isActive":true},{"type":"text","text":" to determine which content type matches"},{"type":"text","text":" "},{"type":"text","text":"your publication."}],"type":"paragraph"},{"anchor":"Dark-Mode","level":2,"text":"Dark Mode","type":"heading"},{"inlineContent":[{"type":"text","text":"The SDK fully supports dark mode. To provide distinct light and dark brand"},{"type":"text","text":" "},{"type":"text","text":"colors, use a dynamic "},{"type":"codeVoice","code":"UIColor"},{"type":"text","text":":"}],"type":"paragraph"},{"syntax":"swift","code":["let brandColor = UIColor(dynamicProvider: {","    $0.userInterfaceStyle == .dark ? .white : .black","})"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Alternatively, define a color in your asset catalog so the system resolves it"},{"type":"text","text":" "},{"type":"text","text":"automatically."}],"type":"paragraph"},{"inlineContent":[{"text":"To force a specific appearance across the entire SDK, set","type":"text"},{"text":" ","type":"text"},{"code":"overrideUserInterfaceStyle","type":"codeVoice"},{"text":" on the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","type":"reference"},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["carouselVC.overrideUserInterfaceStyle = .dark"],"type":"codeListing"},{"anchor":"Embedding-in-SwiftUI","level":2,"text":"Embedding in SwiftUI","type":"heading"},{"inlineContent":[{"type":"text","text":"Wrap the "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","isActive":true},{"type":"text","text":" in a "},{"type":"codeVoice","code":"UIViewControllerRepresentable"},{"type":"text","text":" to"},{"type":"text","text":" "},{"type":"text","text":"use it in a SwiftUI view hierarchy:"}],"type":"paragraph"},{"syntax":"swift","code":["import SwiftUI","import PSReaderUI","","struct ReaderView: UIViewControllerRepresentable {","    func makeUIViewController(context: Context) -> PSReaderUI.CarouselViewController {","        let globalConfig = PSReaderUI.GlobalConfiguration(","            apiKey: \"API_KEY\",","            accountGUID: \"ACCOUNT_GUID\"","        )","        return PSReaderUI.CarouselViewController(","            globalConfig: globalConfig,","            sections: [","                .dynamicArchive(\"Editions\", shortcode: \"SHORTCODE\")","            ]","        )","    }","","    func updateUIViewController(_ uiViewController: PSReaderUI.CarouselViewController, context: Context) {}","}"],"type":"codeListing"},{"anchor":"Using-a-Coordinator-as-a-Delegate","level":3,"text":"Using a Coordinator as a Delegate","type":"heading"},{"inlineContent":[{"type":"text","text":"The SDK makes wide use of delegate protocols (see "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"When embedding in SwiftUI, you can implement delegates on a "},{"type":"codeVoice","code":"Coordinator"},{"type":"text","text":" so their"},{"type":"text","text":" "},{"type":"text","text":"lifecycle is tied to the representable:"}],"type":"paragraph"},{"syntax":"swift","code":["struct ReaderView: UIViewControllerRepresentable {","    func makeCoordinator() -> Coordinator {","        Coordinator()","    }","","    func makeUIViewController(context: Context) -> PSReaderUI.CarouselViewController {","        let globalConfig = PSReaderUI.GlobalConfiguration(","            apiKey: \"API_KEY\",","            accountGUID: \"ACCOUNT_GUID\",","            navigationDelegate: context.coordinator","        )","        return PSReaderUI.CarouselViewController(","            globalConfig: globalConfig,","            sections: [","                .dynamicArchive(\"Editions\", shortcode: \"SHORTCODE\")","            ]","        )","    }","","    func updateUIViewController(_ uiViewController: PSReaderUI.CarouselViewController, context: Context) {}","","    class Coordinator: NavigationDelegate {","        func willPresentReplicaReader() {","            \/\/ Track analytics, adjust UI state, etc.","        }","","        func willDismissReplicaReader() {","            \/\/ Restore UI state, etc.","        }","    }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"The same approach works for any delegate — have "},{"type":"codeVoice","code":"Coordinator"},{"type":"text","text":" conform to"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate"},{"type":"text","text":", or any combination you need and"},{"type":"text","text":" "},{"type":"text","text":"pass "},{"type":"codeVoice","code":"context.coordinator"},{"text":" to the corresponding ","type":"text"},{"code":"GlobalConfiguration","type":"codeVoice"},{"text":" ","type":"text"},{"text":"parameter.","type":"text"}],"type":"paragraph"},{"anchor":"Presenting-Modally","level":2,"text":"Presenting Modally","type":"heading"},{"inlineContent":[{"type":"text","text":"When presenting the "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","isActive":true},{"type":"text","text":" modally, add a dismiss button"},{"type":"text","text":" "},{"type":"text","text":"so users can close it:"}],"type":"paragraph"},{"syntax":"swift","code":["var carouselConfig = PSReaderUI.CarouselConfiguration(globalConfig: globalConfig)","carouselConfig.dismissButton = .dismissButton(position: .leading())","","let carouselVC = PSReaderUI.CarouselViewController(","    globalConfig: globalConfig,","    carouselConfig: carouselConfig,","    sections: [ \/* ... *\/ ]",")"],"type":"codeListing"},{"inlineContent":[{"text":"If you are embedding the carousel inside your own ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"set ","type":"text"},{"type":"codeVoice","code":"embedInNavigationController"},{"text":" to ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" on the carousel configuration","type":"text"},{"text":" ","type":"text"},{"text":"to prevent the SDK from creating a second navigation controller, which would","type":"text"},{"text":" ","type":"text"},{"text":"result in double navigation bars:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["carouselConfig.embedInNavigationController = false"],"type":"codeListing"},{"anchor":"App-Store-Compliance","level":2,"text":"App Store Compliance","type":"heading"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Export Compliance"}],"type":"strong"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The SDK does ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"not"}]},{"text":" use any non-standard encryption and will not affect export controls.","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Privacy Compliance","type":"text"}]}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The SDK does ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"not"}]},{"text":" collect any private information and will not affect privacy compliance.","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Required Info.plist Keys"}]}],"type":"paragraph"},{"inlineContent":[{"text":"The SDK uses the Apryse library to render PDFs, which is preferred over Core","type":"text"},{"text":" ","type":"text"},{"text":"Graphics for its closer adherence to PDF standards. Add the following keys to","type":"text"},{"text":" ","type":"text"},{"text":"your app’s ","type":"text"},{"inlineContent":[{"text":"Info.plist","type":"text"}],"type":"strong"},{"text":":","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"For more information, see the Apryse documentation:","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"https:\/\/docs.apryse.com\/ios\/guides\/get-started\/integration?tab=spm","type":"reference"}],"type":"paragraph"},{"syntax":"xml","code":["<key>NSCameraUsageDescription<\/key>","<string>This will allow you to use the image from your camera.<\/string>","<key>NSPhotoLibraryAddUsageDescription<\/key>","<string>This will allow you to add images to your photo library.<\/string>","<key>NSPhotoLibraryUsageDescription<\/key>","<string>This will allow you to create signatures and annotations from images in your photo library.<\/string>","<key>NSBluetoothAlwaysUsageDescription<\/key>","<string>This will allow us to detect if an Apple Pencil is paired, enabling palm rejection and the ability to scroll with one finger while annotating.<\/string>","<key>NSBluetoothPeripheralUsageDescription<\/key>","<string>This will allow us detect if an Apple Pencil is paired, enabling palm rejection and the ability to scroll with one finger while annotating.<\/string>"],"type":"codeListing"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/getting-started"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/getting-started"]}],"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Demo-Project"],"generated":true,"anchor":"Essentials"}],"metadata":{"modules":[{"name":"PSReaderUI"}],"roleHeading":"Article","title":"Getting Started","role":"article"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","abstract":[{"type":"text","text":"The PSReaderUI SDK provides a flexible, modern UI for integrating the PageSuite"},{"type":"text","text":" "},{"type":"text","text":"PSReader SDK into your application."}],"sections":[],"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started","interfaceLanguage":"swift"},"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/PaywallDelegate":{"title":"PaywallDelegate","url":"\/documentation\/psreaderui\/paywalldelegate","navigatorTitle":[{"kind":"identifier","text":"PaywallDelegate"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaywallDelegate"}],"abstract":[{"text":"A delegate protocol used to provide paywall view controllers for controlling","type":"text"},{"text":" ","type":"text"},{"text":"access to premium content within the SDK.","type":"text"}],"role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Carousel-Setup":{"role":"article","type":"topic","abstract":[{"text":"Configure the carousel’s sections, content sources, and layout.","type":"text"}],"title":"Carousel Setup","kind":"article","url":"\/documentation\/psreaderui\/carousel-setup","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Replica-and-Feed-Editions":{"title":"Replica and Feed Editions","url":"\/documentation\/psreaderui\/replica-and-feed-editions","kind":"article","abstract":[{"text":"Understand the two backend systems that power PSReaderUI content.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","url":"\/documentation\/psreaderui","role":"collection","type":"topic","abstract":[{"text":"A UI framework for building digital newspaper and magazine reader experiences on iOS.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ShareDelegate":{"url":"\/documentation\/psreaderui\/sharedelegate","kind":"symbol","role":"symbol","abstract":[{"text":"Delegate protocol used to provide sharing functionality within the SDK.","type":"text"}],"title":"ShareDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShareDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"ShareDelegate"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"GlobalConfiguration"}],"url":"\/documentation\/psreaderui\/globalconfiguration","role":"symbol","title":"GlobalConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlobalConfiguration"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","kind":"symbol","abstract":[{"type":"text","text":"A configuration object that provides global settings and delegates for"},{"type":"text","text":" "},{"type":"text","text":"customizing the SDK’s behavior and appearance."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","abstract":[{"type":"text","text":"The primary view controller provided by the SDK for presenting digital publication"},{"type":"text","text":" "},{"type":"text","text":"content through an intuitive carousel interface."}],"url":"\/documentation\/psreaderui\/carouselviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CarouselViewController","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"CarouselViewController","kind":"identifier"}],"title":"CarouselViewController","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Change-Log":{"url":"\/documentation\/psreaderui\/change-log","abstract":[{"text":"Track new features, improvements, bug fixes, and other updates in each","type":"text"},{"text":" ","type":"text"},{"text":"PSReaderUI SDK release.","type":"text"}],"kind":"article","title":"Change Log","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log","type":"topic"},"https://docs.apryse.com/ios/guides/get-started/integration?tab=spm":{"identifier":"https:\/\/docs.apryse.com\/ios\/guides\/get-started\/integration?tab=spm","title":"Apryse iOS Integration Guide","type":"link","titleInlineContent":[{"text":"Apryse iOS Integration Guide","type":"text"}],"url":"https:\/\/docs.apryse.com\/ios\/guides\/get-started\/integration?tab=spm"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Demo-Project":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Demo-Project","abstract":[{"type":"text","text":"A complete Xcode project demonstrating PSReaderUI SDK integration."}],"title":"Demo Project","role":"article","kind":"article","url":"\/documentation\/psreaderui\/demo-project","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Essentials","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Demo-Project"],"anchor":"Essentials"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}