{"abstract":[{"text":"Localize all user-facing strings in the PSReaderUI SDK.","type":"text"}],"primaryContentSections":[{"content":[{"anchor":"Overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Localization is provided by the "},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager","type":"reference"},{"type":"text","text":" singleton. Every"},{"type":"text","text":" "},{"type":"text","text":"user-facing string in the SDK is identified by a "},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizedStringKey","type":"reference"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The base "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager"},{"type":"text","text":" uses "},{"type":"codeVoice","code":"NSLocalizedString"},{"type":"text","text":" to resolve each key,"},{"type":"text","text":" "},{"type":"text","text":"with the key’s "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizedStringKey"},{"type":"text","text":" "},{"type":"codeVoice","code":"rawValue"},{"type":"text","text":" as the lookup key and its"},{"type":"text","text":" "},{"type":"text","text":"built-in default as the fallback value. This means you can provide translations"},{"type":"text","text":" "},{"type":"text","text":"using a standard "},{"type":"codeVoice","code":".strings"},{"type":"text","text":" file or a String Catalog ("},{"type":"codeVoice","code":".xcstrings"},{"type":"text","text":") in your"},{"type":"text","text":" "},{"type":"text","text":"app bundle without writing any code."}]},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"New localized string keys may be added between SDK releases. After"},{"type":"text","text":" "},{"type":"text","text":"updating the SDK, review the "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizedStringKey","isActive":true,"type":"reference"},{"type":"text","text":" reference to identify"},{"type":"text","text":" "},{"type":"text","text":"any new keys that need translations."}]}]},{"anchor":"Using-String-Catalogs","type":"heading","text":"Using String Catalogs","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Because the SDK resolves strings through "},{"type":"codeVoice","code":"NSLocalizedString"},{"type":"text","text":", any translation"},{"type":"text","text":" "},{"type":"text","text":"workflow that produces "},{"type":"codeVoice","code":".strings"},{"type":"text","text":" or "},{"type":"codeVoice","code":".xcstrings"},{"type":"text","text":" files works automatically."},{"type":"text","text":" "},{"type":"text","text":"In Xcode, add a String Catalog to your app target and include entries whose"},{"type":"text","text":" "},{"type":"text","text":"keys match the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizedStringKey"},{"type":"text","text":" raw values. The SDK will pick them up"},{"type":"text","text":" "},{"type":"text","text":"at runtime."}]},{"anchor":"Subclassing-LocalizationManager","type":"heading","text":"Subclassing LocalizationManager","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more control, subclass "},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager","type":"reference"},{"type":"text","text":" and replace the shared"},{"type":"text","text":" "},{"type":"text","text":"singleton. This lets you load strings from a remote server, apply A\/B test"},{"type":"text","text":" "},{"type":"text","text":"variants, or fall through to the default behavior selectively:"}]},{"type":"codeListing","syntax":"swift","code":["import PSReaderUI","","class CustomLocalizationManager: PSReaderUI.LocalizationManager {","    override func localizedString(for key: LocalizedStringKey) -> String {","        switch key {","        case .bookmarksTitle:","            return \"Saved\"","        case .downloadsTitle:","            return \"Offline\"","        default:","            return super.localizedString(for: key)","        }","    }","}","","PSReaderUI.LocalizationManager.shared = CustomLocalizationManager()"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set the custom manager before creating any SDK view controllers so that the"},{"type":"text","text":" "},{"type":"text","text":"overridden strings are used from the start."}]},{"anchor":"Reference","type":"heading","text":"Reference","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizedStringKey"},{"type":"text","text":" for the complete list of keys and their default"},{"type":"text","text":" "},{"type":"text","text":"values."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/localization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/localization"]}],"kind":"article","metadata":{"roleHeading":"Article","role":"article","title":"Localization","modules":[{"name":"PSReaderUI"}]},"seeAlsoSections":[{"generated":true,"anchor":"Customization","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers"],"title":"Customization"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"sections":[],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Theming-and-Customization":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","title":"Theming and Customization","abstract":[{"type":"text","text":"Adjust fonts, colors, icons, and layouts to match your app’s brand."}],"role":"article","url":"\/documentation\/psreaderui\/theming-and-customization","kind":"article","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LocalizedStringKey":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizedStringKey","title":"LocalizedStringKey","abstract":[{"text":"Defines keys used to identify localizable strings in the SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"LocalizedStringKey","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalizedStringKey","kind":"identifier"}],"url":"\/documentation\/psreaderui\/localizedstringkey","type":"topic","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"kind":"symbol","url":"\/documentation\/psreaderui","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"type":"topic","role":"collection"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Carousel-Setup":{"type":"topic","abstract":[{"type":"text","text":"Configure the carousel’s sections, content sources, and layout."}],"url":"\/documentation\/psreaderui\/carousel-setup","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","kind":"article","title":"Carousel Setup","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LocalizationManager":{"title":"LocalizationManager","role":"symbol","navigatorTitle":[{"text":"LocalizationManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalizationManager","kind":"identifier"}],"abstract":[{"type":"text","text":"Provides localized strings."}],"url":"\/documentation\/psreaderui\/localizationmanager","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Standalone-View-Controllers":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","kind":"article","url":"\/documentation\/psreaderui\/standalone-view-controllers","abstract":[{"text":"Use archive, bookmarks, downloads, and search views outside of the carousel.","type":"text"}],"role":"article","title":"Standalone View Controllers","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Customization","generated":true,"anchor":"Customization","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers"]}]}]}]}