{"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"variants":[{"paths":["\/documentation\/psreaderui\/media-playback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/psreaderui\/media-playback"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Enable video and media playback within the reader.","type":"text"}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The PSReaderUI SDK does "},{"type":"strong","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" bundle a video player. To enable video"},{"type":"text","text":" "},{"type":"text","text":"playback for media embedded in editions, implement the "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate","isActive":true},{"type":"text","text":" "},{"type":"text","text":"protocol and provide your own player view controller."}]},{"anchor":"Protocol-Methods","type":"heading","level":2,"text":"Protocol Methods"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate"},{"text":" protocol defines two methods:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate\/videoViewController(for:presentingFrom:)","isActive":true,"type":"reference"},{"text":" — returns a view","type":"text"},{"text":" ","type":"text"},{"text":"controller for video playback, which the SDK embeds in its media gallery UI.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate\/pdfMediaOverlay(for:in:superview:)","type":"reference","isActive":true},{"text":" — returns a media","type":"text"},{"text":" ","type":"text"},{"text":"overlay for embedded media objects within replica edition PDF pages.","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"Both methods return ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" by default, meaning media is not played unless you","type":"text"},{"text":" ","type":"text"},{"text":"provide an implementation.","type":"text"}]},{"anchor":"Example","type":"heading","level":2,"text":"Example"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A minimal implementation using "},{"type":"codeVoice","code":"AVPlayerViewController"},{"type":"text","text":":"}]},{"code":["import AVKit","import PSReaderUI","","struct MyMediaDelegate: PSReaderUI.MediaDelegate {","    func videoViewController(","        for video: PSEVideo,","        presentingFrom: UIViewController","    ) -> UIViewController? {","        guard let url = video.url else { return nil }","","        let player = AVPlayer(url: url)","        let playerVC = AVPlayerViewController()","        playerVC.player = player","        return playerVC","    }","}"],"type":"codeListing","syntax":"swift"},{"anchor":"PDF-Media-Overlay","type":"heading","level":3,"text":"PDF Media Overlay"},{"type":"paragraph","inlineContent":[{"text":"To handle media objects embedded directly in replica edition PDF pages (such as","type":"text"},{"text":" ","type":"text"},{"text":"inline videos or interactive elements), implement ","type":"text"},{"code":"pdfMediaOverlay","type":"codeVoice"},{"text":":","type":"text"}]},{"code":["struct MyMediaDelegate: PSReaderUI.MediaDelegate {","    func videoViewController(","        for video: PSEVideo,","        presentingFrom: UIViewController","    ) -> UIViewController? {","        guard let url = video.url else { return nil }","","        let player = AVPlayer(url: url)","        let playerVC = AVPlayerViewController()","        playerVC.player = player","        return playerVC","    }","","    func pdfMediaOverlay(","        for mediaObject: PSEMediaObject,","        in page: PSEPage,","        superview: UIView","    ) -> PSEMediaOverlay? {","        \/\/ Return a media overlay for the embedded object, or nil to skip","        return nil","    }","}"],"type":"codeListing","syntax":"swift"},{"content":[{"inlineContent":[{"text":"The SDK supports video media objects embedded in PDF pages. Audio and","type":"text"},{"text":" ","type":"text"},{"text":"interactive media types are passed through the same delegate methods —","type":"text"},{"text":" ","type":"text"},{"text":"inspect the ","type":"text"},{"code":"PSEMediaObject","type":"codeVoice"},{"text":" properties to determine the media type and","type":"text"},{"text":" ","type":"text"},{"text":"handle accordingly.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note","name":"Note"},{"anchor":"Assigning-the-Delegate","type":"heading","level":2,"text":"Assigning the Delegate"},{"type":"paragraph","inlineContent":[{"text":"Set the delegate on your ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","type":"reference"},{"text":":","type":"text"}]},{"code":["globalConfig.mediaDelegate = MyMediaDelegate()"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate is inherited by all reader configurations created from the"},{"type":"text","text":" "},{"type":"text","text":"global configuration."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"},"sections":[],"seeAlsoSections":[{"anchor":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"],"generated":true,"title":"Features"}],"kind":"article","metadata":{"modules":[{"name":"PSReaderUI"}],"role":"article","roleHeading":"Article","title":"Media Playback"},"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/MediaDelegate/pdfMediaOverlay(for:in:superview:)":{"abstract":[{"text":"Provides a custom media overlay for an embedded media object within a PDF page.","type":"text"}],"url":"\/documentation\/psreaderui\/mediadelegate\/pdfmediaoverlay(for:in:superview:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pdfMediaOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PSEMediaObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEMediaObject"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PSEPage","kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEPage"},{"text":", ","kind":"text"},{"text":"superview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":") -> ","kind":"text"},{"text":"PSEMediaOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEMediaOverlay"},{"text":"?","kind":"text"}],"defaultImplementations":1,"title":"pdfMediaOverlay(for:in:superview:)","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate\/pdfMediaOverlay(for:in:superview:)","required":true,"kind":"symbol","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"abstract":[{"text":"Display custom advertisements within the reader.","type":"text"}],"url":"\/documentation\/psreaderui\/advertisements","role":"article","title":"Advertisements","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","kind":"article","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlobalConfiguration","kind":"identifier"}],"title":"GlobalConfiguration","navigatorTitle":[{"text":"GlobalConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"A configuration object that provides global settings and delegates for","type":"text"},{"text":" ","type":"text"},{"text":"customizing the SDK’s behavior and appearance.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","kind":"symbol","url":"\/documentation\/psreaderui\/globalconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","kind":"article","role":"article","url":"\/documentation\/psreaderui\/text-to-speech","type":"topic","abstract":[{"text":"Add audio playback of article content using the SDK’s text-to-speech system.","type":"text"}],"title":"Text-to-Speech"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"role":"article","title":"Analytics","type":"topic","abstract":[{"text":"Track user interactions and content engagement across the PSReaderUI SDK.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","kind":"article","url":"\/documentation\/psreaderui\/analytics"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Commenting":{"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","abstract":[{"text":"Add comment counts, comment buttons, and commenting integration to the reader.","type":"text"}],"role":"article","kind":"article","title":"Commenting","url":"\/documentation\/psreaderui\/commenting"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"url":"\/documentation\/psreaderui\/sharing","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","role":"article","abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"type":"topic","title":"Sharing"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Search":{"url":"\/documentation\/psreaderui\/search","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search","role":"article","title":"Search","abstract":[{"type":"text","text":"Search across feed edition content for articles and pages."}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Deep-Linking":{"title":"Deep Linking","role":"article","url":"\/documentation\/psreaderui\/deep-linking","type":"topic","abstract":[{"text":"Open a specific feed edition directly, bypassing the archive screen.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","kind":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/MediaDelegate/videoViewController(for:presentingFrom:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PSEVideo","kind":"typeIdentifier","preciseIdentifier":"c:@M@PSReader@objc(cs)PSEVideo"},{"text":", ","kind":"text"},{"text":"presentingFrom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"required":true,"role":"symbol","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate\/videoViewController(for:presentingFrom:)","abstract":[{"type":"text","text":"Provides a view controller for video playback, which the SDK embeds into its"},{"type":"text","text":" "},{"type":"text","text":"reader media gallery UI."}],"url":"\/documentation\/psreaderui\/mediadelegate\/videoviewcontroller(for:presentingfrom:)","title":"videoViewController(for:presentingFrom:)","defaultImplementations":1},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"abstract":[{"text":"Restrict access to premium content with custom paywall screens.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","role":"article","kind":"article","url":"\/documentation\/psreaderui\/paywall-integration","type":"topic","title":"Paywall Integration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"kind":"symbol","url":"\/documentation\/psreaderui","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"type":"topic","role":"collection"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/MediaDelegate":{"navigatorTitle":[{"text":"MediaDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines methods to provide custom media functionality."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaDelegate","kind":"identifier"}],"url":"\/documentation\/psreaderui\/mediadelegate","title":"MediaDelegate","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"],"anchor":"Features","title":"Features"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}