{"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"kind":"article","identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Migration-Guides","interfaceLanguage":"swift"},"abstract":[{"text":"Guidance to help you smoothly transition your app to newer versions of the SDK.","type":"text"},{"text":" ","type":"text"},{"text":"This page highlights breaking changes, necessary updates, and recommended","type":"text"},{"text":" ","type":"text"},{"text":"practices when migrating between versions.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/migration-guides"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/migration-guides"]}],"primaryContentSections":[{"content":[{"level":2,"text":"v26.1.0","type":"heading","anchor":"v2610"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Archive limit defaults"}]}]},{"type":"paragraph","inlineContent":[{"code":"archiveLimit","type":"codeVoice"},{"text":" now defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", with type-specific behavior:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Replica archives: 30 editions (unchanged from previous releases)."}]}]},{"content":[{"inlineContent":[{"text":"Feed archives: unbounded — shows the full backend archive (usually ~1 year).","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is a behavior change for feed edition clients who previously saw a default"},{"type":"text","text":" "},{"type":"text","text":"of 30 editions. To restore the old behavior, explicitly set "},{"type":"codeVoice","code":"archiveLimit"},{"type":"text","text":":"}]},{"syntax":"swift","code":["var archiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","archiveConfig.archiveLimit = 30"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Modern replica reader","type":"text"}],"type":"strong"}]},{"type":"paragraph","inlineContent":[{"text":"A modern replacement for the legacy replica reader is now available. It shares","type":"text"},{"text":" ","type":"text"},{"text":"delegates and navigation with the feed edition reader, giving end users the same","type":"text"},{"text":" ","type":"text"},{"text":"experience regardless of backend. Replica-specific analytics events still fire.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Opt in by setting "},{"type":"codeVoice","code":"useLegacyReplicaReader"},{"type":"text","text":" to "},{"type":"codeVoice","code":"false"},{"type":"text","text":" (defaults to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" for"},{"type":"text","text":" "},{"type":"text","text":"now). The modern reader will become the default in a future release, and the"},{"type":"text","text":" "},{"type":"text","text":"legacy reader will be removed further out."}]},{"syntax":"swift","code":["var archiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","archiveConfig.readerConfig.useLegacyReplicaReader = false"],"type":"codeListing"},{"name":"Important","style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"The legacy reader’s content browser next\/previous button events are","type":"text"},{"text":" ","type":"text"},{"text":"not reported in the modern reader:","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"replicaPageBrowserNextTapped"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"replicaPageBrowserPreviousTapped"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"replicaArticleBrowserNextTapped"},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"replicaArticleBrowserPreviousTapped"},{"text":".","type":"text"}]}]},{"name":"Note","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"LegacyReaderConfiguration"},{"type":"text","text":" properties (e.g. "},{"type":"codeVoice","code":"shareTemplater"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"codeVoice","code":"prefersStatusBarHidden"},{"type":"text","text":", "},{"type":"codeVoice","code":"navigationBarItems"},{"type":"text","text":") do not apply to the modern"},{"type":"text","text":" "},{"type":"text","text":"reader — it uses the standard "},{"type":"codeVoice","code":"ReaderConfiguration"},{"type":"text","text":" delegates instead."}]}]},{"level":2,"text":"v5.5.0","type":"heading","anchor":"v550"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Liquid Glass UI defaults","type":"text"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On iOS 26 and later, the SDK defaults to a new Liquid Glass design. The SDK"},{"type":"text","text":" "},{"type":"text","text":"respects the host app’s "},{"type":"codeVoice","code":"UIDesignRequiresCompatibility"},{"type":"text","text":" flag and will fall back"},{"type":"text","text":" "},{"type":"text","text":"automatically on older OS versions. The new design can also be controlled via"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"LiquidGlassPolicy"},{"type":"text","text":" option. You can apply this globally or more granularly"},{"type":"text","text":" "},{"type":"text","text":"on specific configuration objects (for example, subsection ribbon, navigation"},{"type":"text","text":" "},{"type":"text","text":"bar, page browser, etc.). To disable it globally:"}]},{"syntax":"swift","code":["var globalConfig = PSReaderUI.GlobalConfiguration(apiKey: apiKey, accountGUID: accountGUID)","globalConfig.liquidGlassPolicy = .disabled \/\/ disable Liquid Glass across the SDK"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Archive thumbnail layout","type":"text"}],"type":"strong"}]},{"type":"paragraph","inlineContent":[{"text":"Archive thumbnails now offer a dynamic layout mode:","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"ImageContentMode.flexibleHeight"},{"text":". It lets edition artwork (including the","type":"text"},{"text":" ","type":"text"},{"text":"latest\/hero card) grow or shrink to its true aspect ratio, keeping the full","type":"text"},{"text":" ","type":"text"},{"text":"image visible instead of cropping. Start with an estimated ratio for a steady","type":"text"},{"text":" ","type":"text"},{"text":"initial layout; the SDK tunes the size automatically once the real image","type":"text"},{"text":" ","type":"text"},{"text":"arrives. Example:","type":"text"}]},{"syntax":"swift","code":["var archiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","archiveConfig.thumbnailContentMode = .flexibleHeight(estimatedAspectRatio: 0.9)"],"type":"codeListing"},{"level":2,"text":"v5.2.0","type":"heading","anchor":"v520"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Reader UI\/UX Changes"}]}]},{"type":"paragraph","inlineContent":[{"text":"In PDF-driven editions, PDF pages and articles are now segmented. Users can no","type":"text"},{"text":" ","type":"text"},{"text":"longer swipe between them. Articles are accessed either via article hotspot","type":"text"},{"text":" ","type":"text"},{"text":"links or through the content browser. The content browser is also segmented in","type":"text"},{"text":" ","type":"text"},{"text":"the same way, with a toggle that allows switching between pages and articles.","type":"text"},{"text":" ","type":"text"},{"text":"This behavior now matches the web reader.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The navigation bar layout has also been updated:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"The right-side back arrow has been removed.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The left-side icon now adapts to the current context:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Dismiss Article – If the user opened an article from a hotspot link, this"},{"type":"text","text":" "},{"type":"text","text":"action returns them to the PDF page containing that article."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Dismiss Reader – In all other cases, this action dismisses the reader","type":"text"},{"text":" ","type":"text"},{"text":"view controller.","type":"text"}]}]}],"type":"unorderedList"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can customize the icons for these actions via your "},{"type":"codeVoice","code":"AssetDelegate"},{"type":"text","text":":"}]},{"syntax":"swift","code":["ImageResourceName.dismiss        \/\/ Default: back arrow","ImageResourceName.dismissArticle \/\/ Default: xmark"],"type":"codeListing"},{"level":2,"text":"v5.0.0","type":"heading","anchor":"v500"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Edition Download Behavior"}]}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"5.0.0"},{"text":" introduces the ability to read editions without downloading them.","type":"text"},{"text":" ","type":"text"},{"text":"This is the new default behavior. It can be customized by users via the reader","type":"text"},{"text":" ","type":"text"},{"text":"settings menu. To retain the original default:","type":"text"}]},{"syntax":"swift","code":["var archiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","archiveConfig.readerConfig.settings.downloadWhileReadingDefault = false","","\/\/ To hide the user facing setting","archiveConfig.readerConfig.settings.isDownloadWhileReadingToggleEnabled = false","archiveConfig.readerConfig.settings.isDownloadWhileReadingPreferenceAlertEnabled = false"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Edition Date Formatting"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Breaking Change: "},{"type":"codeVoice","code":"DateFormatter"},{"type":"text","text":" objects in configuration structs have been"},{"type":"text","text":" "},{"type":"text","text":"replaced with the "},{"type":"codeVoice","code":"EditionDateFormatter"},{"type":"text","text":" protocol. This enables more fine"},{"type":"text","text":" "},{"type":"text","text":"grained customization and allows for alternative naming strategies such as"},{"text":" ","type":"text"},{"text":"edition names, identifiers, or any other custom labeling approach.","type":"text"}]},{"inlineContent":[{"type":"text","text":"The SDK provides a "},{"type":"codeVoice","code":"DefaultEditionDateFormatter"},{"type":"text","text":" that wraps a"},{"type":"text","text":" "},{"type":"codeVoice","code":"DateFormatter"},{"type":"text","text":". This allows"}],"type":"paragraph"},{"code":["let dateFormatter = DateFormatter()","dateFormatter.dateFormat = \"d MMMM yyyy\"","dateFormatter.timeZone = .current","archiveConfig.dateFormatter = DefaultEditionDateFormatter(dateFormatter: dateFormatter)","","\/\/ Alternative initializer","archiveConfig.dateFormatter = DefaultEditionDateFormatter(dateFormat: \"d MMMM yyyy\", timeZone: .current)"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Asset Customization","type":"text"}]}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Breaking Change: The "},{"code":"imageResourceForName","type":"codeVoice"},{"type":"text","text":" callbacks have been removed. They"},{"type":"text","text":" "},{"type":"text","text":"have been replaced by "},{"code":"AssetDelegate","type":"codeVoice"},{"type":"text","text":". To migrate to the new system implement"},{"type":"text","text":" "},{"type":"text","text":"the delegate and set it as needed."}],"type":"paragraph"},{"code":["\/\/ Customize assets as desired","struct MyAssetDelegate: PSReaderUI.AssetDelegate {","    func imageResource(for name: ImageResourceName) -> UIImage? {","        return name.defaultImage()","    }","}","","var globalConfig = PSReaderUI.GlobalConfiguration(apiKey: apiKey, accountGUID: accountGUID)","globalConfig.assetDelegate = MyAssetDelegate()"],"syntax":null,"type":"codeListing"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"Migration Guides","roleHeading":"Article","role":"article","modules":[{"name":"PSReaderUI"}]},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log"],"anchor":"Release-Notes","generated":true,"title":"Release Notes"}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Change-Log":{"title":"Change Log","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log","kind":"article","abstract":[{"type":"text","text":"Track new features, improvements, bug fixes, and other updates in each"},{"type":"text","text":" "},{"type":"text","text":"PSReaderUI SDK release."}],"type":"topic","role":"article","url":"\/documentation\/psreaderui\/change-log"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"url":"\/documentation\/psreaderui","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log"],"anchor":"Release-Notes","title":"Release Notes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}