{"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"By default the PSReaderUI SDK does ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"not"}]},{"text":" restrict access to any content.","type":"text"},{"text":" ","type":"text"},{"text":"Paywalls are entirely opt-in: you implement the ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate","isActive":true,"type":"reference"},{"text":" protocol,","type":"text"},{"text":" ","type":"text"},{"text":"provide view controllers that conform to ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallViewController","isActive":true,"type":"reference"},{"text":", and assign","type":"text"},{"text":" ","type":"text"},{"text":"the delegate to your ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"heading","text":"How It Works","level":2,"anchor":"How-It-Works"},{"type":"paragraph","inlineContent":[{"text":"When a user attempts to open or download an edition, the SDK consults a","type":"text"},{"text":" ","type":"text"},{"text":"paywall delegate. When the SDK finds a delegate, the flow is:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"User taps an edition to open or download it."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The SDK calls the relevant ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate","type":"reference"},{"text":" method.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Your delegate returns a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallViewController"},{"type":"text","text":" (or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" to skip the paywall)."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK sets the "},{"type":"codeVoice","code":"onDismiss"},{"type":"text","text":" closure on your view controller and presents it "},{"type":"strong","inlineContent":[{"type":"text","text":"modally"}]},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"When the user finishes, your view controller calls ","type":"text"},{"code":"onDismiss(true)","type":"codeVoice"},{"text":" to","type":"text"},{"text":" ","type":"text"},{"text":"grant access or ","type":"text"},{"code":"onDismiss(false)","type":"codeVoice"},{"text":" to deny it.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK dismisses your view controller automatically — "},{"type":"strong","inlineContent":[{"type":"text","text":"do not"}]},{"type":"text","text":" dismiss it yourself."}]}]}]},{"type":"aside","content":[{"inlineContent":[{"text":"The SDK owns the presentation and dismissal lifecycle. Do not call","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"dismiss(animated:)"},{"text":" on the paywall view controller or its presenting","type":"text"},{"text":" ","type":"text"},{"text":"controller. Doing so may leave the SDK in an inconsistent state.","type":"text"}],"type":"paragraph"}],"name":"Important","style":"important"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate methods receive different model objects depending on the edition"},{"type":"text","text":" "},{"type":"text","text":"type. Knowing their properties helps you make informed paywall decisions."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"PSEdition","type":"codeVoice"},{"type":"text","text":" represents a replica (PDF) edition."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PSEPublished"},{"type":"text","text":" represents a feed edition."}]}]}]},{"type":"heading","text":"Creating a PaywallViewController","level":2,"anchor":"Creating-a-PaywallViewController"},{"type":"paragraph","inlineContent":[{"text":"Your paywall screen must conform to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallViewController","type":"reference"},{"text":". The protocol","type":"text"},{"text":" ","type":"text"},{"text":"requires a single property:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["import PSReaderUI","","class MyPaywallScreen: UIViewController, PSReaderUI.PaywallViewController {","    var onDismiss: ((Bool) -> Void)?","","    \/\/ Build your paywall UI...","","    @objc func userDidSubscribe() {","        onDismiss?(true) \/\/ Grant access","    }","","    @objc func userDidCancel() {","        onDismiss?(false) \/\/ Deny access","    }","}"]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Call "},{"type":"codeVoice","code":"onDismiss"},{"type":"text","text":" "},{"inlineContent":[{"type":"text","text":"exactly once"}],"type":"strong"},{"type":"text","text":" when the user completes or"},{"type":"text","text":" "},{"type":"text","text":"cancels the paywall flow. If you never call "},{"type":"codeVoice","code":"onDismiss"},{"type":"text","text":", the paywall remains"},{"type":"text","text":" "},{"type":"text","text":"on screen indefinitely. Calling it more than once may cause unexpected"},{"type":"text","text":" "},{"type":"text","text":"behavior."}],"type":"paragraph"}],"name":"Important","style":"important"},{"type":"heading","text":"Implementing PaywallDelegate","level":2,"anchor":"Implementing-PaywallDelegate"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate has four methods — two for opening editions and two for"},{"type":"text","text":" "},{"type":"text","text":"downloading them:"}]},{"type":"codeListing","syntax":"swift","code":["struct MyPaywallDelegate: PSReaderUI.PaywallDelegate {","","    func paywallViewControllerForAction(","        openReplicaEdition edition: PSEdition","    ) -> PaywallViewController? {","        return MyPaywallScreen()","    }","","    func paywallViewControllerForAction(","        openFeedEdition published: PSEPublished","    ) -> PaywallViewController? {","        return MyPaywallScreen()","    }","","    func paywallViewControllerForAction(","        downloadReplicaEdition edition: PSEdition","    ) -> PaywallViewController? {","        \/\/ Default implementation delegates to openReplicaEdition.","        return paywallViewControllerForAction(openReplicaEdition: edition)","    }","","    func paywallViewControllerForAction(","        downloadFeedEdition published: PSEPublished","    ) -> PaywallViewController? {","        \/\/ Default implementation delegates to openFeedEdition.","        return paywallViewControllerForAction(openFeedEdition: published)","    }","}"]},{"type":"aside","content":[{"inlineContent":[{"text":"The download methods have default implementations that delegate to the","type":"text"},{"text":" ","type":"text"},{"text":"corresponding open methods. You only need to override them if your paywall","type":"text"},{"text":" ","type":"text"},{"text":"logic differs between opening and downloading.","type":"text"}],"type":"paragraph"}],"name":"Tip","style":"tip"},{"type":"paragraph","inlineContent":[{"text":"Note that separate methods exist for replica and feed editions. See","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","type":"reference"},{"text":" for background on the two systems.","type":"text"}]},{"type":"heading","text":"Conditional Paywalls","level":3,"anchor":"Conditional-Paywalls"},{"type":"paragraph","inlineContent":[{"text":"Return ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" from any delegate method to skip the paywall for that edition.","type":"text"},{"text":" ","type":"text"},{"text":"This lets you implement conditional access logic:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["struct MyPaywallDelegate: PSReaderUI.PaywallDelegate {","","    let userIsSubscribed: Bool","","    func paywallViewControllerForAction(","        openFeedEdition published: PSEPublished","    ) -> PaywallViewController? {","        \/\/ No paywall for subscribers","        if userIsSubscribed { return nil }","","        \/\/ No paywall for supplements","        if published.isSupplement { return nil }","","        return MyPaywallScreen()","    }","","    func paywallViewControllerForAction(","        openReplicaEdition edition: PSEdition","    ) -> PaywallViewController? {","        if userIsSubscribed { return nil }","        return MyPaywallScreen()","    }","}"]},{"type":"heading","text":"Assigning the Delegate","level":2,"anchor":"Assigning-the-Delegate"},{"type":"heading","text":"Global Level","level":3,"anchor":"Global-Level"},{"type":"paragraph","inlineContent":[{"text":"Set the delegate on your ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration"},{"text":" to apply it across the entire","type":"text"},{"text":" ","type":"text"},{"text":"SDK. For most use cases, this is all you need.","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["var globalConfig = PSReaderUI.GlobalConfiguration(","    apiKey: apiKey,","    accountGUID: accountGUID",")","globalConfig.paywallDelegate = MyPaywallDelegate()"]},{"type":"heading","text":"Carousel Level","level":3,"anchor":"Carousel-Level"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set the delegate on a "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselConfiguration","type":"reference","isActive":true},{"type":"text","text":" to override the global delegate"},{"type":"text","text":" "},{"type":"text","text":"for all sections within a specific carousel:"}]},{"type":"codeListing","syntax":"swift","code":["var carouselConfig = PSReaderUI.CarouselConfiguration(globalConfig: globalConfig)","carouselConfig.paywallDelegate = MyCarouselPaywallDelegate()"]},{"type":"heading","text":"Per-Section Level","level":3,"anchor":"Per-Section-Level"},{"type":"paragraph","inlineContent":[{"text":"Set the delegate on an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration"},{"text":" to override the paywall for a","type":"text"},{"text":" ","type":"text"},{"text":"single section. This is useful when different publications within the same","type":"text"},{"text":" ","type":"text"},{"text":"carousel have different access rules:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["var premiumArchiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","premiumArchiveConfig.paywallDelegate = PremiumPaywallDelegate()","","let sections: [PSReaderUI.CarouselViewController.SectionItem] = [","    \/\/ This section uses the per-section paywall","    .section(.init(","        name: \"Premium\",","        type: .feedArchive(guid: \"PREMIUM_GUID\", config: premiumArchiveConfig)","    )),","    \/\/ This section falls back to the global or carousel paywall","    .section(.init(","        name: \"Free\",","        type: .feedArchive(guid: \"FREE_GUID\")","    ))","]"]},{"type":"heading","text":"Open vs Download Paywalls","level":2,"anchor":"Open-vs-Download-Paywalls"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In most cases the same paywall applies to both actions. However, some"},{"type":"text","text":" "},{"type":"text","text":"publishers may want to allow free streaming while requiring a subscription to"},{"type":"text","text":" "},{"type":"text","text":"download."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The download delegate methods have default implementations that call through to"},{"type":"text","text":" "},{"type":"text","text":"the corresponding open methods. Override them to differentiate:"}]},{"type":"codeListing","syntax":"swift","code":["struct StreamingPaywallDelegate: PSReaderUI.PaywallDelegate {","","    func paywallViewControllerForAction(","        openReplicaEdition edition: PSEdition","    ) -> PaywallViewController? {","        \/\/ Free to open and read (streaming)","        return nil","    }","","    func paywallViewControllerForAction(","        openFeedEdition published: PSEPublished","    ) -> PaywallViewController? {","        return nil","    }","","    func paywallViewControllerForAction(","        downloadReplicaEdition edition: PSEdition","    ) -> PaywallViewController? {","        \/\/ Require subscription for offline downloads","        return MyPaywallScreen()","    }","","    func paywallViewControllerForAction(","        downloadFeedEdition published: PSEPublished","    ) -> PaywallViewController? {","        return MyPaywallScreen()","    }","}"]},{"type":"heading","text":"Troubleshooting","level":2,"anchor":"Troubleshooting"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Paywall never dismisses","type":"text"}]},{"text":" ","type":"text"},{"text":"Your ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallViewController","isActive":true,"type":"reference"},{"text":" must call ","type":"text"},{"code":"onDismiss","type":"codeVoice"},{"text":" at some point. If the user","type":"text"},{"text":" ","type":"text"},{"text":"cancels, call ","type":"text"},{"code":"onDismiss(false)","type":"codeVoice"},{"text":". If you never invoke the closure, the SDK has","type":"text"},{"text":" ","type":"text"},{"text":"no signal to dismiss the view controller and it remains on screen.","type":"text"}]},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Wrong paywall appears for a section","type":"text"}],"type":"strong"},{"type":"text","text":" "},{"type":"text","text":"Check the delegate cascade. A per-section delegate on "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"takes priority over the carousel and global delegates. Verify which level your"},{"type":"text","text":" "},{"type":"text","text":"delegate is assigned to and whether a more specific override exists."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Download always shows a paywall even though open is free","type":"text"}]},{"text":" ","type":"text"},{"text":"The default download methods delegate to the open methods. If your open method","type":"text"},{"text":" ","type":"text"},{"text":"returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" but downloads still show a paywall, you may have a separate","type":"text"},{"text":" ","type":"text"},{"text":"delegate assigned at a different cascade level that overrides the download","type":"text"},{"text":" ","type":"text"},{"text":"methods. Check all three levels.","type":"text"}]},{"type":"heading","text":"Complete Example","level":2,"anchor":"Complete-Example"},{"type":"paragraph","inlineContent":[{"text":"An end-to-end integration tying everything together:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["import PSReaderUI","","\/\/ 1. Create a paywall view controller","class SubscriptionPaywall: UIViewController, PSReaderUI.PaywallViewController {","    var onDismiss: ((Bool) -> Void)?","","    override func viewDidLoad() {","        super.viewDidLoad()","        \/\/ Set up your subscription UI...","    }","","    @objc func subscribe() {","        \/\/ Handle subscription logic, then grant access","        onDismiss?(true)","    }","","    @objc func cancel() {","        onDismiss?(false)","    }","}","","\/\/ 2. Implement the delegate","struct AppPaywallDelegate: PSReaderUI.PaywallDelegate {","","    let subscriptionManager: SubscriptionManager","","    func paywallViewControllerForAction(","        openReplicaEdition edition: PSEdition","    ) -> PaywallViewController? {","        guard !subscriptionManager.isSubscribed else { return nil }","        return SubscriptionPaywall()","    }","","    func paywallViewControllerForAction(","        openFeedEdition published: PSEPublished","    ) -> PaywallViewController? {","        guard !subscriptionManager.isSubscribed else { return nil }","        if published.isSupplement { return nil }","        return SubscriptionPaywall()","    }","}","","\/\/ 3. Assign to the global configuration","var globalConfig = PSReaderUI.GlobalConfiguration(","    apiKey: \"YOUR_API_KEY\",","    accountGUID: \"YOUR_ACCOUNT_GUID\"",")","globalConfig.paywallDelegate = AppPaywallDelegate(","    subscriptionManager: mySubscriptionManager",")","","\/\/ 4. Create and present the carousel","let carouselVC = PSReaderUI.CarouselViewController(","    globalConfig: globalConfig,","    sections: [","        .dynamicArchive(\"Editions\", shortcode: \"SHORTCODE\")","    ]",")"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/paywall-integration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/paywall-integration"]}],"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","interfaceLanguage":"swift"},"metadata":{"title":"Paywall Integration","roleHeading":"Article","role":"article","modules":[{"name":"PSReaderUI"}]},"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"sections":[],"abstract":[{"type":"text","text":"Restrict access to premium content with custom paywall screens."}],"kind":"article","seeAlsoSections":[{"anchor":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"title":"Features","generated":true}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"abstract":[{"type":"text","text":"Track user interactions and content engagement across the PSReaderUI SDK."}],"role":"article","kind":"article","url":"\/documentation\/psreaderui\/analytics","title":"Analytics","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselConfiguration":{"abstract":[{"type":"text","text":"Configuration object for customizing the PSReaderUI carousel interface."}],"navigatorTitle":[{"text":"CarouselConfiguration","kind":"identifier"}],"url":"\/documentation\/psreaderui\/carouselconfiguration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselConfiguration","title":"CarouselConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CarouselConfiguration","kind":"identifier"}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/PaywallDelegate":{"navigatorTitle":[{"kind":"identifier","text":"PaywallDelegate"}],"type":"topic","abstract":[{"text":"A delegate protocol used to provide paywall view controllers for controlling","type":"text"},{"text":" ","type":"text"},{"text":"access to premium content within the SDK.","type":"text"}],"kind":"symbol","url":"\/documentation\/psreaderui\/paywalldelegate","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaywallDelegate"}],"title":"PaywallDelegate"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Replica-and-Feed-Editions":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","title":"Replica and Feed Editions","kind":"article","type":"topic","role":"article","abstract":[{"text":"Understand the two backend systems that power PSReaderUI content.","type":"text"}],"url":"\/documentation\/psreaderui\/replica-and-feed-editions"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/PaywallViewController":{"kind":"symbol","abstract":[{"type":"text","text":"A view controller protocol used by the SDK to present paywalls when"},{"type":"text","text":" "},{"type":"text","text":"accessing restricted content."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaywallViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PaywallViewController","kind":"identifier"}],"url":"\/documentation\/psreaderui\/paywallviewcontroller","type":"topic","title":"PaywallViewController","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallViewController"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveConfiguration":{"title":"ArchiveConfiguration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","abstract":[{"type":"text","text":"Configuration for customizing the appearance and behavior of publication archive views."}],"url":"\/documentation\/psreaderui\/archiveconfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArchiveConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ArchiveConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"type":"topic","abstract":[{"text":"A UI framework for building digital newspaper and magazine reader experiences on iOS.","type":"text"}],"url":"\/documentation\/psreaderui","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","title":"PSReaderUI","role":"collection","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"title":"GlobalConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlobalConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GlobalConfiguration","kind":"identifier"}],"url":"\/documentation\/psreaderui\/globalconfiguration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","abstract":[{"type":"text","text":"A configuration object that provides global settings and delegates for"},{"type":"text","text":" "},{"type":"text","text":"customizing the SDK’s behavior and appearance."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"url":"\/documentation\/psreaderui\/sharing","kind":"article","title":"Sharing","abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"role":"article","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"kind":"article","url":"\/documentation\/psreaderui\/advertisements","type":"topic","abstract":[{"type":"text","text":"Display custom advertisements within the reader."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","title":"Advertisements","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"type":"topic","role":"article","title":"Media Playback","url":"\/documentation\/psreaderui\/media-playback","kind":"article","abstract":[{"type":"text","text":"Enable video and media playback within the reader."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"role":"article","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","abstract":[{"text":"Add audio playback of article content using the SDK’s text-to-speech system.","type":"text"}],"type":"topic","title":"Text-to-Speech","url":"\/documentation\/psreaderui\/text-to-speech"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"anchor":"Features","title":"Features","generated":true,"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"]}],"path":"\/seeAlsoSections"}]}]}