{"metadata":{"modules":[{"name":"PSReaderUI"}],"role":"article","title":"Search","roleHeading":"Article"},"abstract":[{"text":"Search across feed edition content for articles and pages.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"anchor":"Features"}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"inlineContent":[{"text":"The SDK includes a full-text search feature powered by the PageSuite search","type":"text"},{"text":" ","type":"text"},{"text":"API. Users can search across one or more feed edition publications and filter","type":"text"},{"text":" ","type":"text"},{"text":"results by type — articles, pages, or both.","type":"text"}],"type":"paragraph"},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"text":"Search is available for feed editions only. Replica (PDF-only) editions","type":"text"},{"text":" ","type":"text"},{"text":"are not supported by the search API. See ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","type":"reference","isActive":true},{"text":" to","type":"text"},{"text":" ","type":"text"},{"text":"determine which system your publications use.","type":"text"}],"type":"paragraph"}]},{"inlineContent":[{"text":"There are three ways to integrate search:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Carousel tab"}],"type":"strong"},{"text":" — add a ","type":"text"},{"code":".search","type":"codeVoice"},{"text":" content type to the carousel.","type":"text"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Standalone view controller","type":"text"}],"type":"strong"},{"type":"text","text":" — use "},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchViewController","type":"reference"},{"type":"text","text":" outside the carousel."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Search service"}],"type":"strong"},{"type":"text","text":" — use "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchService","type":"reference","isActive":true},{"type":"text","text":" directly to build a fully custom search UI."}],"type":"paragraph"}]}]},{"level":2,"anchor":"Adding-Search-to-the-Carousel","type":"heading","text":"Adding Search to the Carousel"},{"inlineContent":[{"text":"Add a search tab to the carousel using the ","type":"text"},{"code":".search(config:)","type":"codeVoice"},{"text":" content type.","type":"text"},{"text":" ","type":"text"},{"text":"When using a dynamic archive, the carousel provides a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate"},{"text":" ","type":"text"},{"text":"automatically — no additional setup is needed:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let carouselVC = PSReaderUI.CarouselViewController(","    globalConfig: globalConfig,","    sections: [","        .dynamicArchive(\"Editions\", shortcode: \"SHORTCODE\"),","        .subsections(\"More\", [","            .init(name: \"Bookmarks\", type: .bookmarks(type: .all)),","            .init(name: \"Search\", type: .search(config: searchConfig))","        ])","    ]",")"]},{"inlineContent":[{"type":"text","text":"When using manual sections, you must set a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate"},{"type":"text","text":" on the"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["var searchConfig = PSReaderUI.SearchConfiguration(globalConfig: globalConfig)","searchConfig.searchDelegate = PSReaderUI.ApplicationSearchDelegate(","    shortcode: \"SHORTCODE\",","    readerConfig: readerConfig",")","","let carouselVC = PSReaderUI.CarouselViewController(","    globalConfig: globalConfig,","    sections: [","        .section(.init(name: \"Daily\", type: .feedArchive(guid: \"APP_GUID\"))),","        .section(.init(name: \"Search\", type: .search(config: searchConfig)))","    ]",")"]},{"level":2,"anchor":"Standalone-Search-View-Controller","type":"heading","text":"Standalone Search View Controller"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchViewController"},{"type":"text","text":" presents search outside of the carousel. It requires"},{"type":"text","text":" "},{"type":"text","text":"a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate"},{"type":"text","text":" to provide the list of searchable publications and their"},{"type":"text","text":" "},{"type":"text","text":"reader configurations. Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ApplicationSearchDelegate"},{"type":"text","text":" for a ready-made"},{"type":"text","text":" "},{"type":"text","text":"implementation:"}]},{"syntax":"swift","type":"codeListing","code":["\/\/ From a shortcode (fetches application config lazily on first search)","let delegate = PSReaderUI.ApplicationSearchDelegate(","    shortcode: \"SHORTCODE\",","    readerConfig: readerConfig",")","","let searchVC = PSReaderUI.SearchViewController(","    globalConfig: globalConfig,","    delegate: delegate",")","","navigationController?.pushViewController(searchVC, animated: true)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For modal presentation, set "},{"type":"codeVoice","code":"dismissible"},{"type":"text","text":" to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to show a close button:"}]},{"syntax":"swift","type":"codeListing","code":["let searchVC = PSReaderUI.SearchViewController(","    globalConfig: globalConfig,","    delegate: delegate,","    dismissible: true",")","","present(searchVC, animated: true)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you already have a "},{"type":"codeVoice","code":"PSEApplication"},{"type":"text","text":" object, you can create the delegate"},{"type":"text","text":" "},{"type":"text","text":"from it directly:"}]},{"syntax":"swift","type":"codeListing","code":["let delegate = PSReaderUI.ApplicationSearchDelegate(","    application: myApplication,","    readerConfig: readerConfig",")"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","isActive":true},{"type":"text","text":" for common patterns like interface style"},{"type":"text","text":" "},{"type":"text","text":"overrides."}]},{"anchor":"In-Reader-Search","level":2,"text":"In-Reader Search","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration\/search","isActive":true},{"type":"text","text":" is set with a non-nil"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration\/searchDelegate","isActive":true},{"type":"text","text":", a search option appears in the reader’s"},{"type":"text","text":" "},{"type":"text","text":"settings menu."}]},{"type":"paragraph","inlineContent":[{"text":"In carousel-based setups this is configured automatically — the carousel","type":"text"},{"text":" ","type":"text"},{"text":"provides a default ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate","type":"reference"},{"text":" if one is not set. For standalone view","type":"text"},{"text":" ","type":"text"},{"text":"controllers (","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController","type":"reference"},{"text":", ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController","type":"reference"},{"text":",","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","type":"reference"},{"text":"), set the delegate explicitly:","type":"text"}]},{"code":["var readerConfig = PSReaderUI.ReaderConfiguration(globalConfig: globalConfig)","readerConfig.search?.searchDelegate = PSReaderUI.ApplicationSearchDelegate(","    shortcode: \"SHORTCODE\",","    readerConfig: readerConfig",")","","var archiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","archiveConfig.readerConfig = readerConfig"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"Set ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration\/search","isActive":true,"type":"reference"},{"text":" to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" to disable search in the reader","type":"text"},{"text":" ","type":"text"},{"text":"entirely.","type":"text"}],"type":"paragraph"},{"anchor":"Search-Service","type":"heading","level":2,"text":"Search Service"},{"inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchService","isActive":true,"type":"reference"},{"text":" provides direct access to the PageSuite search API for","type":"text"},{"text":" ","type":"text"},{"text":"building fully custom search experiences.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Each publication must be paired with a ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchPublicationType","type":"reference","isActive":true},{"text":" — either","type":"text"},{"text":" ","type":"text"},{"code":".app","type":"codeVoice"},{"text":" or ","type":"text"},{"code":".publication","type":"codeVoice"},{"text":". Despite the confusing names, there is no functional","type":"text"},{"text":" ","type":"text"},{"text":"difference between the two; they simply reflect how the publication is indexed","type":"text"},{"text":" ","type":"text"},{"text":"on the backend. Passing the wrong type will cause search to return no results.","type":"text"},{"text":" ","type":"text"},{"text":"You can find the correct type in your application configuration — the carousel","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ApplicationSearchDelegate","type":"reference","isActive":true},{"text":" resolve this automatically.","type":"text"}],"type":"paragraph"},{"code":["let service = PSReaderUI.SearchService()","","service.search(","    accountGuid: \"ACCOUNT_GUID\",","    query: \"election results\",","    type: .all,","    publications: [","        (.app, \"APP_GUID_1\"),","        (.publication, \"PUB_GUID_2\")","    ],","    offset: 0,","    limit: 20,","    timeZone: .current",") { result in","    switch result {","    case .success(let response):","        let totalCount = response.meta?.totalCount ?? 0","        let results = response.data ?? []","","        for item in results {","            print(item.headline ?? \"Untitled\")","            print(item.snippet ?? \"\")","        }","","    case .failure(let error):","        print(error)","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"Each ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult","type":"reference"},{"text":" includes:","type":"text"}],"type":"paragraph"},{"header":"row","type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Property"}]}],[{"type":"paragraph","inlineContent":[{"text":"Description","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"type"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"\"EDITION_ARTICLE\""},{"text":" or ","type":"text"},{"type":"codeVoice","code":"\"EDITION_PAGE\""},{"text":".","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"editionId"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"The GUID of the edition containing the result."}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pageId"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"The GUID of the specific page."}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"applicationId"}]}],[{"type":"paragraph","inlineContent":[{"text":"The application GUID (publication identifier).","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"headline"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Article headline (articles only)."}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"section"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Section name (articles only)."}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pageNumber"}]}],[{"type":"paragraph","inlineContent":[{"text":"Page number (pages only).","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"snippet","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"Text excerpt with ","type":"text"},{"code":"<b>","type":"codeVoice"},{"text":" tags around matching terms.","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"images"}]}],[{"type":"paragraph","inlineContent":[{"text":"Array of associated images with URLs and captions.","type":"text"}]}]]]},{"inlineContent":[{"type":"text","text":"Use "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult\/formattedSnippet(font:)","isActive":true},{"type":"text","text":" to convert the snippet into an"},{"type":"text","text":" "},{"type":"codeVoice","code":"NSAttributedString"},{"type":"text","text":" with bold highlights:"}],"type":"paragraph"},{"code":["let attributedSnippet = result.formattedSnippet(font: .systemFont(ofSize: 14))"],"type":"codeListing","syntax":"swift"},{"anchor":"Opening-Search-Results","type":"heading","level":2,"text":"Opening Search Results"},{"inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","isActive":true,"type":"reference"},{"text":" to open an edition from a ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Map the result’s identifiers to the reader’s initializer parameters:","type":"text"}],"type":"paragraph"},{"code":["guard let editionGUID = result.editionId,","      let publicationGUID = result.applicationId else {","    return","}","","let reader = PSReaderUI.FeedReaderViewController(","    globalConfig: globalConfig,","    publicationGUID: publicationGUID,","    editionGUID: editionGUID,","    openingPage: result.pageId.map { .page(guid: $0) }",")","","present(reader, animated: true)"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"See "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","type":"reference","isActive":true},{"type":"text","text":" for more on presenting the reader directly."}],"type":"paragraph"},{"anchor":"Paywall-Integration","type":"heading","level":2,"text":"Paywall Integration"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate"},{"text":" includes a method for gating access to search results:","type":"text"}],"type":"paragraph"},{"code":["func paywallViewControllerForAction(","    openSearchResult result: SearchResult",") -> PaywallViewController? {","    \/\/ Use result.editionId, result.applicationId, etc. to decide","    guard !userIsSubscribed else { return nil }","    return MyPaywallScreen()","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"The default implementation returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" (no paywall). Override it to restrict"},{"type":"text","text":" "},{"type":"text","text":"access. The "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult","isActive":true},{"type":"text","text":" provides edition, publication, and application"},{"type":"text","text":" "},{"type":"text","text":"identifiers that you can use to make access decisions."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration"},{"type":"text","text":" for the full paywall setup guide."}],"type":"paragraph"},{"anchor":"Analytics","type":"heading","level":2,"text":"Analytics"},{"inlineContent":[{"type":"text","text":"The SDK fires two analytics events for search interactions:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"searchCompleted"},{"text":" — when a search query returns results (initial search only, not pagination).","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"searchResultTapped"},{"type":"text","text":" — when a user taps a search result."}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Both events carry a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/SearchEventContext"},{"type":"text","text":" with the query, filter"},{"type":"text","text":" "},{"type":"text","text":"type, result count, and searched publications. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"},{"type":"text","text":" for the"},{"type":"text","text":" "},{"type":"text","text":"general analytics setup guide."}],"type":"paragraph"},{"anchor":"Customizing-Appearance","type":"heading","level":2,"text":"Customizing Appearance"},{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration"},{"type":"text","text":" controls the visual appearance of the search UI,"},{"type":"text","text":" "},{"type":"text","text":"including background colors, filter pill styling, and result label fonts. Create"},{"type":"text","text":" "},{"type":"text","text":"one from your "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration"},{"type":"text","text":" and override individual properties:"}],"type":"paragraph"},{"code":["var searchConfig = PSReaderUI.SearchConfiguration(globalConfig: globalConfig)","searchConfig.backgroundColor = .systemBackground","searchConfig.selectedPillBackgroundColor = .systemBlue"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","isActive":true,"type":"reference"},{"text":" for the SDK’s general theming system.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/search"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/search"]}],"sections":[],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchResult/snippet":{"role":"symbol","title":"snippet","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult\/snippet","url":"\/documentation\/psreaderui\/searchresult\/snippet","abstract":[{"type":"text","text":"A text snippet with "},{"type":"codeVoice","code":"<b>"},{"type":"text","text":" tags highlighting matched terms."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"snippet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderConfiguration/search":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"search"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchConfiguration","preciseIdentifier":"s:10PSReaderUI19SearchConfigurationV"},{"kind":"text","text":"?"}],"title":"search","url":"\/documentation\/psreaderui\/readerconfiguration\/search","abstract":[{"text":"Optional search configuration enabling in-reader search.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration\/search","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GlobalConfiguration","kind":"identifier"}],"title":"GlobalConfiguration","navigatorTitle":[{"text":"GlobalConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"A configuration object that provides global settings and delegates for","type":"text"},{"text":" ","type":"text"},{"text":"customizing the SDK’s behavior and appearance.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","kind":"symbol","url":"\/documentation\/psreaderui\/globalconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Deep-Linking":{"title":"Deep Linking","role":"article","url":"\/documentation\/psreaderui\/deep-linking","type":"topic","abstract":[{"text":"Open a specific feed edition directly, bypassing the archive screen.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","kind":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchConfiguration/searchDelegate":{"abstract":[{"type":"text","text":"The delegate that provides searchable publications and reader configurations."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration\/searchDelegate","kind":"symbol","role":"symbol","title":"searchDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SearchDelegate","preciseIdentifier":"s:10PSReaderUI14SearchDelegateP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/psreaderui\/searchconfiguration\/searchdelegate","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/PaywallDelegate":{"abstract":[{"type":"text","text":"A delegate protocol used to provide paywall view controllers for controlling"},{"type":"text","text":" "},{"type":"text","text":"access to premium content within the SDK."}],"kind":"symbol","type":"topic","title":"PaywallDelegate","url":"\/documentation\/psreaderui\/paywalldelegate","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaywallDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PaywallDelegate"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Replica-and-Feed-Editions":{"abstract":[{"text":"Understand the two backend systems that power PSReaderUI content.","type":"text"}],"type":"topic","title":"Replica and Feed Editions","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","kind":"article","url":"\/documentation\/psreaderui\/replica-and-feed-editions"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"role":"article","title":"Analytics","type":"topic","abstract":[{"text":"Track user interactions and content engagement across the PSReaderUI SDK.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","kind":"article","url":"\/documentation\/psreaderui\/analytics"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/FeedReaderViewController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedReaderViewController"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/FeedReaderViewController","type":"topic","url":"\/documentation\/psreaderui\/feedreaderviewcontroller","navigatorTitle":[{"kind":"identifier","text":"FeedReaderViewController"}],"abstract":[{"type":"text","text":"A standalone view controller for displaying feed edition content."}],"title":"FeedReaderViewController","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"role":"article","url":"\/documentation\/psreaderui\/media-playback","abstract":[{"type":"text","text":"Enable video and media playback within the reader."}],"kind":"article","title":"Media Playback","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Theming-and-Customization":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","title":"Theming and Customization","abstract":[{"type":"text","text":"Adjust fonts, colors, icons, and layouts to match your app’s brand."}],"role":"article","url":"\/documentation\/psreaderui\/theming-and-customization","kind":"article","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchPublicationType":{"navigatorTitle":[{"kind":"identifier","text":"SearchPublicationType"}],"abstract":[{"type":"text","text":"The type of a searchable feed edition publication."}],"kind":"symbol","title":"SearchPublicationType","url":"\/documentation\/psreaderui\/searchpublicationtype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchPublicationType"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchPublicationType"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"kind":"symbol","url":"\/documentation\/psreaderui","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"type":"topic","role":"collection"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchViewController":{"abstract":[{"type":"text","text":"A standalone view controller for searching feed edition content."}],"title":"SearchViewController","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchViewController","url":"\/documentation\/psreaderui\/searchviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchViewController"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SearchViewController"}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"url":"\/documentation\/psreaderui\/sharing","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","role":"article","abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"type":"topic","title":"Sharing"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"abstract":[{"text":"Restrict access to premium content with custom paywall screens.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","role":"article","kind":"article","url":"\/documentation\/psreaderui\/paywall-integration","type":"topic","title":"Paywall Integration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventChannel/SearchEventContext":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchEventContext","kind":"identifier"}],"navigatorTitle":[{"text":"SearchEventContext","kind":"identifier"}],"title":"EventChannel.SearchEventContext","abstract":[{"type":"text","text":"Context object for search events."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel\/SearchEventContext","kind":"symbol","url":"\/documentation\/psreaderui\/eventchannel\/searcheventcontext","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchResult":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchResult"}],"type":"topic","title":"SearchResult","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult","kind":"symbol","abstract":[{"type":"text","text":"A single search result returned by the PageSuite search API."}],"navigatorTitle":[{"kind":"identifier","text":"SearchResult"}],"url":"\/documentation\/psreaderui\/searchresult"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/BookmarksViewController":{"url":"\/documentation\/psreaderui\/bookmarksviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BookmarksViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BookmarksViewController"}],"abstract":[{"type":"text","text":"A standalone view controller for displaying bookmarked pages and articles."}],"kind":"symbol","type":"topic","title":"BookmarksViewController","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchService":{"type":"topic","navigatorTitle":[{"text":"SearchService","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchService","kind":"symbol","url":"\/documentation\/psreaderui\/searchservice","role":"symbol","abstract":[{"text":"A service for searching PageSuite feed edition content.","type":"text"}],"title":"SearchService","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchService","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ApplicationSearchDelegate":{"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ApplicationSearchDelegate","url":"\/documentation\/psreaderui\/applicationsearchdelegate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApplicationSearchDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"ApplicationSearchDelegate","kind":"identifier"}],"title":"ApplicationSearchDelegate","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate","type":"reference","isActive":true},{"type":"text","text":" that derives search publications from a "},{"code":"PSEApplication","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"or fetches one lazily from a shortcode."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchDelegate":{"navigatorTitle":[{"text":"SearchDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A delegate that provides the list of searchable publications and their reader configurations.","type":"text"}],"title":"SearchDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate","url":"\/documentation\/psreaderui\/searchdelegate","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DownloadsViewController":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController","url":"\/documentation\/psreaderui\/downloadsviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadsViewController"}],"navigatorTitle":[{"kind":"identifier","text":"DownloadsViewController"}],"abstract":[{"type":"text","text":"A standalone view controller for displaying downloaded editions."}],"title":"DownloadsViewController","type":"topic","kind":"symbol","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"abstract":[{"text":"Display custom advertisements within the reader.","type":"text"}],"url":"\/documentation\/psreaderui\/advertisements","role":"article","title":"Advertisements","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","kind":"article","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Commenting":{"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","abstract":[{"text":"Add comment counts, comment buttons, and commenting integration to the reader.","type":"text"}],"role":"article","kind":"article","title":"Commenting","url":"\/documentation\/psreaderui\/commenting"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchConfiguration":{"url":"\/documentation\/psreaderui\/searchconfiguration","kind":"symbol","abstract":[{"text":"Configuration for the SDK’s built-in search interface.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SearchConfiguration","kind":"identifier"}],"title":"SearchConfiguration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchResult/formattedSnippet(font:)":{"url":"\/documentation\/psreaderui\/searchresult\/formattedsnippet(font:)","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult\/formattedSnippet(font:)","abstract":[{"type":"text","text":"Returns the "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchResult\/snippet","isActive":true},{"type":"text","text":" as an attributed string with matched terms in bold."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formattedSnippet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"kind":"text","text":"?"}],"title":"formattedSnippet(font:)","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Standalone-View-Controllers":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","kind":"article","url":"\/documentation\/psreaderui\/standalone-view-controllers","abstract":[{"text":"Use archive, bookmarks, downloads, and search views outside of the carousel.","type":"text"}],"role":"article","title":"Standalone View Controllers","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","kind":"article","role":"article","url":"\/documentation\/psreaderui\/text-to-speech","type":"topic","abstract":[{"text":"Add audio playback of article content using the SDK’s text-to-speech system.","type":"text"}],"title":"Text-to-Speech"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Deep-Linking","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Commenting","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"title":"Features","generated":true}]}]}]}