{"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"PSReaderUI"}],"title":"Sharing"},"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"primaryContentSections":[{"content":[{"text":"Overview","level":2,"anchor":"Overview","type":"heading"},{"inlineContent":[{"text":"The PSReaderUI SDK provides built-in sharing through the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate"},{"text":" ","type":"text"},{"text":"protocol. The SDK ships three ready-to-use providers — ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareProvider"},{"text":",","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/WebReaderShareProvider"},{"text":", and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArticleLinkShareProvider"},{"text":" — that cover the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"most common scenarios. For full control, implement "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate"},{"type":"text","text":" directly."}],"type":"paragraph"},{"text":"Key Concepts","level":2,"anchor":"Key-Concepts","type":"heading"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Web reader link"}]},{"type":"text","text":" — a URL that opens the edition page in the PageSuite web"},{"type":"text","text":" "},{"type":"text","text":"reader (e.g., "},{"code":"reader.pagesuite.com\/shortcode\/CODE\/edition\/GUID","type":"codeVoice"},{"type":"text","text":"). This lets"},{"type":"text","text":" "},{"type":"text","text":"anyone view the page in a browser without installing the app."}],"type":"paragraph"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Article link"}],"type":"strong"},{"text":" — a URL pointing to the article on the publisher’s own website","type":"text"},{"text":" ","type":"text"},{"text":"(e.g., ","type":"text"},{"code":"example.com\/news\/article-slug","type":"codeVoice"},{"text":"). This link is set by the publisher in","type":"text"},{"text":" ","type":"text"},{"text":"the CMS and is only available for article-type pages that have a ","type":"text"},{"code":"shareLink","type":"codeVoice"},{"text":" ","type":"text"},{"text":"configured.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Both link types are surfaced through the iOS share sheet"},{"type":"text","text":" "},{"type":"text","text":"("},{"type":"codeVoice","code":"UIActivityViewController"},{"type":"text","text":"). The built-in providers automatically include a"},{"type":"text","text":" "},{"inlineContent":[{"type":"text","text":"Copy Link"}],"type":"strong"},{"type":"text","text":" activity alongside the standard system activities."}],"type":"paragraph"},{"text":"Choosing a Share Policy","level":2,"anchor":"Choosing-a-Share-Policy","type":"heading"},{"inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareProvider","isActive":true,"type":"reference"},{"text":" wraps one or both of the built-in providers and applies a","type":"text"},{"text":" ","type":"text"},{"text":"fallback strategy through its ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareProvider\/SharePolicy","isActive":true,"type":"reference"},{"text":" enum:","type":"text"}],"type":"paragraph"},{"rows":[[[{"type":"paragraph","inlineContent":[{"text":"Policy","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"When to use"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"What’s shareable"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".disabled"}],"type":"paragraph"}],[{"inlineContent":[{"text":"You don’t want any sharing","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Nothing","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".onlyWebReader","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"text":"All pages should share a web reader link","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Any page with a page GUID","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".onlyArticleLink","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Only article pages with a CMS link should be shareable","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Article pages with a non-empty ","type":"text"},{"code":"shareLink","type":"codeVoice"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".preferWebReader"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Web reader link preferred, article link as fallback"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Most pages via web reader; article pages also eligible"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":".preferArticleLink"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Article link preferred, web reader as fallback"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Article pages via CMS link; all other pages via web reader"}],"type":"paragraph"}]]],"header":"row","type":"table"},{"name":"Tip","style":"tip","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":".onlyArticleLink()"},{"type":"text","text":" is the default policy when no share delegate is"},{"type":"text","text":" "},{"type":"text","text":"assigned. Assign a delegate explicitly only if you need a different policy."}],"type":"paragraph"}]},{"text":"Quick Setup","level":2,"anchor":"Quick-Setup","type":"heading"},{"inlineContent":[{"type":"text","text":"To enable web reader sharing, create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/WebReaderShareProvider"},{"type":"text","text":" with your"},{"type":"text","text":" "},{"type":"text","text":"shortcode and assign it through a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareProvider"},{"type":"text","text":":"}],"type":"paragraph"},{"code":["let webProvider = PSReaderUI.WebReaderShareProvider(","    urlMask: nil,","    shortCode: \"SHORTCODE\"",")","","globalConfig.shareDelegate = PSReaderUI.ShareProvider(","    sharePolicy: .preferArticleLink(","        webProvider: webProvider,","        articleLinkProvider: PSReaderUI.ArticleLinkShareProvider()","    )",")"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"To disable sharing entirely:","type":"text"}],"type":"paragraph"},{"code":["globalConfig.shareDelegate = PSReaderUI.ShareProvider(sharePolicy: .disabled)"],"type":"codeListing","syntax":"swift"},{"text":"Policy Examples","level":2,"type":"heading","anchor":"Policy-Examples"},{"text":"Web Reader Only","level":3,"type":"heading","anchor":"Web-Reader-Only"},{"inlineContent":[{"type":"text","text":"Share every page as a web reader link. Useful when the publisher does not have"},{"type":"text","text":" "},{"type":"text","text":"article pages on their website:"}],"type":"paragraph"},{"code":["let webProvider = PSReaderUI.WebReaderShareProvider(","    urlMask: nil,","    shortCode: \"SHORTCODE\"",")","","globalConfig.shareDelegate = PSReaderUI.ShareProvider(","    sharePolicy: .onlyWebReader(webProvider: webProvider)",")"],"type":"codeListing","syntax":"swift"},{"text":"Custom Web Reader Domain","level":3,"type":"heading","anchor":"Custom-Web-Reader-Domain"},{"inlineContent":[{"text":"If your web reader is hosted on a custom domain, pass it as the ","type":"text"},{"code":"urlMask","type":"codeVoice"},{"text":":","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let webProvider = PSReaderUI.WebReaderShareProvider(","    urlMask: \"reader.mypublication.com\",","    shortCode: \"SHORTCODE\"",")"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When "},{"type":"codeVoice","code":"urlMask"},{"type":"text","text":" is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", the provider defaults to "},{"type":"codeVoice","code":"reader.pagesuite.com"},{"type":"text","text":" for"},{"type":"text","text":" "},{"type":"text","text":"feed editions and "},{"type":"codeVoice","code":"edition.pagesuite.com"},{"type":"text","text":" for replica editions."}]},{"level":3,"type":"heading","anchor":"Article-Link-Only-Default","text":"Article Link Only (Default)"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Only pages that have a publisher-configured article link are shareable:"}]},{"type":"codeListing","syntax":"swift","code":["globalConfig.shareDelegate = PSReaderUI.ShareProvider(","    sharePolicy: .onlyArticleLink()",")"]},{"level":3,"type":"heading","anchor":"Prefer-Article-Link-with-Web-Reader-Fallback","text":"Prefer Article Link with Web Reader Fallback"},{"type":"paragraph","inlineContent":[{"text":"Share the article link when available, otherwise fall back to the web reader:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let webProvider = PSReaderUI.WebReaderShareProvider(","    urlMask: nil,","    shortCode: \"SHORTCODE\"",")","","globalConfig.shareDelegate = PSReaderUI.ShareProvider(","    sharePolicy: .preferArticleLink(","        webProvider: webProvider,","        articleLinkProvider: PSReaderUI.ArticleLinkShareProvider()","    )",")"]},{"level":2,"type":"heading","anchor":"ShareContext","text":"ShareContext"},{"type":"paragraph","inlineContent":[{"text":"When a share action is triggered, the delegate returns a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareContext","type":"reference"},{"text":" that","type":"text"},{"text":" ","type":"text"},{"text":"the SDK passes to ","type":"text"},{"code":"UIActivityViewController","type":"codeVoice"},{"text":". The struct has three fields:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"inlineContent":[{"code":"activityItems","type":"codeVoice"}],"type":"strong"},{"text":" — the primary items to share (URLs, strings, images).","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"code":"applicationActivities","type":"codeVoice"}]},{"type":"text","text":" — optional custom "},{"type":"codeVoice","code":"UIActivity"},{"type":"text","text":" instances to"},{"type":"text","text":" "},{"type":"text","text":"include in the share sheet."}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"code":"subject","type":"codeVoice"}],"type":"strong"},{"type":"text","text":" — an optional subject line used by activities like Mail."}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The built-in providers automatically add a "},{"type":"strong","inlineContent":[{"type":"text","text":"Copy Link"}]},{"type":"text","text":" activity to"},{"type":"text","text":" "},{"type":"codeVoice","code":"applicationActivities"},{"type":"text","text":". If you implement a custom delegate, add your own"},{"type":"text","text":" "},{"type":"text","text":"activities as needed."}]},{"level":2,"type":"heading","anchor":"Replica-vs-Feed-Sharing","text":"Replica vs Feed Sharing"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate","type":"reference","isActive":true},{"text":" protocol defines ","type":"text"},{"inlineContent":[{"type":"text","text":"separate methods"}],"type":"strong"},{"text":" for feed and","type":"text"},{"text":" ","type":"text"},{"text":"replica editions.","type":"text"}]},{"level":3,"type":"heading","anchor":"Feed-Edition-Methods","text":"Feed Edition Methods"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Feed editions use page-level sharing:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"isShareable(page:inEdition:inPublished:)"},{"text":" — controls whether the share","type":"text"},{"text":" ","type":"text"},{"text":"button is visible for a given page.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"shareContext(forPage:inEdition:inPublished:)","type":"codeVoice"},{"type":"text","text":" — provides the share content."}]}]}]},{"level":3,"type":"heading","anchor":"Replica-Edition-Methods","text":"Replica Edition Methods"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Replica editions use spread-level sharing. A "},{"code":"PSReplicaPageSpread","type":"codeVoice"},{"type":"text","text":" represents"},{"type":"text","text":" "},{"type":"text","text":"what the user currently sees and has three cases:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"codeVoice","code":".single(PSPage)"}]},{"type":"text","text":" — a single PDF page."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"codeVoice","code":".double(left: PSPage?, right: PSPage?)"}]},{"type":"text","text":" — a double-page spread in"},{"type":"text","text":" "},{"type":"text","text":"landscape mode."}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"codeVoice","code":".article(PSArticle)"}],"type":"strong"},{"text":" — an article view within the replica reader.","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"text":"The delegate methods receive a ","type":"text"},{"code":"PSReplicaPageSpread","type":"codeVoice"},{"text":" and a","type":"text"},{"text":" ","type":"text"},{"code":"PSReplicaEdition","type":"codeVoice"},{"text":":","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"isShareable(spread:inReplicaEdition:)","type":"codeVoice"},{"text":" — controls share button visibility.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"shareContext(forSpread:inReplicaEdition:)"},{"text":" — provides the share content.","type":"text"}],"type":"paragraph"}]}]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArticleLinkShareProvider"},{"type":"text","text":" only shares replica article spreads"},{"type":"text","text":" "},{"type":"text","text":"("},{"type":"codeVoice","code":".article"},{"type":"text","text":" case) where the article has a non-empty "},{"type":"codeVoice","code":"shareLink"},{"type":"text","text":". PDF page"},{"type":"text","text":" "},{"type":"text","text":"spreads are not shareable through this provider."}],"type":"paragraph"}],"style":"note","name":"Note"},{"level":2,"type":"heading","anchor":"Custom-ShareDelegate","text":"Custom ShareDelegate"},{"type":"paragraph","inlineContent":[{"text":"For full control, implement ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate","isActive":true},{"text":" directly. The protocol has","type":"text"},{"text":" ","type":"text"},{"text":"methods for both feed edition pages and replica spreads:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["struct MyShareDelegate: PSReaderUI.ShareDelegate {","","    \/\/ MARK: Feed Edition Methods","","    func isShareable(","        page: PSEPage,","        inEdition edition: PSEEdition,","        inPublished published: PSEPublished","    ) -> Bool {","        \/\/ Only share article pages","        return page.type == \"templateArticle\"","    }","","    func shareContext(","        forPage page: PSEPage,","        inEdition edition: PSEEdition,","        inPublished published: PSEPublished","    ) -> ShareContext? {","        guard let article = page.articles?.first,","              let shareLink = article.sharelink,","              let url = URL(string: shareLink) else {","            return nil","        }","        return ShareContext(","            activityItems: [url],","            subject: article.headline","        )","    }","","    \/\/ MARK: Replica Edition Methods","","    func isShareable(","        spread: PSReplicaPageSpread,","        inReplicaEdition replicaEdition: PSReplicaEdition","    ) -> Bool {","        \/\/ Share all page spreads; only share articles that have a link","        switch spread {","        case .single, .double:","            return true","        case .article(let article):","            return !article.shareLink.isEmpty","        }","    }","","    func shareContext(","        forSpread spread: PSReplicaPageSpread,","        inReplicaEdition replicaEdition: PSReplicaEdition","    ) -> ShareContext? {","        let edition = replicaEdition.edition","","        switch spread {","        case .article(let article):","            \/\/ Share the article link","            guard let url = URL(string: article.shareLink) else { return nil }","            return ShareContext(","                activityItems: [url],","                subject: article.headline","            )","","        case .single(let page):","            \/\/ Share a text description of the page","            let text = \"\\(edition.publicationName) - \\(edition.name), page \\(page.num)\"","            return ShareContext(activityItems: [text])","","        case .double(let left, let right):","            let page = left ?? right","            guard let page else { return nil }","            let text = \"\\(edition.publicationName) - \\(edition.name), page \\(page.num)\"","            return ShareContext(activityItems: [text])","        }","    }","}"]},{"type":"aside","content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"isShareable","type":"codeVoice"},{"text":" methods have default implementations that return","type":"text"},{"text":" ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" when ","type":"text"},{"code":"shareContext","type":"codeVoice"},{"text":" returns a non-nil value. You only need to implement","type":"text"},{"text":" ","type":"text"},{"text":"them explicitly as a performance optimization to avoid building a share","type":"text"},{"text":" ","type":"text"},{"text":"context just to check visibility.","type":"text"}],"type":"paragraph"}],"style":"tip","name":"Tip"},{"level":2,"type":"heading","anchor":"Print-Integration","text":"Print Integration"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since v5.3, printing is consolidated into the share actions. The dedicated"},{"type":"text","text":" "},{"type":"text","text":"print icon has been removed from the reader navigation bar. Users access"},{"type":"text","text":" "},{"type":"text","text":"printing through the system share sheet, where it appears as a standard"},{"type":"text","text":" "},{"type":"codeVoice","code":"UIActivity"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"Printing requires no configuration. It is available automatically whenever","type":"text"},{"text":" ","type":"text"},{"text":"sharing is enabled (i.e., the share delegate is not set to ","type":"text"},{"code":".disabled","type":"codeVoice"},{"text":").","type":"text"}]}],"kind":"content"}],"seeAlsoSections":[{"anchor":"Features","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"title":"Features","generated":true}],"sections":[],"abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/sharing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/sharing"]}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ShareDelegate":{"abstract":[{"type":"text","text":"Delegate protocol used to provide sharing functionality within the SDK."}],"url":"\/documentation\/psreaderui\/sharedelegate","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShareDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ShareDelegate"}],"title":"ShareDelegate","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ShareContext":{"title":"ShareContext","kind":"symbol","navigatorTitle":[{"text":"ShareContext","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareContext","type":"topic","url":"\/documentation\/psreaderui\/sharecontext","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ShareContext","kind":"identifier"}],"abstract":[{"type":"text","text":"A structure encapsulating information used to present shareable content."}],"role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"kind":"article","url":"\/documentation\/psreaderui\/advertisements","type":"topic","abstract":[{"type":"text","text":"Display custom advertisements within the reader."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","title":"Advertisements","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"abstract":[{"type":"text","text":"Track user interactions and content engagement across the PSReaderUI SDK."}],"role":"article","kind":"article","url":"\/documentation\/psreaderui\/analytics","title":"Analytics","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/WebReaderShareProvider":{"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate"},{"type":"text","text":" that provides shareable links to the web reader pages."},{"type":"text","text":" "},{"type":"text","text":"Use this provider to generate URLs pointing to web reader content."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebReaderShareProvider"}],"navigatorTitle":[{"kind":"identifier","text":"WebReaderShareProvider"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/WebReaderShareProvider","role":"symbol","url":"\/documentation\/psreaderui\/webreadershareprovider","title":"WebReaderShareProvider"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"role":"article","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","abstract":[{"text":"Add audio playback of article content using the SDK’s text-to-speech system.","type":"text"}],"type":"topic","title":"Text-to-Speech","url":"\/documentation\/psreaderui\/text-to-speech"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"type":"topic","abstract":[{"text":"A UI framework for building digital newspaper and magazine reader experiences on iOS.","type":"text"}],"url":"\/documentation\/psreaderui","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","title":"PSReaderUI","role":"collection","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ShareProvider/SharePolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharePolicy"}],"title":"ShareProvider.SharePolicy","role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareProvider\/SharePolicy","navigatorTitle":[{"kind":"identifier","text":"SharePolicy"}],"kind":"symbol","abstract":[{"type":"text","text":"Defines the sharing strategy used by the SDK."}],"type":"topic","url":"\/documentation\/psreaderui\/shareprovider\/sharepolicy"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"type":"topic","role":"article","title":"Media Playback","url":"\/documentation\/psreaderui\/media-playback","kind":"article","abstract":[{"type":"text","text":"Enable video and media playback within the reader."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ShareProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShareProvider"}],"navigatorTitle":[{"kind":"identifier","text":"ShareProvider"}],"kind":"symbol","title":"ShareProvider","url":"\/documentation\/psreaderui\/shareprovider","type":"topic","abstract":[{"text":"A composite share provider allowing multiple share strategies to be chained.","type":"text"},{"text":" ","type":"text"},{"text":"Configure this provider to choose preferred or fallback sharing behaviors.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareProvider","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"role":"article","url":"\/documentation\/psreaderui\/paywall-integration","type":"topic","abstract":[{"type":"text","text":"Restrict access to premium content with custom paywall screens."}],"title":"Paywall Integration","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArticleLinkShareProvider":{"type":"topic","kind":"symbol","role":"symbol","title":"ArticleLinkShareProvider","navigatorTitle":[{"kind":"identifier","text":"ArticleLinkShareProvider"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleLinkShareProvider"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate","isActive":true},{"type":"text","text":" providing direct article links on the publication’s website."}],"url":"\/documentation\/psreaderui\/articlelinkshareprovider","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArticleLinkShareProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"generated":true,"title":"Features","anchor":"Features"}]}]}]}