{"metadata":{"modules":[{"name":"PSReaderUI"}],"roleHeading":"Article","title":"Standalone View Controllers","role":"article"},"hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"abstract":[{"type":"text","text":"Use archive, bookmarks, downloads, and search views outside of the carousel."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers"},"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"generated":true,"anchor":"Customization","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"],"title":"Customization"}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","type":"reference","isActive":true},{"text":" is the primary way to present SDK content, but","type":"text"},{"text":" ","type":"text"},{"text":"the SDK also exposes four standalone view controllers for use outside the","type":"text"},{"text":" ","type":"text"},{"text":"carousel. These are useful when you want to embed a specific view in your own","type":"text"},{"text":" ","type":"text"},{"text":"navigation hierarchy or present it independently.","type":"text"}]},{"anchor":"When-to-Use-Standalone-View-Controllers","type":"heading","level":2,"text":"When to Use Standalone View Controllers"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use standalone view controllers when you need to embed a single content view"},{"type":"text","text":" "},{"type":"text","text":"in your own navigation hierarchy — for example, a bookmarks tab in a custom"},{"type":"text","text":" "},{"type":"text","text":"tab bar controller. Prefer "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController"},{"type":"text","text":" when you want the full"},{"type":"text","text":" "},{"type":"text","text":"tabbed experience with section ribbons, since it manages navigation and layout"},{"type":"text","text":" "},{"type":"text","text":"internally."}]},{"anchor":"ArchiveViewController","type":"heading","level":2,"text":"ArchiveViewController"},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController","isActive":true,"type":"reference"},{"text":" displays a publication’s edition archive in a grid","type":"text"},{"text":" ","type":"text"},{"text":"layout. Initialize it with an ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController\/ArchiveType","isActive":true,"type":"reference"},{"text":" to specify","type":"text"},{"text":" ","type":"text"},{"text":"the content source:","type":"text"}]},{"code":["\/\/ Feed edition archive","let feedArchive = PSReaderUI.ArchiveViewController(","    globalConfig: globalConfig,","    archiveType: .feedArchive(guid: \"APP_GUID\", publicationName: \"My Publication\")",")","","\/\/ Replica edition archive","let replicaArchive = PSReaderUI.ArchiveViewController(","    globalConfig: globalConfig,","    archiveType: .replicaArchive(guid: \"PUB_GUID\")",")","","\/\/ Kiosk grids","let replicaKiosk = PSReaderUI.ArchiveViewController(","    globalConfig: globalConfig,","    archiveType: .replicaPublicationKiosk(publications: replicaPublications)",")","","let feedKiosk = PSReaderUI.ArchiveViewController(","    globalConfig: globalConfig,","    archiveType: .feedPublicationKiosk(publications: feedPublications)",")"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Pass an optional "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","isActive":true},{"type":"text","text":" to customize the appearance."}]},{"anchor":"Kiosk-Grid-Setup","type":"heading","level":3,"text":"Kiosk Grid Setup"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For kiosk grids, build an array of "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/KioskReplicaPublication","isActive":true},{"type":"text","text":" entries. Each"},{"type":"text","text":" "},{"type":"text","text":"entry specifies a publication GUID and an optional per-publication"},{"type":"text","text":" "},{"type":"text","text":"configuration override:"}]},{"code":["let publications = [","    PSReaderUI.KioskReplicaPublication(guid: \"PUB_GUID_1\"),","    PSReaderUI.KioskReplicaPublication(guid: \"PUB_GUID_2\"),","    PSReaderUI.KioskReplicaPublication(","        guid: \"PUB_GUID_3\",","        archiveConfig: specialArchiveConfig  \/\/ Optional override","    )","]","","let kioskVC = PSReaderUI.ArchiveViewController(","    globalConfig: globalConfig,","    archiveType: .replicaPublicationKiosk(publications: publications)",")"],"type":"codeListing","syntax":"swift"},{"anchor":"BookmarksViewController","type":"heading","level":2,"text":"BookmarksViewController"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController"},{"type":"text","text":" displays the user’s bookmarked pages and articles."},{"type":"text","text":" "},{"type":"text","text":"Filter the displayed content using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksConfiguration\/BookmarkType"},{"type":"text","text":":"}]},{"code":["\/\/ All bookmarks","let allBookmarks = PSReaderUI.BookmarksViewController(","    globalConfig: globalConfig,","    type: .all",")","","\/\/ Only replica edition bookmarks","let replicaBookmarks = PSReaderUI.BookmarksViewController(","    globalConfig: globalConfig,","    type: .replicaEdition",")"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller exposes a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController\/sortMode-swift.property"},{"type":"text","text":" property"},{"type":"text","text":" "},{"type":"text","text":"with two options:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".byBookmarked"},{"type":"text","text":" — most recently bookmarked first."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":".byDate","type":"codeVoice"},{"type":"text","text":" — most recent publication date first."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The user can also change the sort mode through a menu button in the UI. The"},{"type":"text","text":" "},{"type":"text","text":"selected sort mode is persisted across sessions."}]},{"anchor":"DownloadsViewController","type":"heading","level":2,"text":"DownloadsViewController"},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController","isActive":true,"type":"reference"},{"text":" displays editions the user has downloaded for","type":"text"},{"text":" ","type":"text"},{"text":"offline reading. Filter by ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsConfiguration\/DownloadType","type":"reference","isActive":true},{"text":":","type":"text"}]},{"code":["let downloads = PSReaderUI.DownloadsViewController(","    globalConfig: globalConfig,","    downloadTypes: .all",")"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Like bookmarks, downloads supports a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController\/sortMode-swift.property"},{"text":" ","type":"text"},{"text":"property:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":".byDownloaded"},{"type":"text","text":" — most recently downloaded first."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".byDate"},{"text":" — most recent publication date first.","type":"text"}]}]}]},{"anchor":"SearchViewController","type":"heading","level":2,"text":"SearchViewController"},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchViewController","isActive":true},{"type":"text","text":" provides full-text search across feed edition"},{"type":"text","text":" "},{"type":"text","text":"publications. It requires a "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate","isActive":true},{"type":"text","text":" to supply the list of searchable"},{"type":"text","text":" "},{"type":"text","text":"publications and their reader configurations. Use "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ApplicationSearchDelegate","isActive":true},{"type":"text","text":" "},{"type":"text","text":"for a ready-made implementation:"}]},{"code":["let delegate = PSReaderUI.ApplicationSearchDelegate(","    shortcode: \"SHORTCODE\",","    readerConfig: readerConfig",")","","let searchVC = PSReaderUI.SearchViewController(","    globalConfig: globalConfig,","    delegate: delegate",")"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For modal presentation, set "},{"code":"dismissible","type":"codeVoice"},{"type":"text","text":" to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" to show a close button:"}]},{"code":["let searchVC = PSReaderUI.SearchViewController(","    globalConfig: globalConfig,","    delegate: delegate,","    dismissible: true",")","","present(searchVC, animated: true)"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Pass an optional ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration"},{"text":" to customize the appearance. See","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"},{"text":" for the full search integration guide.","type":"text"}]},{"anchor":"Common-Patterns","type":"heading","level":2,"text":"Common Patterns"},{"anchor":"Safe-Area-Insets","type":"heading","level":3,"text":"Safe Area Insets"},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController","isActive":true,"type":"reference"},{"text":", and","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController","isActive":true,"type":"reference"},{"text":" support ","type":"text"},{"type":"codeVoice","code":"additionalSafeAreaInsets"},{"text":". Set this when","type":"text"},{"text":" ","type":"text"},{"text":"embedding in a container that already applies its own insets:","type":"text"}]},{"code":["archiveVC.additionalSafeAreaInsets = UIEdgeInsets(top: 0, left: 0, bottom: 49, right: 0)"],"type":"codeListing","syntax":"swift"},{"anchor":"Interface-Style","type":"heading","level":3,"text":"Interface Style"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Override the user interface style to force light or dark mode for a specific"},{"type":"text","text":" "},{"type":"text","text":"view controller:"}]},{"code":["bookmarksVC.overrideUserInterfaceStyle = .dark"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This setting propagates to all internal child view controllers."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/standalone-view-controllers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/standalone-view-controllers"]}],"sections":[],"kind":"article","references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DownloadsViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownloadsViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A standalone view controller for displaying downloaded editions."}],"title":"DownloadsViewController","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DownloadsViewController","kind":"identifier"}],"url":"\/documentation\/psreaderui\/downloadsviewcontroller","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/BookmarksViewController/sortMode-swift.property":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController\/sortMode-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sortMode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10PSReaderUI23BookmarksViewControllerC8SortModeO","kind":"typeIdentifier","text":"SortMode"}],"url":"\/documentation\/psreaderui\/bookmarksviewcontroller\/sortmode-swift.property","title":"sortMode","abstract":[{"type":"text","text":"The current sort mode for displaying bookmarks."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchViewController","kind":"identifier"}],"abstract":[{"text":"A standalone view controller for searching feed edition content.","type":"text"}],"title":"SearchViewController","type":"topic","url":"\/documentation\/psreaderui\/searchviewcontroller","role":"symbol","navigatorTitle":[{"text":"SearchViewController","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchViewController","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Carousel-Setup":{"type":"topic","abstract":[{"type":"text","text":"Configure the carousel’s sections, content sources, and layout."}],"title":"Carousel Setup","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","url":"\/documentation\/psreaderui\/carousel-setup","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DownloadsViewController/sortMode-swift.property":{"abstract":[{"type":"text","text":"The current sort mode for displaying downloaded editions."}],"url":"\/documentation\/psreaderui\/downloadsviewcontroller\/sortmode-swift.property","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController\/sortMode-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sortMode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10PSReaderUI23DownloadsViewControllerC8SortModeO","kind":"typeIdentifier","text":"SortMode"}],"kind":"symbol","role":"symbol","title":"sortMode","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/KioskReplicaPublication":{"kind":"symbol","abstract":[{"text":"Describes a replica publication entry in a kiosk grid.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"KioskReplicaPublication"}],"url":"\/documentation\/psreaderui\/kioskreplicapublication","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KioskReplicaPublication"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/KioskReplicaPublication","title":"KioskReplicaPublication"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/BookmarksViewController":{"abstract":[{"type":"text","text":"A standalone view controller for displaying bookmarked pages and articles."}],"navigatorTitle":[{"text":"BookmarksViewController","kind":"identifier"}],"url":"\/documentation\/psreaderui\/bookmarksviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BookmarksViewController","kind":"identifier"}],"type":"topic","role":"symbol","title":"BookmarksViewController","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveViewController/ArchiveType":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController\/ArchiveType","type":"topic","role":"symbol","abstract":[{"text":"Describes the type of archive content to display.","type":"text"}],"title":"ArchiveViewController.ArchiveType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveType"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArchiveType"}],"url":"\/documentation\/psreaderui\/archiveviewcontroller\/archivetype"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveViewController"}],"abstract":[{"text":"A standalone view controller for displaying publication archives.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController","title":"ArchiveViewController","navigatorTitle":[{"kind":"identifier","text":"ArchiveViewController"}],"kind":"symbol","url":"\/documentation\/psreaderui\/archiveviewcontroller"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarouselViewController"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","type":"topic","abstract":[{"type":"text","text":"The primary view controller provided by the SDK for presenting digital publication"},{"type":"text","text":" "},{"type":"text","text":"content through an intuitive carousel interface."}],"url":"\/documentation\/psreaderui\/carouselviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CarouselViewController"}],"kind":"symbol","title":"CarouselViewController"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ApplicationSearchDelegate":{"type":"topic","url":"\/documentation\/psreaderui\/applicationsearchdelegate","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ApplicationSearchDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApplicationSearchDelegate"}],"abstract":[{"text":"A ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate","type":"reference"},{"text":" that derives search publications from a ","type":"text"},{"code":"PSEApplication","type":"codeVoice"},{"text":" ","type":"text"},{"text":"or fetches one lazily from a shortcode.","type":"text"}],"title":"ApplicationSearchDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplicationSearchDelegate"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveConfiguration":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","url":"\/documentation\/psreaderui\/archiveconfiguration","role":"symbol","title":"ArchiveConfiguration","navigatorTitle":[{"text":"ArchiveConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for customizing the appearance and behavior of publication archive views."}],"type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArchiveConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Localization":{"role":"article","title":"Localization","abstract":[{"text":"Localize all user-facing strings in the PSReaderUI SDK.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization","url":"\/documentation\/psreaderui\/localization","type":"topic","kind":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","url":"\/documentation\/psreaderui","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"title":"PSReaderUI"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchConfiguration":{"role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchConfiguration","navigatorTitle":[{"text":"SearchConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the SDK’s built-in search interface."}],"title":"SearchConfiguration","kind":"symbol","url":"\/documentation\/psreaderui\/searchconfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Search":{"role":"article","type":"topic","abstract":[{"type":"text","text":"Search across feed edition content for articles and pages."}],"url":"\/documentation\/psreaderui\/search","kind":"article","title":"Search","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Search"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SearchDelegate":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SearchDelegate","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SearchDelegate","title":"SearchDelegate","url":"\/documentation\/psreaderui\/searchdelegate","abstract":[{"text":"A delegate that provides the list of searchable publications and their reader configurations.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Theming-and-Customization":{"role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","title":"Theming and Customization","kind":"article","url":"\/documentation\/psreaderui\/theming-and-customization","abstract":[{"type":"text","text":"Adjust fonts, colors, icons, and layouts to match your app’s brand."}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DownloadsConfiguration/DownloadType":{"url":"\/documentation\/psreaderui\/downloadsconfiguration\/downloadtype","title":"DownloadsConfiguration.DownloadType","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsConfiguration\/DownloadType","type":"topic","abstract":[{"type":"text","text":"Defines the types of downloadable content supported by the downloads view."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadType"}],"navigatorTitle":[{"kind":"identifier","text":"DownloadType"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/BookmarksConfiguration/BookmarkType":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksConfiguration\/BookmarkType","kind":"symbol","navigatorTitle":[{"text":"BookmarkType","kind":"identifier"}],"abstract":[{"type":"text","text":"An option set representing the types of bookmarks supported by the bookmarks view."}],"title":"BookmarksConfiguration.BookmarkType","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BookmarkType","kind":"identifier"}],"url":"\/documentation\/psreaderui\/bookmarksconfiguration\/bookmarktype"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"anchor":"Customization","title":"Customization","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}