{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/text-to-speech"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/text-to-speech"]}],"abstract":[{"text":"Add audio playback of article content using the SDK’s text-to-speech system.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"title":"Features","anchor":"Features","generated":true}],"metadata":{"modules":[{"name":"PSReaderUI"}],"title":"Text-to-Speech","roleHeading":"Article","role":"article"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The PSReaderUI SDK provides a modular text-to-speech (TTS) architecture built"},{"type":"text","text":" "},{"type":"text","text":"around the "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate","isActive":true},{"type":"text","text":" protocol. The system is designed so that each"},{"type":"text","text":" "},{"type":"text","text":"layer can be swapped independently — you can replace just the voice synthesis,"},{"type":"text","text":" "},{"type":"text","text":"just the article formatting, or just the UI without touching the rest:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Article Formatter"}]},{"text":" (","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechArticleFormatter"},{"text":") — extracts and","type":"text"},{"text":" ","type":"text"},{"text":"formats article text for synthesis.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Speech Synthesizer","type":"text"}],"type":"strong"},{"type":"text","text":" ("},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechSynthesizer","type":"reference","isActive":true},{"type":"text","text":") — converts formatted"},{"type":"text","text":" "},{"type":"text","text":"text into an audio file."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Audio Session Provider","type":"text"}]},{"text":" (","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioSessionProvider","isActive":true,"type":"reference"},{"text":") — manages the","type":"text"},{"text":" ","type":"text"},{"code":"AVAudioSession","type":"codeVoice"},{"text":" lifecycle.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Audio Interface"}],"type":"strong"},{"text":" — presents playback controls to the user as either a","type":"text"},{"text":" ","type":"text"},{"text":"transient overlay or a persistent banner.","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"The SDK ships default implementations of each component. For most apps, the","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider"},{"text":" class wires everything together in a single","type":"text"},{"text":" ","type":"text"},{"text":"line.","type":"text"}]},{"type":"heading","level":2,"text":"Quick Start","anchor":"Quick-Start"},{"type":"paragraph","inlineContent":[{"text":"Assign a ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","type":"reference","isActive":true},{"text":" as the audio delegate on your","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","type":"reference","isActive":true},{"text":":","type":"text"}]},{"type":"codeListing","code":["globalConfig.audioDelegate = PSReaderUI.DefaultTextToSpeechProvider(","    configuration: .init(globalConfig: globalConfig)",")"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"That’s it. This enables a listen button in the reader navigation bar. When"},{"type":"text","text":" "},{"type":"text","text":"tapped, the SDK formats the current article, synthesizes speech using the"},{"type":"text","text":" "},{"type":"text","text":"device’s text-to-speech engine, and presents an audio overlay with playback"},{"type":"text","text":" "},{"type":"text","text":"controls."}]},{"type":"paragraph","inlineContent":[{"text":"All of the defaults — article formatting, speech synthesis, audio session","type":"text"},{"text":" ","type":"text"},{"text":"management, and overlay appearance — are handled automatically. The sections","type":"text"},{"text":" ","type":"text"},{"text":"below cover how to customize individual layers if you need more control.","type":"text"}]},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"text":"TTS is available for ","type":"text"},{"inlineContent":[{"text":"article pages only","type":"text"}],"type":"strong"},{"text":". Pure PDF pages (non-article","type":"text"},{"text":" ","type":"text"},{"text":"page spreads) do not contain structured text and cannot be synthesized. The","type":"text"},{"text":" ","type":"text"},{"text":"listen button will not appear for these pages.","type":"text"}],"type":"paragraph"}]},{"type":"heading","level":2,"text":"Custom Synthesizer","anchor":"Custom-Synthesizer"},{"inlineContent":[{"text":"The default synthesizer (","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechSynthesizer"},{"text":") uses","type":"text"},{"text":" ","type":"text"},{"code":"AVSpeechSynthesizer","type":"codeVoice"},{"text":" with the device’s default voice. If the user has","type":"text"},{"text":" ","type":"text"},{"text":"downloaded a premium or enhanced voice through ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Settings > Accessibility >"},{"type":"text","text":" "},{"type":"text","text":"Spoken Content > Voices"}]},{"text":", iOS will prefer it automatically. However, most","type":"text"},{"text":" ","type":"text"},{"text":"users will not have done this, and the default system voice can sound","type":"text"},{"text":" ","type":"text"},{"text":"noticeably robotic.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"To provide a higher quality experience, implement "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechSynthesizer","isActive":true},{"type":"text","text":" "},{"type":"text","text":"and plug in your own synthesis layer — whether that’s a third-party TTS"},{"type":"text","text":" "},{"type":"text","text":"package bundled with the app or a cloud-based service. Everything else the SDK"},{"type":"text","text":" "},{"type":"text","text":"provides (article formatting, the overlay UI, audio session management,"},{"type":"text","text":" "},{"type":"text","text":"playback controls) continues to work unchanged:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["struct PremiumSynthesizer: PSReaderUI.TextToSpeechSynthesizer {","    func synthesize(string: String, completion: @escaping (Result<URL, Error>) -> Void) {","        \/\/ Call your TTS API, write the audio to a temporary file,","        \/\/ and return the file URL.","        MyTTSService.synthesize(string) { result in","            completion(result)","        }","    }","}","","\/\/ Swap in your synthesizer — the rest of the stack stays the same","globalConfig.audioDelegate = PSReaderUI.DefaultTextToSpeechProvider(","    configuration: .init(globalConfig: globalConfig),","    speechSynthesizer: PremiumSynthesizer()",")"]},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"language"},{"type":"text","text":" parameter on "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechSynthesizer","type":"reference","isActive":true},{"type":"text","text":" controls the"},{"type":"text","text":" "},{"type":"text","text":"voice locale when using the built-in engine (defaults to "},{"type":"codeVoice","code":"\"en\""},{"type":"text","text":")."}],"type":"paragraph"},{"type":"heading","text":"Custom Article Formatter","level":2,"anchor":"Custom-Article-Formatter"},{"inlineContent":[{"text":"Implement ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechArticleFormatter","isActive":true,"type":"reference"},{"text":" to control how article content is","type":"text"},{"text":" ","type":"text"},{"text":"prepared before it reaches the synthesizer. This is useful for stripping","type":"text"},{"text":" ","type":"text"},{"text":"boilerplate, reordering sections, adding pronunciation hints, or inserting","type":"text"},{"text":" ","type":"text"},{"text":"pauses between paragraphs.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Like the synthesizer, the formatter plugs directly into"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","isActive":true},{"type":"text","text":" — you get to customize what text is spoken"},{"type":"text","text":" "},{"type":"text","text":"without rebuilding the rest of the stack:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["struct MyArticleFormatter: PSReaderUI.TextToSpeechArticleFormatter {","    func format(article: PSEArticle) throws -> String {","        let title = article.title ?? \"\"","        let body = article.body ?? \"\"","        return \"\\(title). \\(body)\"","    }","","    func format(article: PSArticle) throws -> String {","        return article.title ?? \"\"","    }","}","","globalConfig.audioDelegate = PSReaderUI.DefaultTextToSpeechProvider(","    configuration: .init(globalConfig: globalConfig),","    articleFormatter: MyArticleFormatter()",")"]},{"inlineContent":[{"type":"text","text":"The built-in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechArticleFormatter"},{"type":"text","text":" extracts the headline,"},{"type":"text","text":" "},{"type":"text","text":"byline, and body text, strips HTML markup, and joins them into a clean string"},{"type":"text","text":" "},{"type":"text","text":"ready for synthesis."}],"type":"paragraph"},{"inlineContent":[{"text":"You can combine a custom formatter and a custom synthesizer together:","type":"text"}],"type":"paragraph"},{"code":["globalConfig.audioDelegate = PSReaderUI.DefaultTextToSpeechProvider(","    configuration: .init(globalConfig: globalConfig),","    articleFormatter: MyArticleFormatter(),","    speechSynthesizer: PremiumSynthesizer()",")"],"type":"codeListing","syntax":"swift"},{"type":"heading","level":2,"text":"Audio Interface Patterns","anchor":"Audio-Interface-Patterns"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK supports two UI patterns for audio playback. You can use either one or"},{"type":"text","text":" "},{"type":"text","text":"both, depending on your "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate"},{"type":"text","text":" implementation."}]},{"type":"heading","level":3,"text":"Transient Overlay","anchor":"Transient-Overlay"},{"type":"paragraph","inlineContent":[{"text":"The default pattern used by ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","type":"reference"},{"text":". When the user taps","type":"text"},{"text":" ","type":"text"},{"text":"the listen button, a popover-style overlay appears over the reader content. The","type":"text"},{"text":" ","type":"text"},{"text":"overlay includes:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Play \/ Pause"}]},{"text":" button with a loading indicator during synthesis","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Skip backward \/ forward"}]},{"text":" buttons (15-second increments)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Progress bar"}]},{"type":"text","text":" with scrub support for seeking through the audio"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Elapsed","type":"text"}],"type":"strong"},{"text":" and ","type":"text"},{"inlineContent":[{"type":"text","text":"remaining"}],"type":"strong"},{"text":" time labels","type":"text"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Title"}],"type":"strong"},{"type":"text","text":" and "},{"inlineContent":[{"text":"subtitle","type":"text"}],"type":"strong"},{"type":"text","text":" labels showing the article name"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"text":"The SDK manages the overlay’s presentation and dismissal. The overlay is","type":"text"},{"text":" ","type":"text"},{"text":"dismissed when the user taps outside it. On iOS 26+, the overlay adopts the","type":"text"},{"text":" ","type":"text"},{"text":"Liquid Glass design language by default.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"To provide a fully custom overlay UI while keeping the SDK’s lifecycle","type":"text"},{"text":" ","type":"text"},{"text":"management, subclass ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlay"},{"text":":","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Create a subclass of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlay"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Design your audio interface in the subclass."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Return an instance from your "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate"},{"type":"text","text":" "},{"code":"playAudio","type":"codeVoice"},{"type":"text","text":" method."}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Both feed and replica editions support overlays via separate delegate methods:"},{"type":"text","text":" "},{"type":"codeVoice","code":"playAudio(for:inEdition:)"},{"type":"text","text":" for feed editions and"},{"type":"text","text":" "},{"type":"codeVoice","code":"playAudio(forSpread:inReplicaEdition:)"},{"type":"text","text":" for replica editions."}]},{"type":"heading","level":3,"text":"Persistent Banner","anchor":"Persistent-Banner"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An alternative pattern where a compact audio control banner remains visible at"},{"type":"text","text":" "},{"type":"text","text":"the bottom of the reader as the user navigates between pages. This is useful"},{"type":"text","text":" "},{"type":"text","text":"when you want playback controls to persist across page navigation rather than"},{"type":"text","text":" "},{"type":"text","text":"appearing as a modal."}]},{"type":"paragraph","inlineContent":[{"text":"Implement ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioBannerViewController","type":"reference","isActive":true},{"text":" and return it from","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate\/audioBannerViewController()","type":"reference","isActive":true},{"text":":","type":"text"}]},{"code":["class MyAudioBanner: UIViewController, PSReaderUI.AudioBannerViewController {","","    var isFloating: Bool { true }","","    override func viewDidLoad() {","        super.viewDidLoad()","        \/\/ Build your compact audio control UI (play\/pause, progress, etc.)","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"isFloating","type":"codeVoice"},{"text":" property controls how the banner is positioned:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"code":"true","type":"codeVoice"}]},{"type":"text","text":" — the banner floats above the reader content, pinned to the"},{"type":"text","text":" "},{"type":"text","text":"bottom of the screen. The SDK automatically applies a bottom safe-area inset"},{"type":"text","text":" "},{"type":"text","text":"equal to the banner’s height so content is not obscured."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"codeVoice","code":"false"}]},{"type":"text","text":" — the banner is stacked below the reader. The reader’s available"},{"type":"text","text":" "},{"type":"text","text":"height is reduced accordingly."}]}]}]},{"inlineContent":[{"text":"Banner visibility is driven by the view’s own layout. Set an intrinsic content","type":"text"},{"text":" ","type":"text"},{"text":"height (via Auto Layout constraints) to show the banner. Collapse the height to","type":"text"},{"text":" ","type":"text"},{"text":"zero to hide it. The SDK does not call show\/hide methods — it reads the","type":"text"},{"text":" ","type":"text"},{"text":"banner’s layout directly.","type":"text"}],"type":"paragraph"},{"level":3,"anchor":"Choosing-a-Pattern","text":"Choosing a Pattern","type":"heading"},{"header":"row","rows":[[[{"inlineContent":[{"type":"text","text":"Pattern"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Best for"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Default provider","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"Transient overlay"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Most integrations — simple, no custom UI needed"}],"type":"paragraph"}],[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider"},{"type":"text","text":" provides this out of the box"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"Persistent banner"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Apps with their own audio system or “now playing” UI","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Requires a custom ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate"},{"text":" implementation","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"Both","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Overlay for on-demand playback, banner for persistent controls"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Requires a custom "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate","isActive":true},{"type":"text","text":" returning both"}],"type":"paragraph"}]]],"type":"table"},{"level":2,"anchor":"Customizing-the-Overlay","text":"Customizing the Overlay","type":"heading"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlayConfiguration","isActive":true},{"type":"text","text":" struct controls the appearance of the"},{"type":"text","text":" "},{"type":"text","text":"default audio overlay. It inherits defaults from "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","isActive":true},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"text","text":"can be customized before passing to "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","isActive":true},{"type":"text","text":":"}],"type":"paragraph"},{"syntax":"swift","code":["var ttsConfig = PSReaderUI.AudioOverlayConfiguration(globalConfig: globalConfig)","","\/\/ Accent color for the play button and progress bar","ttsConfig.brandColor = .systemBlue","","\/\/ Overlay background","ttsConfig.backgroundColor = .secondarySystemBackground","","\/\/ Article title (defaults: primaryFont bold, 18pt)","ttsConfig.titleLabel = LabelConfiguration(","    font: .systemFont(ofSize: 18, weight: .bold),","    pointSize: 18,","    color: .label",")","","\/\/ Secondary info line (defaults: primaryFont, 14pt)","ttsConfig.subtitleLabel = LabelConfiguration(","    font: .systemFont(ofSize: 14),","    pointSize: 14,","    color: .secondaryLabel",")","","\/\/ Elapsed time display (defaults: primaryFont, 12pt)","ttsConfig.elapsedLabel = LabelConfiguration(","    font: .monospacedDigitSystemFont(ofSize: 12, weight: .regular),","    pointSize: 12,","    color: .tertiaryLabel",")","","\/\/ Remaining time display (defaults: primaryFont, 12pt)","ttsConfig.remainingLabel = LabelConfiguration(","    font: .monospacedDigitSystemFont(ofSize: 12, weight: .regular),","    pointSize: 12,","    color: .tertiaryLabel",")","","\/\/ Custom playback icons","ttsConfig.assetDelegate = MyAssetDelegate()","","\/\/ iOS 26+ Liquid Glass effect (defaults to global value)","ttsConfig.liquidGlassPolicy = .automatic","","let ttsProvider = PSReaderUI.DefaultTextToSpeechProvider(configuration: ttsConfig)","globalConfig.audioDelegate = ttsProvider"],"type":"codeListing"},{"level":2,"anchor":"Handling-Page-Navigation","text":"Handling Page Navigation","type":"heading"},{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate"},{"type":"text","text":" protocol includes methods that the SDK calls when the"},{"type":"text","text":" "},{"type":"text","text":"user navigates to a different page or spread:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"code":"didChangeTo(page:inEdition:inPublished:)","type":"codeVoice"},{"text":" — called for feed edition","type":"text"},{"text":" ","type":"text"},{"text":"navigation.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"didChangeTo(spread:inReplicaEdition:)","type":"codeVoice"},{"type":"text","text":" — called for replica edition"},{"type":"text","text":" "},{"type":"text","text":"navigation."}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","isActive":true,"type":"reference"},{"type":"text","text":" uses these methods to automatically stop"},{"type":"text","text":" "},{"type":"text","text":"playback when the user navigates away from the article that is currently"},{"type":"text","text":" "},{"type":"text","text":"playing. If the user navigates back to the same article, playback resumes from"},{"type":"text","text":" "},{"type":"text","text":"where it left off."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If you implement a custom "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate","type":"reference","isActive":true},{"type":"text","text":", use these methods to pause or stop"},{"type":"text","text":" "},{"type":"text","text":"your audio player, update banner state, or perform any cleanup needed when the"},{"type":"text","text":" "},{"type":"text","text":"user moves between pages."}],"type":"paragraph"},{"level":2,"anchor":"Audio-Session-Management","text":"Audio Session Management","type":"heading"},{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioSessionProvider","type":"reference"},{"type":"text","text":" protocol manages "},{"code":"AVAudioSession","type":"codeVoice"},{"type":"text","text":" activation and"},{"type":"text","text":" "},{"type":"text","text":"deactivation around playback. The default implementation"},{"type":"text","text":" "},{"type":"text","text":"("},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultAudioSessionProvider","type":"reference"},{"type":"text","text":") configures the session for "},{"code":".playback","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"category, enabling background audio."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Override it if your app has specific audio session requirements — for example,"},{"type":"text","text":" "},{"type":"text","text":"mixing with other audio sources or handling interruptions differently:"}],"type":"paragraph"},{"syntax":"swift","code":["struct MyAudioSessionProvider: PSReaderUI.AudioSessionProvider {","    func setupAudioSession(for article: PSEArticle, inEdition source: PSEEditionSource) throws {","        let session = AVAudioSession.sharedInstance()","        try session.setCategory(.playback, options: .mixWithOthers)","        try session.setActive(true)","    }","","    func deactivateAudioSession(for article: PSEArticle, inEdition source: PSEEditionSource) throws {","        try AVAudioSession.sharedInstance().setActive(false, options: .notifyOthersOnDeactivation)","    }","}"],"type":"codeListing"},{"inlineContent":[{"text":"The protocol also defines matching methods for replica editions","type":"text"},{"text":" ","type":"text"},{"text":"(","type":"text"},{"code":"setupAudioSession(for:inReplicaEdition:)","type":"codeVoice"},{"text":" and","type":"text"},{"text":" ","type":"text"},{"code":"deactivateAudioSession(for:inReplicaEdition:)","type":"codeVoice"},{"text":") with default implementations","type":"text"},{"text":" ","type":"text"},{"text":"that delegate to the feed edition methods.","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"Custom-AudioDelegate","text":"Custom AudioDelegate","type":"heading"},{"inlineContent":[{"type":"text","text":"For full control over the audio experience, implement "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate"},{"type":"text","text":" "},{"type":"text","text":"directly. This is an advanced pattern for apps that manage their own audio"},{"type":"text","text":" "},{"type":"text","text":"system entirely — for example, using a persistent “now playing” banner with an"},{"type":"text","text":" "},{"type":"text","text":"external audio manager instead of the SDK’s built-in overlay."}],"type":"paragraph"},{"syntax":"swift","code":["class MyAudioDelegate: PSReaderUI.AudioDelegate {","","    let audioManager: MyAudioManager","","    \/\/ MARK: Feed Edition Methods","","    func isListenable(page: PSEPage, inEdition source: PSEEditionSource) -> Bool {","        return page.articles?.count == 1","    }","","    func audioBannerViewController() -> AudioBannerViewController? {","        \/\/ Return a persistent banner, or nil for overlay-only","        return MyAudioBanner(audioManager: audioManager)","    }","","    func playAudio(for page: PSEPage, inEdition source: PSEEditionSource) -> AudioOverlay? {","        guard let article = page.articles?.first else { return nil }","","        \/\/ Start playback through your own audio manager","        audioManager.play(article: article)","","        \/\/ Return nil — the banner handles the UI","        return nil","    }","","    func didChangeTo(page: PSEPage?,","                     inEdition edition: PSEEdition,","                     inPublished published: PSEPublished) {","        audioManager.pause()","    }","","    \/\/ MARK: Replica Edition Methods","","    func isListenable(spread: PSReplicaPageSpread,","                      inReplicaEdition replicaEdition: PSReplicaEdition) -> Bool {","        return spread.isArticle","    }","","    func playAudio(forSpread spread: PSReplicaPageSpread,","                   inReplicaEdition replicaEdition: PSReplicaEdition) -> AudioOverlay? {","        guard case .article(let article) = spread else { return nil }","        audioManager.play(replicaArticle: article)","        return nil","    }","","    func didChangeTo(spread: PSReplicaPageSpread?,","                     inReplicaEdition replicaEdition: PSReplicaEdition) {","        audioManager.pause()","    }","}","","globalConfig.audioDelegate = MyAudioDelegate(audioManager: myAudioManager)"],"type":"codeListing"},{"style":"tip","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you return "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" from both "},{"type":"codeVoice","code":"playAudio"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"codeVoice","code":"audioBannerViewController()"},{"type":"text","text":", the SDK will not present any audio UI. Use this"},{"type":"text","text":" "},{"type":"text","text":"when your app manages the entire audio experience externally."}]}],"type":"aside","name":"Tip"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","interfaceLanguage":"swift"},"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioOverlayConfiguration":{"title":"AudioOverlayConfiguration","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlayConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOverlayConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"AudioOverlayConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration structure for customizing the appearance of audio overlays."}],"kind":"symbol","role":"symbol","url":"\/documentation\/psreaderui\/audiooverlayconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/TextToSpeechArticleFormatter":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Protocol for formatting articles into text suitable for speech synthesis."}],"url":"\/documentation\/psreaderui\/texttospeecharticleformatter","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextToSpeechArticleFormatter","kind":"identifier"}],"title":"TextToSpeechArticleFormatter","navigatorTitle":[{"text":"TextToSpeechArticleFormatter","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechArticleFormatter"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioOverlay":{"title":"AudioOverlay","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOverlay"}],"navigatorTitle":[{"kind":"identifier","text":"AudioOverlay"}],"kind":"symbol","abstract":[{"text":"A custom view controller designed for presenting audio playback interfaces as overlays.","type":"text"}],"type":"topic","url":"\/documentation\/psreaderui\/audiooverlay","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioDelegate":{"title":"AudioDelegate","abstract":[{"type":"text","text":"Delegate protocol used to provide audio playback functionality within the SDK."}],"url":"\/documentation\/psreaderui\/audiodelegate","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AudioDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDelegate","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioBannerViewController":{"title":"AudioBannerViewController","role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioBannerViewController","kind":"symbol","abstract":[{"type":"text","text":"A view controller used to present persistent audio controls as a banner."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioBannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"AudioBannerViewController"}],"url":"\/documentation\/psreaderui\/audiobannerviewcontroller","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/TextToSpeechSynthesizer":{"url":"\/documentation\/psreaderui\/texttospeechsynthesizer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextToSpeechSynthesizer"}],"navigatorTitle":[{"kind":"identifier","text":"TextToSpeechSynthesizer"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechSynthesizer","role":"symbol","type":"topic","title":"TextToSpeechSynthesizer","abstract":[{"type":"text","text":"Protocol for synthesizing text into speech audio."}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"kind":"article","title":"Media Playback","url":"\/documentation\/psreaderui\/media-playback","type":"topic","role":"article","abstract":[{"text":"Enable video and media playback within the reader.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"type":"topic","title":"Analytics","abstract":[{"text":"Track user interactions and content engagement across the PSReaderUI SDK.","type":"text"}],"url":"\/documentation\/psreaderui\/analytics","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","kind":"article","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"title":"Paywall Integration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","abstract":[{"text":"Restrict access to premium content with custom paywall screens.","type":"text"}],"url":"\/documentation\/psreaderui\/paywall-integration","type":"topic","kind":"article","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultAudioSessionProvider":{"title":"DefaultAudioSessionProvider","role":"symbol","type":"topic","abstract":[{"text":"Default implementation of audio session management.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultAudioSessionProvider","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultAudioSessionProvider","navigatorTitle":[{"text":"DefaultAudioSessionProvider","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/psreaderui\/defaultaudiosessionprovider"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultTextToSpeechArticleFormatter":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechArticleFormatter","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultTextToSpeechArticleFormatter"}],"role":"symbol","url":"\/documentation\/psreaderui\/defaulttexttospeecharticleformatter","navigatorTitle":[{"kind":"identifier","text":"DefaultTextToSpeechArticleFormatter"}],"abstract":[{"type":"text","text":"Default implementation of text-to-speech article formatting."}],"kind":"symbol","type":"topic","title":"DefaultTextToSpeechArticleFormatter"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"type":"topic","kind":"article","url":"\/documentation\/psreaderui\/sharing","title":"Sharing","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioSessionProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioSessionProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AudioSessionProvider","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioSessionProvider","kind":"symbol","abstract":[{"type":"text","text":"Protocol for managing audio session lifecycle and interruption handling."}],"url":"\/documentation\/psreaderui\/audiosessionprovider","type":"topic","title":"AudioSessionProvider"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultTextToSpeechProvider":{"url":"\/documentation\/psreaderui\/defaulttexttospeechprovider","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultTextToSpeechProvider"}],"abstract":[{"text":"A complete text-to-speech implementation providing ready-to-use audio functionality.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"DefaultTextToSpeechProvider","navigatorTitle":[{"text":"DefaultTextToSpeechProvider","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","type":"topic","role":"symbol","title":"GlobalConfiguration","abstract":[{"type":"text","text":"A configuration object that provides global settings and delegates for"},{"type":"text","text":" "},{"type":"text","text":"customizing the SDK’s behavior and appearance."}],"navigatorTitle":[{"kind":"identifier","text":"GlobalConfiguration"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlobalConfiguration"}],"url":"\/documentation\/psreaderui\/globalconfiguration","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"url":"\/documentation\/psreaderui\/advertisements","type":"topic","abstract":[{"text":"Display custom advertisements within the reader.","type":"text"}],"kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","role":"article","title":"Advertisements"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"url":"\/documentation\/psreaderui","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"role":"collection"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultTextToSpeechSynthesizer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultTextToSpeechSynthesizer"}],"kind":"symbol","title":"DefaultTextToSpeechSynthesizer","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechSynthesizer","navigatorTitle":[{"kind":"identifier","text":"DefaultTextToSpeechSynthesizer"}],"url":"\/documentation\/psreaderui\/defaulttexttospeechsynthesizer","abstract":[{"type":"text","text":"Default implementation of text-to-speech synthesis using the system’s TTS capabilities."}],"role":"symbol","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioDelegate/audioBannerViewController()":{"title":"audioBannerViewController()","abstract":[{"text":"Provides a persistent banner view controller for audio controls.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate\/audioBannerViewController()","url":"\/documentation\/psreaderui\/audiodelegate\/audiobannerviewcontroller()","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioBannerViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10PSReaderUI25AudioBannerViewControllerP","text":"AudioBannerViewController"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"anchor":"Features","title":"Features"}]}]}]}