{"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"text":"PSReaderUI is designed to be customized. The configuration system follows a","type":"text"},{"text":" ","type":"text"},{"text":"cascading hierarchy: ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","type":"reference"},{"text":" supplies default values that flow","type":"text"},{"text":" ","type":"text"},{"text":"into ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselConfiguration","type":"reference"},{"text":", ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","type":"reference"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration","isActive":true},{"type":"text","text":", and their sub-configurations. Override any value at"},{"type":"text","text":" "},{"type":"text","text":"any level to apply targeted changes."}],"type":"paragraph"},{"level":2,"text":"Configuration Hierarchy","anchor":"Configuration-Hierarchy","type":"heading"},{"inlineContent":[{"type":"text","text":"When you create a "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselConfiguration","isActive":true},{"type":"text","text":" or "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","isActive":true},{"type":"text","text":", pass"},{"type":"text","text":" "},{"type":"text","text":"your "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","isActive":true},{"type":"text","text":" to its initializer. The child configuration"},{"type":"text","text":" "},{"type":"text","text":"inherits the global fonts, brand color, delegates, and other settings. You"},{"text":" ","type":"text"},{"text":"can then override individual properties without affecting the rest:","type":"text"}],"type":"paragraph"},{"code":["let globalConfig = PSReaderUI.GlobalConfiguration(","    apiKey: apiKey,","    accountGUID: accountGUID,","    primaryFont: UIFont(name: \"Georgia\", size: 12)!,","    secondaryFont: .systemFont(ofSize: 12),","    brandColor: .systemBlue",")","","var carouselConfig = PSReaderUI.CarouselConfiguration(globalConfig: globalConfig)","carouselConfig.sectionRibbon.layout = .fillEqually","\/\/ brandColor, fonts, etc. are inherited from globalConfig"],"syntax":"swift","type":"codeListing"},{"level":2,"text":"Fonts","anchor":"Fonts","type":"heading"},{"inlineContent":[{"type":"text","text":"Two font families control the SDK’s typography:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"inlineContent":[{"code":"primaryFont","type":"codeVoice"}],"type":"strong"},{"text":" — used for titles, headlines, publication names, and other","type":"text"},{"text":" ","type":"text"},{"text":"prominent text. Set on ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration\/primaryFont","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"codeVoice","code":"secondaryFont"}]},{"type":"text","text":" — used for labels, dates, captions, and secondary UI"},{"type":"text","text":" "},{"type":"text","text":"elements. Set on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration\/secondaryFont"},{"type":"text","text":"."}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Individual components expose "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LabelConfiguration","isActive":true,"type":"reference"},{"type":"text","text":" properties that let you"},{"type":"text","text":" "},{"type":"text","text":"override the font, point size, and color for specific labels without changing"},{"type":"text","text":" "},{"type":"text","text":"the global fonts:"}],"type":"paragraph"},{"code":["var archiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","archiveConfig.editionNameLabel = LabelConfiguration(","    font: UIFont(name: \"Georgia-Bold\", size: 14)!,","    pointSize: 14,","    color: .label",")"],"syntax":"swift","type":"codeListing"},{"level":2,"text":"Brand Color","anchor":"Brand-Color","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration\/brandColor","type":"reference","isActive":true},{"text":" is used as an accent color throughout","type":"text"},{"text":" ","type":"text"},{"text":"the SDK — in selection states, progress indicators, and interactive elements.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To support both light and dark appearances, provide a dynamic color:"}]},{"type":"codeListing","syntax":"swift","code":["let brandColor = UIColor(dynamicProvider: {","    $0.userInterfaceStyle == .dark ? .white : .black","})"]},{"type":"paragraph","inlineContent":[{"text":"Or define the color in your asset catalog for automatic trait resolution.","type":"text"}]},{"type":"heading","text":"Thumbnail Content Mode","level":2,"anchor":"Thumbnail-Content-Mode"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode","isActive":true},{"type":"text","text":" enum controls how edition thumbnails are sized and"},{"type":"text","text":" "},{"type":"text","text":"positioned within their containers across archive, bookmarks, downloads, and"},{"type":"text","text":" "},{"type":"text","text":"splash screens. This is one of the most impactful visual customization points"},{"type":"text","text":" "},{"type":"text","text":"— it determines the layout feel of your archive grid."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"There are three modes:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode\/fitToWidth","type":"reference","isActive":true}]},{"text":" — the image fills the container’s width","type":"text"},{"text":" ","type":"text"},{"text":"and is cropped vertically if the aspect ratio differs. This is the default","type":"text"},{"text":" ","type":"text"},{"text":"for archives, bookmarks, and downloads.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode\/fitToHeight","type":"reference","isActive":true}]},{"type":"text","text":" — the image fills the container’s"},{"type":"text","text":" "},{"type":"text","text":"height and is cropped horizontally if needed. This is the default for the"},{"type":"text","text":" "},{"type":"text","text":"reader splash screen."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode\/flexibleHeight(estimatedAspectRatio:)","isActive":true}]},{"text":" — the image","type":"text"},{"text":" ","type":"text"},{"text":"fills the container’s width while the cell height adjusts dynamically to","type":"text"},{"text":" ","type":"text"},{"text":"preserve the image’s natural aspect ratio. Provide an ","type":"text"},{"code":"estimatedAspectRatio","type":"codeVoice"},{"text":" ","type":"text"},{"text":"to stabilize layout during loading; the SDK refines it automatically once","type":"text"},{"text":" ","type":"text"},{"text":"images arrive.","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"text":"Set the content mode on any configuration that displays thumbnails:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["var archiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","","\/\/ Fixed-height cells that crop vertically (default)","archiveConfig.thumbnailContentMode = .fitToWidth","","\/\/ Dynamic-height cells that show the full image","archiveConfig.thumbnailContentMode = .flexibleHeight(estimatedAspectRatio: 0.75)"]},{"inlineContent":[{"text":"Pair the content mode with ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration\/cellAspectRatio","isActive":true,"type":"reference"},{"text":" (or the","type":"text"},{"text":" ","type":"text"},{"text":"equivalent ","type":"text"},{"type":"codeVoice","code":"aspectRatio"},{"text":" on ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksConfiguration","isActive":true,"type":"reference"},{"text":" and","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsConfiguration","isActive":true,"type":"reference"},{"text":") to fine-tune the grid dimensions.","type":"text"}],"type":"paragraph"},{"style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode\/flexibleHeight(estimatedAspectRatio:)","isActive":true},{"type":"text","text":" is not"},{"type":"text","text":" "},{"type":"text","text":"supported in the bookmarks or downloads views."}],"type":"paragraph"}],"type":"aside"},{"level":2,"type":"heading","text":"Dark Mode","anchor":"Dark-Mode"},{"inlineContent":[{"text":"The SDK respects the system appearance by default. To force a specific style","type":"text"},{"text":" ","type":"text"},{"text":"across the entire SDK, set ","type":"text"},{"type":"codeVoice","code":"overrideUserInterfaceStyle"},{"text":" on the","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","isActive":true,"type":"reference"},{"text":":","type":"text"}],"type":"paragraph"},{"code":["carouselVC.overrideUserInterfaceStyle = .dark"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"This propagates to all child view controllers, including the reader, archive,"},{"type":"text","text":" "},{"type":"text","text":"bookmarks, and downloads views."}],"type":"paragraph"},{"level":2,"type":"heading","text":"Liquid Glass (iOS 26+)","anchor":"Liquid-Glass-iOS-26+"},{"inlineContent":[{"text":"On iOS 26 and later, the SDK adopts the Liquid Glass design language by","type":"text"},{"text":" ","type":"text"},{"text":"default. The ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LiquidGlassPolicy","isActive":true,"type":"reference"},{"text":" enum controls this behavior:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"code":".automatic","type":"codeVoice"}]},{"type":"text","text":" (default) — uses Liquid Glass on iOS 26+ when supported."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"codeVoice","code":".disabled"}],"type":"strong"},{"type":"text","text":" — uses the standard appearance on all OS versions."}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Set the policy globally or on specific configuration objects for granular"},{"type":"text","text":" "},{"type":"text","text":"control:"}],"type":"paragraph"},{"code":["\/\/ Disable globally","globalConfig.liquidGlassPolicy = .disabled","","\/\/ Or disable only on the subsection ribbon","carouselConfig.subsectionRibbon.liquidGlassPolicy = .disabled"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"The SDK also respects the host app’s "},{"type":"codeVoice","code":"UIDesignRequiresCompatibility"},{"type":"text","text":" "},{"type":"text","text":"Info.plist key and will fall back automatically when set."}],"type":"paragraph"},{"level":2,"type":"heading","text":"Custom Icons","anchor":"Custom-Icons"},{"inlineContent":[{"text":"Implement ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate","type":"reference"},{"text":" to replace any of the SDK’s built-in icons with","type":"text"},{"text":" ","type":"text"},{"text":"your own images. See the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageResourceName","type":"reference"},{"text":" symbol page for the full list","type":"text"},{"text":" ","type":"text"},{"text":"of icon identifiers and their usage context.","type":"text"}],"type":"paragraph"},{"code":["struct MyAssetDelegate: PSReaderUI.AssetDelegate {","    func imageResource(for name: ImageResourceName) -> UIImage? {","        switch name {","        case .share:","            return UIImage(named: \"my-share-icon\")","        default:","            return name.defaultImage()","        }","    }","}","","globalConfig.assetDelegate = MyAssetDelegate()"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"For the legacy replica reader, override"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate\/legacyImageResource(for:)","type":"reference"},{"type":"text","text":" using "},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyImageResourceName","type":"reference"},{"type":"text","text":" "},{"type":"text","text":"identifiers."}],"type":"paragraph"},{"level":2,"type":"heading","text":"Placeholder Images","anchor":"Placeholder-Images"},{"inlineContent":[{"type":"text","text":"The SDK can use placeholder images when a thumbnail is unavailable — for"},{"type":"text","text":" "},{"type":"text","text":"example, when an article has no associated image or a thumbnail fails to load."},{"type":"text","text":" "},{"type":"text","text":"By default the SDK shows a solid skeleton view (a grey box that adapts to"},{"type":"text","text":" "},{"type":"text","text":"light and dark mode). Implement"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate\/placeholderImage(size:with:completion:)"},{"type":"text","text":" to provide a custom"},{"type":"text","text":" "},{"type":"text","text":"placeholder instead:"}],"type":"paragraph"},{"code":["struct MyAssetDelegate: PSReaderUI.AssetDelegate {","    func placeholderImage(","        size: CGSize,","        with traits: UITraitCollection,","        completion: @escaping (UIImage?) -> Void","    ) {","        let name = traits.userInterfaceStyle == .dark","            ? \"placeholder-dark\"","            : \"placeholder-light\"","","        let image = UIImage(named: name)","        completion(image)","    }","}","","globalConfig.assetDelegate = MyAssetDelegate()"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"size"},{"text":" parameter reflects the thumbnail container’s dimensions, which you","type":"text"},{"text":" ","type":"text"},{"text":"can use to select or generate an appropriately sized image. The ","type":"text"},{"type":"codeVoice","code":"traits"},{"text":" ","type":"text"},{"text":"parameter carries the current ","type":"text"},{"type":"codeVoice","code":"UITraitCollection"},{"text":" — use it to adapt to","type":"text"},{"text":" ","type":"text"},{"text":"light or dark mode via ","type":"text"},{"type":"codeVoice","code":"userInterfaceStyle"},{"text":", or to account for display scale,","type":"text"},{"text":" ","type":"text"},{"text":"size classes, and other environment traits.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" from the completion handler to keep the current placeholder"},{"type":"text","text":" "},{"type":"text","text":"presentation unchanged."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The asset delegate is inherited from "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","isActive":true},{"type":"text","text":" by default. To"},{"type":"text","text":" "},{"type":"text","text":"use a different delegate specifically for bookmarks, set it directly on the"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksConfiguration\/assetDelegate","isActive":true},{"type":"text","text":" property."}],"type":"paragraph"},{"level":2,"type":"heading","text":"Date Formatting","anchor":"Date-Formatting"},{"inlineContent":[{"type":"text","text":"Edition dates are formatted through the "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EditionDateFormatter","type":"reference","isActive":true},{"type":"text","text":" protocol."},{"type":"text","text":" "},{"type":"text","text":"The SDK provides "},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultEditionDateFormatter","type":"reference","isActive":true},{"type":"text","text":", which wraps a standard"},{"type":"text","text":" "},{"code":"DateFormatter","type":"codeVoice"},{"type":"text","text":":"}],"type":"paragraph"},{"code":["let dateFormatter = DefaultEditionDateFormatter(","    dateFormat: \"d MMMM yyyy\",","    timeZone: .current",")","globalConfig.dateFormatter = dateFormatter"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"If your publications use custom names instead of dates, implement","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EditionDateFormatter","isActive":true,"type":"reference"},{"text":" to return the appropriate label for each edition.","type":"text"}],"type":"paragraph"},{"text":"Ribbon and Navigation Customization","type":"heading","level":2,"anchor":"Ribbon-and-Navigation-Customization"},{"inlineContent":[{"type":"text","text":"The carousel’s section and subsection ribbons are configurable via"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SectionRibbonConfiguration"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SubsectionRibbonConfiguration"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["carouselConfig.sectionRibbon.layout = .fillEqually  \/\/ or .fitLeft, .fitCenter","carouselConfig.subsectionRibbon.alignment = .center  \/\/ or .left"]},{"inlineContent":[{"text":"The reader navigation bar appearance is controlled through","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderNavigationBarConfiguration","type":"reference"},{"text":" on the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration","type":"reference"},{"text":":","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["var archiveConfig = PSReaderUI.ArchiveConfiguration(globalConfig: globalConfig)","archiveConfig.readerConfig.navigationBar.titleLabel.color = .label"]},{"text":"Content Browser","type":"heading","level":2,"anchor":"Content-Browser"},{"inlineContent":[{"type":"text","text":"The reader’s content browser is the panel that lets users navigate between"},{"type":"text","text":" "},{"type":"text","text":"sections, pages, and articles within an open edition. It is configured via"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderBrowserConfiguration","type":"reference"},{"type":"text","text":", which provides independent control over fonts,"},{"type":"text","text":" "},{"type":"text","text":"colors, and the Liquid Glass policy. Customize the browser without affecting"},{"type":"text","text":" "},{"type":"text","text":"the rest of the reader by setting properties on"},{"type":"text","text":" "},{"code":"archiveConfig.readerConfig.browserConfig","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"level":2,"text":"Legacy Replica Reader","type":"heading","anchor":"Legacy-Replica-Reader"},{"type":"paragraph","inlineContent":[{"text":"When using the legacy replica reader","type":"text"},{"text":" ","type":"text"},{"text":"(","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration\/useLegacyReplicaReader","type":"reference"},{"text":" is ","type":"text"},{"code":"true","type":"codeVoice"},{"text":"), additional","type":"text"},{"text":" ","type":"text"},{"text":"customization options are available through ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyReaderConfiguration","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This includes navigation bar items, share templating, and legacy-specific","type":"text"},{"text":" ","type":"text"},{"text":"icon overrides via ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyImageResourceName","type":"reference"},{"text":".","type":"text"}]}]}],"abstract":[{"type":"text","text":"Adjust fonts, colors, icons, and layouts to match your app’s brand."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"PSReaderUI"}],"role":"article","title":"Theming and Customization","roleHeading":"Article"},"seeAlsoSections":[{"title":"Customization","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"],"anchor":"Customization","generated":true}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/psreaderui\/theming-and-customization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/psreaderui\/theming-and-customization"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"]]},"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Carousel-Setup":{"role":"article","type":"topic","abstract":[{"text":"Configure the carousel’s sections, content sources, and layout.","type":"text"}],"title":"Carousel Setup","kind":"article","url":"\/documentation\/psreaderui\/carousel-setup","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveConfiguration":{"title":"ArchiveConfiguration","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration for customizing the appearance and behavior of publication archive views."}],"url":"\/documentation\/psreaderui\/archiveconfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArchiveConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","navigatorTitle":[{"text":"ArchiveConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ImageContentMode/fitToHeight":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode\/fitToHeight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fitToHeight"}],"title":"ImageContentMode.fitToHeight","abstract":[{"type":"text","text":"The image is scaled proportionally to fit the height of its container,"},{"type":"text","text":" "},{"type":"text","text":"potentially cropping horizontally."}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/psreaderui\/imagecontentmode\/fittoheight"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SectionRibbonConfiguration":{"url":"\/documentation\/psreaderui\/sectionribbonconfiguration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SectionRibbonConfiguration","title":"SectionRibbonConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration object controlling the appearance and layout of the carousel section ribbon."}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SectionRibbonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SectionRibbonConfiguration"}],"role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","url":"\/documentation\/psreaderui","role":"collection","type":"topic","abstract":[{"text":"A UI framework for building digital newspaper and magazine reader experiences on iOS.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ImageContentMode":{"abstract":[{"text":"Defines how an image should be resized and positioned within its container.","type":"text"}],"title":"ImageContentMode","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode","role":"symbol","kind":"symbol","url":"\/documentation\/psreaderui\/imagecontentmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageContentMode","kind":"identifier"}],"navigatorTitle":[{"text":"ImageContentMode","kind":"identifier"}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AssetDelegate/placeholderImage(size:with:completion:)":{"abstract":[{"text":"Provides a placeholder image for content that is unavailable.","type":"text"}],"type":"topic","title":"placeholderImage(size:with:completion:)","url":"\/documentation\/psreaderui\/assetdelegate\/placeholderimage(size:with:completion:)","kind":"symbol","required":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate\/placeholderImage(size:with:completion:)","role":"symbol","defaultImplementations":1,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Standalone-View-Controllers":{"type":"topic","url":"\/documentation\/psreaderui\/standalone-view-controllers","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","title":"Standalone View Controllers","abstract":[{"type":"text","text":"Use archive, bookmarks, downloads, and search views outside of the carousel."}],"kind":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ImageResourceName":{"type":"topic","abstract":[{"text":"An enumeration of asset identifiers used by the SDK’s UI components.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageResourceName","url":"\/documentation\/psreaderui\/imageresourcename","title":"ImageResourceName","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageResourceName","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ImageResourceName","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration/primaryFont":{"kind":"symbol","abstract":[{"type":"text","text":"The primary font used throughout the SDK’s UI. This is used when emphasis is desired."}],"url":"\/documentation\/psreaderui\/globalconfiguration\/primaryfont","type":"topic","role":"symbol","title":"primaryFont","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration\/primaryFont","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AssetDelegate":{"role":"symbol","kind":"symbol","title":"AssetDelegate","type":"topic","abstract":[{"text":"A delegate protocol for providing custom images and logos used within the SDK.","type":"text"}],"url":"\/documentation\/psreaderui\/assetdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AssetDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AssetDelegate"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EditionDateFormatter":{"role":"symbol","title":"EditionDateFormatter","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EditionDateFormatter"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EditionDateFormatter"}],"url":"\/documentation\/psreaderui\/editiondateformatter","abstract":[{"text":"A protocol defining methods for generating display strings to represent editions.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EditionDateFormatter"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderConfiguration":{"abstract":[{"type":"text","text":"Configuration object for customizing the PSReaderUI Reader."}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration","url":"\/documentation\/psreaderui\/readerconfiguration","role":"symbol","navigatorTitle":[{"text":"ReaderConfiguration","kind":"identifier"}],"kind":"symbol","title":"ReaderConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LegacyReaderConfiguration":{"url":"\/documentation\/psreaderui\/legacyreaderconfiguration","type":"topic","abstract":[{"text":"Configuration object for customizing the appearance, behavior, and sharing","type":"text"},{"text":" ","type":"text"},{"text":"strategies of the legacy replica reader.","type":"text"}],"kind":"symbol","title":"LegacyReaderConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegacyReaderConfiguration"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyReaderConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LegacyReaderConfiguration"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderNavigationBarConfiguration":{"url":"\/documentation\/psreaderui\/readernavigationbarconfiguration","title":"ReaderNavigationBarConfiguration","role":"symbol","navigatorTitle":[{"text":"ReaderNavigationBarConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration object for customizing reader navigation bars."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderNavigationBarConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderNavigationBarConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultEditionDateFormatter":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultEditionDateFormatter","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultEditionDateFormatter","type":"topic","navigatorTitle":[{"text":"DefaultEditionDateFormatter","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Default implementation of "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EditionDateFormatter","isActive":true},{"type":"text","text":" using "},{"code":"DateFormatter","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/psreaderui\/defaulteditiondateformatter","title":"DefaultEditionDateFormatter","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/BookmarksConfiguration/assetDelegate":{"url":"\/documentation\/psreaderui\/bookmarksconfiguration\/assetdelegate","abstract":[{"type":"text","text":"Delegate providing custom images used within the bookmarks view."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksConfiguration\/assetDelegate","kind":"symbol","title":"assetDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"assetDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AssetDelegate","preciseIdentifier":"s:10PSReaderUI13AssetDelegateP"}],"type":"topic","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","abstract":[{"type":"text","text":"The primary view controller provided by the SDK for presenting digital publication"},{"type":"text","text":" "},{"type":"text","text":"content through an intuitive carousel interface."}],"url":"\/documentation\/psreaderui\/carouselviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CarouselViewController","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"CarouselViewController","kind":"identifier"}],"title":"CarouselViewController","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ImageContentMode/fitToWidth":{"title":"ImageContentMode.fitToWidth","url":"\/documentation\/psreaderui\/imagecontentmode\/fittowidth","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fitToWidth","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The image is scaled proportionally to fit the width of its container,"},{"type":"text","text":" "},{"type":"text","text":"potentially cropping vertically."}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode\/fitToWidth"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/BookmarksConfiguration":{"url":"\/documentation\/psreaderui\/bookmarksconfiguration","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksConfiguration","role":"symbol","navigatorTitle":[{"text":"BookmarksConfiguration","kind":"identifier"}],"title":"BookmarksConfiguration","abstract":[{"text":"Configuration for customizing the appearance and behavior of bookmark archives.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BookmarksConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AssetDelegate/legacyImageResource(for:)":{"title":"legacyImageResource(for:)","url":"\/documentation\/psreaderui\/assetdelegate\/legacyimageresource(for:)","kind":"symbol","abstract":[{"text":"Provides a custom image for legacy reader components.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate\/legacyImageResource(for:)","required":true,"type":"topic","defaultImplementations":1,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacyImageResource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LegacyImageResourceName","preciseIdentifier":"s:10PSReaderUI23LegacyImageResourceNameO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ImageContentMode/flexibleHeight(estimatedAspectRatio:)":{"title":"ImageContentMode.flexibleHeight(estimatedAspectRatio:)","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode\/flexibleHeight(estimatedAspectRatio:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flexibleHeight","kind":"identifier"},{"text":"(","kind":"text"},{"text":"estimatedAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/psreaderui\/imagecontentmode\/flexibleheight(estimatedaspectratio:)","abstract":[{"type":"text","text":"The image is scaled proportionally to fit the width of its container,"},{"type":"text","text":" "},{"type":"text","text":"while the height adjusts dynamically maintaining the images aspect ratio."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselConfiguration":{"url":"\/documentation\/psreaderui\/carouselconfiguration","abstract":[{"type":"text","text":"Configuration object for customizing the PSReaderUI carousel interface."}],"navigatorTitle":[{"kind":"identifier","text":"CarouselConfiguration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarouselConfiguration"}],"title":"CarouselConfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselConfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration/brandColor":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration\/brandColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"brandColor","kind":"symbol","abstract":[{"type":"text","text":"The primary brand \/ accent color used throughout the SDK’s interface."}],"url":"\/documentation\/psreaderui\/globalconfiguration\/brandcolor","role":"symbol","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"GlobalConfiguration"}],"url":"\/documentation\/psreaderui\/globalconfiguration","role":"symbol","title":"GlobalConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlobalConfiguration"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","kind":"symbol","abstract":[{"type":"text","text":"A configuration object that provides global settings and delegates for"},{"type":"text","text":" "},{"type":"text","text":"customizing the SDK’s behavior and appearance."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DownloadsConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration for customizing the appearance and behavior of download archives."}],"title":"DownloadsConfiguration","role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsConfiguration","type":"topic","url":"\/documentation\/psreaderui\/downloadsconfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadsConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DownloadsConfiguration"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderBrowserConfiguration":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderBrowserConfiguration","kind":"identifier"}],"title":"ReaderBrowserConfiguration","url":"\/documentation\/psreaderui\/readerbrowserconfiguration","role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderBrowserConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration object used to customize the appearance of the reader content browser."}],"navigatorTitle":[{"text":"ReaderBrowserConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LegacyImageResourceName":{"type":"topic","navigatorTitle":[{"text":"LegacyImageResourceName","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyImageResourceName","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LegacyImageResourceName","kind":"identifier"}],"role":"symbol","url":"\/documentation\/psreaderui\/legacyimageresourcename","abstract":[{"text":"Enumeration of asset identifiers used specifically by the legacy reader.","type":"text"}],"title":"LegacyImageResourceName"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LabelConfiguration":{"abstract":[{"type":"text","text":"Configuration object that specifies the appearance of "},{"type":"codeVoice","code":"UILabels"},{"type":"text","text":" used"},{"type":"text","text":" "},{"type":"text","text":"throughout the PSReaderUI SDK."}],"title":"LabelConfiguration","url":"\/documentation\/psreaderui\/labelconfiguration","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LabelConfiguration"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LabelConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LabelConfiguration"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration/secondaryFont":{"title":"secondaryFont","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration\/secondaryFont","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"kind":"symbol","url":"\/documentation\/psreaderui\/globalconfiguration\/secondaryfont","type":"topic","abstract":[{"text":"The secondary font used throughout the SDK’s UI. This is used for general UI labels.","type":"text"}],"role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SubsectionRibbonConfiguration":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SubsectionRibbonConfiguration","type":"topic","url":"\/documentation\/psreaderui\/subsectionribbonconfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SubsectionRibbonConfiguration","kind":"identifier"}],"title":"SubsectionRibbonConfiguration","abstract":[{"type":"text","text":"Configuration used to customize the appearance and layout of the carousel subsection ribbon."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SubsectionRibbonConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Localization":{"url":"\/documentation\/psreaderui\/localization","type":"topic","title":"Localization","abstract":[{"type":"text","text":"Localize all user-facing strings in the PSReaderUI SDK."}],"kind":"article","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderConfiguration/useLegacyReplicaReader":{"kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration\/useLegacyReplicaReader","type":"topic","title":"useLegacyReplicaReader","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useLegacyReplicaReader","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","abstract":[{"text":"When ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", uses the legacy replica reader instead of the modern implementation.","type":"text"}],"url":"\/documentation\/psreaderui\/readerconfiguration\/uselegacyreplicareader"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LiquidGlassPolicy":{"type":"topic","kind":"symbol","title":"LiquidGlassPolicy","navigatorTitle":[{"text":"LiquidGlassPolicy","kind":"identifier"}],"url":"\/documentation\/psreaderui\/liquidglasspolicy","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LiquidGlassPolicy","abstract":[{"type":"text","text":"A policy describing how the SDK adopts the iOS Liquid Glass UI effect."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiquidGlassPolicy","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveConfiguration/cellAspectRatio":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration\/cellAspectRatio","type":"topic","title":"cellAspectRatio","abstract":[{"type":"text","text":"Aspect ratio for thumbnails representing editions in the archive view."}],"role":"symbol","kind":"symbol","url":"\/documentation\/psreaderui\/archiveconfiguration\/cellaspectratio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"Customization","identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"],"generated":true,"title":"Customization"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}