{"kind":"symbol","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"metadata":{"role":"collection","externalID":"PSReaderUI","roleHeading":"Framework","symbolKind":"module","title":"PSReaderUI","modules":[{"name":"PSReaderUI"}]},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"PSReaderUI provides a complete, customizable interface layer on top of the PSReader SDK.","type":"text"},{"text":" ","type":"text"},{"text":"It handles edition browsing, reading, bookmarking, downloading, and more — letting you","type":"text"},{"text":" ","type":"text"},{"text":"ship a fully-featured digital publication reader with minimal integration work.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK supports PageSuite’s two content systems:"}]},{"items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Feed Editions","type":"text"}]},{"text":" — the modern system with mixed HTML and PDF content.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Replica Editions","type":"text"}]},{"type":"text","text":" — the legacy PDF-only system."}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"Consult the PageSuite portal or your account manager to determine which system your","type":"text"},{"text":" ","type":"text"},{"text":"publications use. See ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","type":"reference"},{"text":" for details.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The primary entry point is ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","type":"reference"},{"text":", initialized with a","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","type":"reference"},{"text":" and one or more content sections. The recommended approach","type":"text"},{"text":" ","type":"text"},{"text":"uses a ","type":"text"},{"inlineContent":[{"type":"text","text":"shortcode"}],"type":"strong"},{"text":" to load content dynamically:","type":"text"}]},{"type":"codeListing","code":["import PSReaderUI","","let globalConfig = GlobalConfiguration(","    apiKey: \"YOUR_API_KEY\",","    accountGUID: \"YOUR_ACCOUNT_GUID\"",")","","let carousel = CarouselViewController(","    globalConfig: globalConfig,","    sections: [","        .dynamicArchive(\"Editions\", shortcode: \"YOUR_SHORTCODE\")","    ]",")"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started"},{"text":" for a complete walkthrough. A ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Demo-Project"},{"text":" is","type":"text"},{"text":" ","type":"text"},{"text":"also available.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/psreaderui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/psreaderui"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Demo-Project"],"anchor":"Essentials","title":"Essentials"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions"],"anchor":"Concepts","title":"Concepts"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"],"anchor":"Customization","title":"Customization"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"anchor":"Features","title":"Features"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LiquidGlassPolicy","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode"],"anchor":"General-Configuration","title":"General Configuration"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderNavigationBarConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderBrowserConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderSplashConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SettingsConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyReaderConfiguration"],"anchor":"Reader-Configuration","title":"Reader Configuration"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveDatePickerConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsConfiguration"],"anchor":"Archive-Configuration","title":"Archive Configuration"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SectionRibbonConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SubsectionRibbonConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ButtonConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LabelConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ContentUnavailableConfiguration"],"anchor":"Carousel-Configuration","title":"Carousel Configuration"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EditionDateFormatter","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultEditionDateFormatter"],"anchor":"Date-Formatting","title":"Date Formatting"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallViewController","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertViewController","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/NavigationDelegate"],"anchor":"Delegates","title":"Delegates"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareProvider","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareContext","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/WebReaderShareProvider","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArticleLinkShareProvider"],"anchor":"Sharing-Types","title":"Sharing Types"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlay","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlayConfiguration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioBannerViewController","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechArticleFormatter","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechArticleFormatter","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechSynthesizer","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechSynthesizer","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioSessionProvider","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultAudioSessionProvider"],"anchor":"Text-to-Speech-Types","title":"Text-to-Speech Types"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultAssetProvider","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageResourceName","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyImageResourceName"],"anchor":"Asset-Customization","title":"Asset Customization"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizedStringKey"],"anchor":"Localization-Types","title":"Localization Types"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventSubscriber"],"anchor":"Analytics-Types","title":"Analytics Types"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/KioskReplicaPublication","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/KioskFeedPublication"],"anchor":"Kiosk","title":"Kiosk"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController"],"anchor":"View-Controllers","title":"View Controllers"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Migration-Guides","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log"],"anchor":"Release-Notes","title":"Release Notes"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CopyLinkActivity"],"anchor":"Classes","title":"Classes","generated":true}],"references":{"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioDelegate":{"title":"AudioDelegate","abstract":[{"type":"text","text":"Delegate protocol used to provide audio playback functionality within the SDK."}],"url":"\/documentation\/psreaderui\/audiodelegate","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AudioDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDelegate","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/TextToSpeechSynthesizer":{"url":"\/documentation\/psreaderui\/texttospeechsynthesizer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextToSpeechSynthesizer"}],"navigatorTitle":[{"kind":"identifier","text":"TextToSpeechSynthesizer"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechSynthesizer","role":"symbol","type":"topic","title":"TextToSpeechSynthesizer","abstract":[{"type":"text","text":"Protocol for synthesizing text into speech audio."}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/MediaDelegate":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MediaDelegate","kind":"identifier"}],"url":"\/documentation\/psreaderui\/mediadelegate","abstract":[{"text":"Defines methods to provide custom media functionality.","type":"text"}],"title":"MediaDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/MediaDelegate"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CopyLinkActivity":{"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/psreaderui\/copylinkactivity","title":"CopyLinkActivity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CopyLinkActivity","kind":"identifier"}],"navigatorTitle":[{"text":"CopyLinkActivity","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CopyLinkActivity","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/PSReaderUIVersionString":{"role":"symbol","url":"\/documentation\/psreaderui\/psreaderuiversionstring","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PSReaderUIVersionString","type":"topic","kind":"symbol","title":"PSReaderUIVersionString","abstract":[{"text":"Project version string for PSReaderUI.","type":"text"}],"fragments":[{"text":"PSReaderUIVersionString","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Demo-Project":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Demo-Project","role":"article","url":"\/documentation\/psreaderui\/demo-project","abstract":[{"type":"text","text":"A complete Xcode project demonstrating PSReaderUI SDK integration."}],"title":"Demo Project","kind":"article","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/PaywallViewController":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaywallViewController"}],"type":"topic","abstract":[{"text":"A view controller protocol used by the SDK to present paywalls when","type":"text"},{"text":" ","type":"text"},{"text":"accessing restricted content.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallViewController","navigatorTitle":[{"kind":"identifier","text":"PaywallViewController"}],"url":"\/documentation\/psreaderui\/paywallviewcontroller","kind":"symbol","title":"PaywallViewController"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarouselConfiguration"}],"abstract":[{"type":"text","text":"Configuration object for customizing the PSReaderUI carousel interface."}],"navigatorTitle":[{"kind":"identifier","text":"CarouselConfiguration"}],"title":"CarouselConfiguration","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselConfiguration","url":"\/documentation\/psreaderui\/carouselconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Sharing":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","abstract":[{"type":"text","text":"Configure how users share edition content from the reader."}],"type":"topic","kind":"article","url":"\/documentation\/psreaderui\/sharing","title":"Sharing","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ImageContentMode":{"kind":"symbol","title":"ImageContentMode","abstract":[{"text":"Defines how an image should be resized and positioned within its container.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageContentMode"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageContentMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageContentMode"}],"type":"topic","url":"\/documentation\/psreaderui\/imagecontentmode"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LiquidGlassPolicy":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LiquidGlassPolicy"}],"title":"LiquidGlassPolicy","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A policy describing how the SDK adopts the iOS Liquid Glass UI effect."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiquidGlassPolicy"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LiquidGlassPolicy","url":"\/documentation\/psreaderui\/liquidglasspolicy"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Analytics":{"type":"topic","title":"Analytics","abstract":[{"text":"Track user interactions and content engagement across the PSReaderUI SDK.","type":"text"}],"url":"\/documentation\/psreaderui\/analytics","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics","kind":"article","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Advertisements":{"url":"\/documentation\/psreaderui\/advertisements","type":"topic","abstract":[{"text":"Display custom advertisements within the reader.","type":"text"}],"kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","role":"article","title":"Advertisements"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ShareContext":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShareContext"}],"role":"symbol","title":"ShareContext","type":"topic","url":"\/documentation\/psreaderui\/sharecontext","navigatorTitle":[{"kind":"identifier","text":"ShareContext"}],"abstract":[{"type":"text","text":"A structure encapsulating information used to present shareable content."}],"kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareContext"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ShareDelegate":{"navigatorTitle":[{"text":"ShareDelegate","kind":"identifier"}],"url":"\/documentation\/psreaderui\/sharedelegate","role":"symbol","title":"ShareDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ShareDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol used to provide sharing functionality within the SDK."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SubsectionRibbonConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SubsectionRibbonConfiguration"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Configuration used to customize the appearance and layout of the carousel subsection ribbon.","type":"text"}],"title":"SubsectionRibbonConfiguration","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SubsectionRibbonConfiguration","url":"\/documentation\/psreaderui\/subsectionribbonconfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubsectionRibbonConfiguration"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DownloadsViewController":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadsViewController"}],"title":"DownloadsViewController","abstract":[{"type":"text","text":"A standalone view controller for displaying downloaded editions."}],"url":"\/documentation\/psreaderui\/downloadsviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DownloadsViewController"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ContentUnavailableConfiguration":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ContentUnavailableConfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration for customizing the appearance and behavior of content unavailable screens."}],"title":"ContentUnavailableConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentUnavailableConfiguration"}],"url":"\/documentation\/psreaderui\/contentunavailableconfiguration","navigatorTitle":[{"kind":"identifier","text":"ContentUnavailableConfiguration"}],"type":"topic","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultTextToSpeechProvider":{"url":"\/documentation\/psreaderui\/defaulttexttospeechprovider","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultTextToSpeechProvider"}],"abstract":[{"text":"A complete text-to-speech implementation providing ready-to-use audio functionality.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"DefaultTextToSpeechProvider","navigatorTitle":[{"text":"DefaultTextToSpeechProvider","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Getting-Started":{"abstract":[{"type":"text","text":"The PSReaderUI SDK provides a flexible, modern UI for integrating the PageSuite"},{"type":"text","text":" "},{"type":"text","text":"PSReader SDK into your application."}],"kind":"article","title":"Getting Started","type":"topic","url":"\/documentation\/psreaderui\/getting-started","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/PaywallDelegate":{"url":"\/documentation\/psreaderui\/paywalldelegate","abstract":[{"text":"A delegate protocol used to provide paywall view controllers for controlling","type":"text"},{"text":" ","type":"text"},{"text":"access to premium content within the SDK.","type":"text"}],"title":"PaywallDelegate","role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PaywallDelegate","navigatorTitle":[{"kind":"identifier","text":"PaywallDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaywallDelegate"}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Text-to-Speech":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","url":"\/documentation\/psreaderui\/text-to-speech","kind":"article","type":"topic","abstract":[{"type":"text","text":"Add audio playback of article content using the SDK’s text-to-speech system."}],"title":"Text-to-Speech","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EditionDateFormatter":{"role":"symbol","title":"EditionDateFormatter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EditionDateFormatter"}],"abstract":[{"type":"text","text":"A protocol defining methods for generating display strings to represent editions."}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EditionDateFormatter","kind":"symbol","url":"\/documentation\/psreaderui\/editiondateformatter","navigatorTitle":[{"kind":"identifier","text":"EditionDateFormatter"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventSubscriber":{"navigatorTitle":[{"text":"EventSubscriber","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that listens to analytics events broadcast from an "},{"type":"codeVoice","code":"EventChannel"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventSubscriber","kind":"symbol","url":"\/documentation\/psreaderui\/eventsubscriber","title":"EventSubscriber","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventSubscriber","kind":"identifier"}],"role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LegacyReaderConfiguration":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegacyReaderConfiguration"}],"kind":"symbol","title":"LegacyReaderConfiguration","abstract":[{"text":"Configuration object for customizing the appearance, behavior, and sharing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"strategies of the legacy replica reader."}],"role":"symbol","url":"\/documentation\/psreaderui\/legacyreaderconfiguration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyReaderConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegacyReaderConfiguration"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderBrowserConfiguration":{"abstract":[{"text":"Configuration object used to customize the appearance of the reader content browser.","type":"text"}],"title":"ReaderBrowserConfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderBrowserConfiguration","navigatorTitle":[{"kind":"identifier","text":"ReaderBrowserConfiguration"}],"url":"\/documentation\/psreaderui\/readerbrowserconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReaderBrowserConfiguration"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Localization":{"title":"Localization","kind":"article","url":"\/documentation\/psreaderui\/localization","role":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization","abstract":[{"type":"text","text":"Localize all user-facing strings in the PSReaderUI SDK."}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Replica-and-Feed-Editions":{"title":"Replica and Feed Editions","type":"topic","role":"article","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions","abstract":[{"type":"text","text":"Understand the two backend systems that power PSReaderUI content."}],"url":"\/documentation\/psreaderui\/replica-and-feed-editions"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/KioskReplicaPublication":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/KioskReplicaPublication","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KioskReplicaPublication"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KioskReplicaPublication"}],"abstract":[{"type":"text","text":"Describes a replica publication entry in a kiosk grid."}],"url":"\/documentation\/psreaderui\/kioskreplicapublication","type":"topic","kind":"symbol","title":"KioskReplicaPublication"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ButtonConfiguration":{"abstract":[{"text":"Configuration object used to customize buttons displayed within the SDK’s UI.","type":"text"}],"type":"topic","url":"\/documentation\/psreaderui\/buttonconfiguration","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"ButtonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ButtonConfiguration","title":"ButtonConfiguration","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/WebReaderShareProvider":{"navigatorTitle":[{"kind":"identifier","text":"WebReaderShareProvider"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate","isActive":true},{"type":"text","text":" that provides shareable links to the web reader pages."},{"type":"text","text":" "},{"type":"text","text":"Use this provider to generate URLs pointing to web reader content."}],"title":"WebReaderShareProvider","type":"topic","role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/WebReaderShareProvider","kind":"symbol","url":"\/documentation\/psreaderui\/webreadershareprovider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebReaderShareProvider"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LocalizationManager":{"navigatorTitle":[{"text":"LocalizationManager","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalizationManager","kind":"identifier"}],"title":"LocalizationManager","type":"topic","abstract":[{"text":"Provides localized strings.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizationManager","url":"\/documentation\/psreaderui\/localizationmanager","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ShareProvider":{"title":"ShareProvider","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShareProvider"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShareProvider"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareProvider","url":"\/documentation\/psreaderui\/shareprovider","kind":"symbol","abstract":[{"text":"A composite share provider allowing multiple share strategies to be chained.","type":"text"},{"text":" ","type":"text"},{"text":"Configure this provider to choose preferred or fallback sharing behaviors.","type":"text"}],"role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/PSReaderUIVersionNumber":{"kind":"symbol","url":"\/documentation\/psreaderui\/psreaderuiversionnumber","title":"PSReaderUIVersionNumber","abstract":[{"text":"Project version number for PSReaderUI.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"PSReaderUIVersionNumber"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PSReaderUIVersionNumber"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderConfiguration","url":"\/documentation\/psreaderui\/readerconfiguration","role":"symbol","abstract":[{"text":"Configuration object for customizing the PSReaderUI Reader.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderConfiguration","kind":"identifier"}],"title":"ReaderConfiguration","navigatorTitle":[{"text":"ReaderConfiguration","kind":"identifier"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Standalone-View-Controllers":{"abstract":[{"text":"Use archive, bookmarks, and downloads views outside of the carousel.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","kind":"article","type":"topic","role":"article","title":"Standalone View Controllers","url":"\/documentation\/psreaderui\/standalone-view-controllers"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArchiveConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveConfiguration","url":"\/documentation\/psreaderui\/archiveconfiguration","title":"ArchiveConfiguration","navigatorTitle":[{"text":"ArchiveConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration for customizing the appearance and behavior of publication archive views."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LocalizedStringKey":{"url":"\/documentation\/psreaderui\/localizedstringkey","kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LocalizedStringKey","navigatorTitle":[{"text":"LocalizedStringKey","kind":"identifier"}],"title":"LocalizedStringKey","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalizedStringKey","kind":"identifier"}],"abstract":[{"text":"Defines keys used to identify localizable strings in the SDK.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioSessionProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioSessionProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AudioSessionProvider","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioSessionProvider","kind":"symbol","abstract":[{"type":"text","text":"Protocol for managing audio session lifecycle and interruption handling."}],"url":"\/documentation\/psreaderui\/audiosessionprovider","type":"topic","title":"AudioSessionProvider"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderSplashConfiguration":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderSplashConfiguration","navigatorTitle":[{"kind":"identifier","text":"ReaderSplashConfiguration"}],"type":"topic","kind":"symbol","title":"ReaderSplashConfiguration","abstract":[{"type":"text","text":"Configuration object for customizing the splash screen displayed when opening"},{"type":"text","text":" "},{"type":"text","text":"a published edition. The splash screen provides visual feedback during content"},{"type":"text","text":" "},{"type":"text","text":"loading transitions, displaying the edition’s thumbnail, name, date, loading status."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReaderSplashConfiguration"}],"role":"symbol","url":"\/documentation\/psreaderui\/readersplashconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/KioskFeedPublication":{"navigatorTitle":[{"kind":"identifier","text":"KioskFeedPublication"}],"abstract":[{"type":"text","text":"Describes a feed publication entry in a kiosk grid."}],"role":"symbol","title":"KioskFeedPublication","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/KioskFeedPublication","type":"topic","kind":"symbol","url":"\/documentation\/psreaderui\/kioskfeedpublication","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"KioskFeedPublication"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultEditionDateFormatter":{"navigatorTitle":[{"kind":"identifier","text":"DefaultEditionDateFormatter"}],"title":"DefaultEditionDateFormatter","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultEditionDateFormatter"}],"abstract":[{"type":"text","text":"Default implementation of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EditionDateFormatter"},{"type":"text","text":" using "},{"type":"codeVoice","code":"DateFormatter"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/psreaderui\/defaulteditiondateformatter","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultEditionDateFormatter"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SectionRibbonConfiguration":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SectionRibbonConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SectionRibbonConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration object controlling the appearance and layout of the carousel section ribbon.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SectionRibbonConfiguration","title":"SectionRibbonConfiguration","url":"\/documentation\/psreaderui\/sectionribbonconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AdvertViewController":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdvertViewController","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"AdvertViewController","kind":"identifier"}],"url":"\/documentation\/psreaderui\/advertviewcontroller","abstract":[{"text":"A protocol representing a view controller used for displaying advertisements","type":"text"},{"text":" ","type":"text"},{"text":"within the PSReaderUI SDK.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertViewController","title":"AdvertViewController","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ImageResourceName":{"title":"ImageResourceName","url":"\/documentation\/psreaderui\/imageresourcename","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ImageResourceName","kind":"symbol","role":"symbol","abstract":[{"text":"An enumeration of asset identifiers used by the SDK’s UI components.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageResourceName"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageResourceName"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioOverlayConfiguration":{"title":"AudioOverlayConfiguration","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlayConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOverlayConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"AudioOverlayConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration structure for customizing the appearance of audio overlays."}],"kind":"symbol","role":"symbol","url":"\/documentation\/psreaderui\/audiooverlayconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultAudioSessionProvider":{"title":"DefaultAudioSessionProvider","role":"symbol","type":"topic","abstract":[{"text":"Default implementation of audio session management.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultAudioSessionProvider","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultAudioSessionProvider","navigatorTitle":[{"text":"DefaultAudioSessionProvider","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/psreaderui\/defaultaudiosessionprovider"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioOverlay":{"title":"AudioOverlay","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOverlay"}],"navigatorTitle":[{"kind":"identifier","text":"AudioOverlay"}],"kind":"symbol","abstract":[{"text":"A custom view controller designed for presenting audio playback interfaces as overlays.","type":"text"}],"type":"topic","url":"\/documentation\/psreaderui\/audiooverlay","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Migration-Guides":{"kind":"article","abstract":[{"type":"text","text":"Guidance to help you smoothly transition your app to newer versions of the SDK."},{"type":"text","text":" "},{"type":"text","text":"This page highlights breaking changes, necessary updates, and recommended"},{"type":"text","text":" "},{"type":"text","text":"practices when migrating between versions."}],"role":"article","title":"Migration Guides","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Migration-Guides","url":"\/documentation\/psreaderui\/migration-guides","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArchiveViewController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A standalone view controller for displaying publication archives."}],"kind":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveViewController","navigatorTitle":[{"text":"ArchiveViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/psreaderui\/archiveviewcontroller","title":"ArchiveViewController"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/BookmarksViewController":{"abstract":[{"type":"text","text":"A standalone view controller for displaying bookmarked pages and articles."}],"navigatorTitle":[{"text":"BookmarksViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BookmarksViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/psreaderui\/bookmarksviewcontroller","kind":"symbol","title":"BookmarksViewController"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultTextToSpeechSynthesizer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultTextToSpeechSynthesizer"}],"kind":"symbol","title":"DefaultTextToSpeechSynthesizer","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechSynthesizer","navigatorTitle":[{"kind":"identifier","text":"DefaultTextToSpeechSynthesizer"}],"url":"\/documentation\/psreaderui\/defaulttexttospeechsynthesizer","abstract":[{"type":"text","text":"Default implementation of text-to-speech synthesis using the system’s TTS capabilities."}],"role":"symbol","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ReaderNavigationBarConfiguration":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ReaderNavigationBarConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderNavigationBarConfiguration","kind":"identifier"}],"url":"\/documentation\/psreaderui\/readernavigationbarconfiguration","title":"ReaderNavigationBarConfiguration","role":"symbol","type":"topic","abstract":[{"text":"Configuration object for customizing reader navigation bars.","type":"text"}],"navigatorTitle":[{"text":"ReaderNavigationBarConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/SettingsConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SettingsConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsConfiguration"}],"kind":"symbol","title":"SettingsConfiguration","url":"\/documentation\/psreaderui\/settingsconfiguration","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/SettingsConfiguration","abstract":[{"text":"Configuration object used to customize the reader’s settings menu.","type":"text"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/TextToSpeechArticleFormatter":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Protocol for formatting articles into text suitable for speech synthesis."}],"url":"\/documentation\/psreaderui\/texttospeecharticleformatter","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextToSpeechArticleFormatter","kind":"identifier"}],"title":"TextToSpeechArticleFormatter","navigatorTitle":[{"text":"TextToSpeechArticleFormatter","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/TextToSpeechArticleFormatter"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/NavigationDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NavigationDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NavigationDelegate","kind":"identifier"}],"title":"NavigationDelegate","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/NavigationDelegate","abstract":[{"type":"text","text":"A delegate protocol for navigation events in "},{"code":"PSReaderUI","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/psreaderui\/navigationdelegate","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DownloadsConfiguration":{"role":"symbol","abstract":[{"type":"text","text":"Configuration for customizing the appearance and behavior of download archives."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DownloadsConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DownloadsConfiguration","navigatorTitle":[{"text":"DownloadsConfiguration","kind":"identifier"}],"kind":"symbol","title":"DownloadsConfiguration","url":"\/documentation\/psreaderui\/downloadsconfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/EventChannel":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/EventChannel","role":"symbol","url":"\/documentation\/psreaderui\/eventchannel","type":"topic","abstract":[{"type":"text","text":"Singleton class responsible for analytics reporting."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventChannel","kind":"identifier"}],"navigatorTitle":[{"text":"EventChannel","kind":"identifier"}],"kind":"symbol","title":"EventChannel"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AudioBannerViewController":{"title":"AudioBannerViewController","role":"symbol","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AudioBannerViewController","kind":"symbol","abstract":[{"type":"text","text":"A view controller used to present persistent audio controls as a banner."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioBannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"AudioBannerViewController"}],"url":"\/documentation\/psreaderui\/audiobannerviewcontroller","type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Media-Playback":{"kind":"article","title":"Media Playback","url":"\/documentation\/psreaderui\/media-playback","type":"topic","role":"article","abstract":[{"text":"Enable video and media playback within the reader.","type":"text"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/CarouselViewController":{"role":"symbol","kind":"symbol","title":"CarouselViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarouselViewController"}],"abstract":[{"type":"text","text":"The primary view controller provided by the SDK for presenting digital publication"},{"type":"text","text":" "},{"type":"text","text":"content through an intuitive carousel interface."}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/CarouselViewController","type":"topic","url":"\/documentation\/psreaderui\/carouselviewcontroller","navigatorTitle":[{"kind":"identifier","text":"CarouselViewController"}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AdvertDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AdvertDelegate","title":"AdvertDelegate","kind":"symbol","url":"\/documentation\/psreaderui\/advertdelegate","navigatorTitle":[{"text":"AdvertDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdvertDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"A delegate protocol to enable custom advertising placements within the SDK."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/BookmarksConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BookmarksConfiguration"}],"title":"BookmarksConfiguration","url":"\/documentation\/psreaderui\/bookmarksconfiguration","abstract":[{"text":"Configuration for customizing the appearance and behavior of bookmark archives.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BookmarksConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/BookmarksConfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/AssetDelegate":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate","title":"AssetDelegate","abstract":[{"type":"text","text":"A delegate protocol for providing custom images and logos used within the SDK."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AssetDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AssetDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/psreaderui\/assetdelegate","role":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/GlobalConfiguration":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/GlobalConfiguration","type":"topic","role":"symbol","title":"GlobalConfiguration","abstract":[{"type":"text","text":"A configuration object that provides global settings and delegates for"},{"type":"text","text":" "},{"type":"text","text":"customizing the SDK’s behavior and appearance."}],"navigatorTitle":[{"kind":"identifier","text":"GlobalConfiguration"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GlobalConfiguration"}],"url":"\/documentation\/psreaderui\/globalconfiguration","kind":"symbol"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultTextToSpeechArticleFormatter":{"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultTextToSpeechArticleFormatter","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultTextToSpeechArticleFormatter"}],"role":"symbol","url":"\/documentation\/psreaderui\/defaulttexttospeecharticleformatter","navigatorTitle":[{"kind":"identifier","text":"DefaultTextToSpeechArticleFormatter"}],"abstract":[{"type":"text","text":"Default implementation of text-to-speech article formatting."}],"kind":"symbol","type":"topic","title":"DefaultTextToSpeechArticleFormatter"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Theming-and-Customization":{"type":"topic","title":"Theming and Customization","abstract":[{"type":"text","text":"Adjust fonts, colors, icons, and layouts to match your app’s brand."}],"url":"\/documentation\/psreaderui\/theming-and-customization","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","role":"article","kind":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI":{"url":"\/documentation\/psreaderui","type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI","kind":"symbol","title":"PSReaderUI","abstract":[{"type":"text","text":"A UI framework for building digital newspaper and magazine reader experiences on iOS."}],"role":"collection"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArchiveDatePickerConfiguration":{"role":"symbol","title":"ArchiveDatePickerConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArchiveDatePickerConfiguration"}],"url":"\/documentation\/psreaderui\/archivedatepickerconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArchiveDatePickerConfiguration"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArchiveDatePickerConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration object for customizing the appearance and behavior of the"},{"type":"text","text":" "},{"type":"text","text":"archive date picker within the SDK."}]},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Paywall-Integration":{"title":"Paywall Integration","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","abstract":[{"text":"Restrict access to premium content with custom paywall screens.","type":"text"}],"url":"\/documentation\/psreaderui\/paywall-integration","type":"topic","kind":"article","role":"article"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LabelConfiguration":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LabelConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"LabelConfiguration"}],"type":"topic","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LabelConfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration object that specifies the appearance of "},{"code":"UILabels","type":"codeVoice"},{"type":"text","text":" used"},{"type":"text","text":" "},{"type":"text","text":"throughout the PSReaderUI SDK."}],"kind":"symbol","url":"\/documentation\/psreaderui\/labelconfiguration","title":"LabelConfiguration"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/LegacyImageResourceName":{"title":"LegacyImageResourceName","navigatorTitle":[{"text":"LegacyImageResourceName","kind":"identifier"}],"identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/LegacyImageResourceName","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Enumeration of asset identifiers used specifically by the legacy reader."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LegacyImageResourceName","kind":"identifier"}],"url":"\/documentation\/psreaderui\/legacyimageresourcename"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Carousel-Setup":{"title":"Carousel Setup","type":"topic","role":"article","kind":"article","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","abstract":[{"type":"text","text":"Configure the carousel’s sections, content sources, and layout."}],"url":"\/documentation\/psreaderui\/carousel-setup"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/ArticleLinkShareProvider":{"title":"ArticleLinkShareProvider","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ArticleLinkShareProvider","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleLinkShareProvider","kind":"identifier"}],"url":"\/documentation\/psreaderui\/articlelinkshareprovider","navigatorTitle":[{"text":"ArticleLinkShareProvider","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/ShareDelegate","isActive":true},{"type":"text","text":" providing direct article links on the publication’s website."}],"type":"topic"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/Change-Log":{"title":"Change Log","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log","kind":"article","abstract":[{"type":"text","text":"Track new features, improvements, bug fixes, and other updates in each"},{"type":"text","text":" "},{"type":"text","text":"PSReaderUI SDK release."}],"type":"topic","role":"article","url":"\/documentation\/psreaderui\/change-log"},"doc://com.pagesuite.PSReaderUI/documentation/PSReaderUI/DefaultAssetProvider":{"role":"symbol","kind":"symbol","title":"DefaultAssetProvider","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/DefaultAssetProvider","abstract":[{"type":"text","text":"A default implementation of the "},{"type":"reference","identifier":"doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/AssetDelegate","isActive":true},{"type":"text","text":" protocol that provides the SDK’s built-in assets."}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DefaultAssetProvider","kind":"identifier"}],"navigatorTitle":[{"text":"DefaultAssetProvider","kind":"identifier"}],"url":"\/documentation\/psreaderui\/defaultassetprovider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Getting-Started","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Demo-Project"],"anchor":"Essentials","title":"Essentials"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Replica-and-Feed-Editions"],"anchor":"Concepts","title":"Concepts"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Theming-and-Customization","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Carousel-Setup","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Standalone-View-Controllers","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Localization"],"anchor":"Customization","title":"Customization"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Paywall-Integration","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Sharing","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Text-to-Speech","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Advertisements","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Media-Playback","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Analytics"],"anchor":"Features","title":"Features"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Migration-Guides","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/Change-Log"],"anchor":"Release-Notes","title":"Release Notes"},{"identifiers":["doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PSReaderUIVersionNumber","doc:\/\/com.pagesuite.PSReaderUI\/documentation\/PSReaderUI\/PSReaderUIVersionString"],"generated":true,"title":"Variables","anchor":"Variables"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}